### ISSUE TITLE
`read_row_group` throws `KeyError` when selecting an array column

### ISSUE THREAD

**Issue by vafl** [apache/arrow#1207]
There seems to be a bug that occurs when an array column is explicitly selected with the `columns` parameter of `read_row_groups`. Below is a minimal example to reproduce the issue. 

(pyarrow version 0.7.1)

```python
import pyarrow as pa
import pyarrow.parquet as pq
import pandas as pd
import numpy as np

# write a parquet file with an array column
n = 13
a = [np.random.random(10) for i in range(n)]
b = [i for i in range(n)]
df = pd.DataFrame({'a': a, 'b': b})
fname = 'test.parquet'
tbl = pa.Table.from_pandas(df)
pq.write_table(tbl, fname)

pqf = pq.ParquetFile(fname)
print(pqf.schema)
# returns:
# <pyarrow._parquet.ParquetSchema object at 0x10dd198c8>
# a.list.item: DOUBLE
# b: INT64
# __index_level_0__: INT64

# this works
df_1 = pqf.read_row_group(0).to_pandas()

# this works
df_2 = pqf.read_row_group(0, columns=['b']).to_pandas()

# these two throw an exception
df_3 = pqf.read_row_group(0, columns=['a']).to_pandas()
df_4 = pqf.read_row_group(0, columns=['a', 'b']).to_pandas()

# Traceback (most recent call last):
#   File "bug.py", line 25, in <module>
#     df_3 = pqf.read_row_group(0, columns=['a']).to_pandas()
#   File "/usr/local/lib/python3.6/site-packages/pyarrow/parquet.py", line 91, in read_row_group
#     columns, use_pandas_metadata=use_pandas_metadata)
#   File "/usr/local/lib/python3.6/site-packages/pyarrow/parquet.py", line 124, in _get_column_indices
#     indices = list(map(self.reader.column_name_idx, column_names))
#   File "pyarrow/_parquet.pyx", line 496, in pyarrow._parquet.ParquetReader.column_name_idx (/Users/travis/build/apache/arrow-dist/arrow/python/build/temp.macosx-10.6-intel-3.6/_parquet.cxx:9523)
# KeyError: b'a'
```

**Comment by wesm** [comment]
If you pass `a.list.item` instead of `a` it should work. I opened https://issues.apache.org/jira/browse/ARROW-1684 ARROW-1684 about improving the usability of this API for nested columns

**Comment by vafl** [comment]
Great, thanks. that works
