### ISSUE TITLE
[python] Add a pyarrow.Table.aggregate function to compute aggregates against the whole table

### ISSUE THREAD

**Issue by westonpace** [apache/arrow#14896]
### Describe the enhancement requested

The implementation would be almost identical to pyarrow.TableGroupBy.aggregate except the keys list would be empty.  Currently this does not appear to be possible using an empty array of keys:

```
>>> tab.group_by([]).aggregate([("x", "sum")])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/table.pxi", line 5325, in pyarrow.lib.TableGroupBy.aggregate
  File "pyarrow/_compute.pyx", line 2145, in pyarrow._compute._group_by
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Cannot infer ExecBatch length without at least one value
```

Even if it were possible, I don't think it would be obvious to obtain the result in this way.

### Component(s)

Python

**Comment by westonpace** [comment]
Note, we may want to wait until #14867 merges as the corresponding C++ functionality will be more obvious (and tested)

**Comment by coady** [comment]
Also related to #33832. Because if it's worth doing for tables, it would be even more valuable on datasets or scanners, for out-of-core aggregation.

**Comment by thisisnic** [comment]
This issue has been marked as stale because it has had no activity in the past 2 years. Please remove the stale label or comment below, or this issue will be closed in 14 days.
