### ISSUE TITLE
[CI] Appveyor failing with error related to libmambapy

### ISSUE THREAD

**Issue by westonpace** [apache/arrow#14897]
### Describe the bug, including details regarding any error messages, version, and platform.

It appears that, at some point today, seemingly unrelated to commits, appveyor began regularly failing with this error:

```
C:\projects\arrow>mamba update -q -y -c conda-forge --all   || exit /B 
Traceback (most recent call last):
  File "C:\Miniconda38-x64\Scripts\mamba-script.py", line 6, in <module>
    from mamba.mamba import main
  File "C:\Miniconda38-x64\lib\site-packages\mamba\mamba.py", line 49, in <module>
    import libmambapy as api
  File "C:\Miniconda38-x64\lib\site-packages\libmambapy\__init__.py", line 7, in <module>
    raise e
  File "C:\Miniconda38-x64\lib\site-packages\libmambapy\__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: DLL load failed while importing bindings: The specified module could not be found.
C:\projects\arrow>set lastexitcode=1 
```

Example: https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/45626144

### Component(s)

Continuous Integration

**Comment by kou** [comment]
I can't remember how to fix this but this has been fixed.
