### ISSUE TITLE
[Java] : Cannot export vectors with fields of type list<struct<....>> after using Writer APIs

### ISSUE THREAD

**Issue by irshadcc** [apache/arrow#14908]
### Describe the bug, including details regarding any error messages, version, and platform.

**Project Link** :  [Github Project Link](https://github.com/irshadcc/debug_projects)

I was trying to export some data with type list<struct<int, utf8>>  from Java and encountered this error.  The process is as follows. 
> 1. Initialize the schema and vector schema root with list<struct<int, utf8>>. 
> 2. Create the writers and write some data to the vectors. 
> 3. Export the vector schema root using C Data Interface
### Code

```java
package com.example.demo;

import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.List ;

import org.apache.arrow.c.ArrowArray;
import org.apache.arrow.c.ArrowSchema;
import org.apache.arrow.c.Data;
import org.apache.arrow.memory.ArrowBuf;
import org.apache.arrow.memory.RootAllocator;
import org.apache.arrow.vector.VectorSchemaRoot;
import org.apache.arrow.vector.complex.ListVector;
import org.apache.arrow.vector.complex.writer.IntWriter;
import org.apache.arrow.vector.complex.writer.VarCharWriter;
import org.apache.arrow.vector.complex.writer.BaseWriter.ListWriter;
import org.apache.arrow.vector.complex.writer.BaseWriter.StructWriter;
import org.apache.arrow.vector.types.pojo.ArrowType;
import org.apache.arrow.vector.types.pojo.Field;
import org.apache.arrow.vector.types.pojo.FieldType;
import org.apache.arrow.vector.types.pojo.Schema;

public class BugDemo 
{

    /* Allocator */
    private RootAllocator allocator ; 

    /* Schema and Vectors */
    private Schema schema ; 
    private VectorSchemaRoot vectorSchemaRoot ; 


    /* Writers */
    private ListWriter listWriter ;
    private StructWriter structWriter; 
    private IntWriter intWriter ;
    private VarCharWriter varCharWriter ;


    public void run() {
        /* Initialize */
        initSchemaAndVectors() ;
        initWriters();

        /* Write some data and export */
        writeData() ;
        System.out.println(vectorSchemaRoot.contentToTSVString());
        export(); // Error thrown in this function
        
        /* Close all */
        closeAll();
    }

    public void initSchemaAndVectors() {

        allocator = new RootAllocator();
        List<Field> fields = Arrays.asList(
            new Field("list_field", new FieldType(true, new ArrowType.List(), null), Arrays.asList(
                new Field("struct_field", new FieldType(true, new ArrowType.Struct(), null), Arrays.asList(
                    new Field("int_field", new FieldType(true, new ArrowType.Int(64, false), null), null),
                    new Field("var_char_field", new FieldType(true, new ArrowType.Utf8(), null), null)
                ))
            ))
        );

        schema = new Schema(fields) ; 
        vectorSchemaRoot = VectorSchemaRoot.create(schema, allocator);

    }

    public void initWriters() {

        listWriter = ((ListVector) vectorSchemaRoot.getVector("list_field")).getWriter() ;
        structWriter = listWriter.struct() ; 
        intWriter  = structWriter.integer("int_field");
        varCharWriter = structWriter.varChar("var_char_field");
    } 

    public void writeData() {
        /**
         * Write the following data 
         * Row 0 : [ {0, "value_0"} ]
         * Row 1 : [ {1, "value_1"} ]
         * Row 2 : [ {2, "value_2"} ]
         */

        Object[][] rows = new Object[][] {
            {0, "value_0"}, 
            {1, "value_1"},
            {2, "value_2"}
        };

        for (int i = 0 ; i < rows.length; i++) {
            listWriter.startList();
                structWriter.start();
                    intWriter.writeInt((int) rows[i][0]);
                    writeString(varCharWriter, (String) rows[i][1]);
                structWriter.end();
            listWriter.endList();
        }
        vectorSchemaRoot.setRowCount(rows.length);
    }

    public void export() {
        try (
            ArrowSchema arrowSchema = ArrowSchema.allocateNew(allocator);
            ArrowArray arrowArray = ArrowArray.allocateNew(allocator)
        ) {

            Data.exportSchema(allocator, schema, null, arrowSchema);
            Data.exportVectorSchemaRoot(allocator, vectorSchemaRoot, null, arrowArray);
            /* Consume the exported data in some other language by passing memory address. */
        }
    }

    public void closeAll() {
        vectorSchemaRoot.close();
        allocator.close();

    }


    /* Private methods */
    private void writeString(VarCharWriter writer, String value) {

        ArrowBuf buffer = allocator.buffer(256); 
        byte[] stringBytes = value.getBytes(StandardCharsets.UTF_8) ;
        buffer.writeBytes(stringBytes);
        writer.writeVarChar(0, stringBytes.length, buffer);
        buffer.close();
    }


    public static void main( String[] args )
    {
        BugDemo bugDemo = new BugDemo();
        bugDemo.run();
    }
}

```

### Output
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
list_field
[{"int_field":0,"var_char_field":"value_0"}]
[{"int_field":1,"var_char_field":"value_1"}]
[{"int_field":2,"var_char_field":"value_2"}]

Exception in thread "main" java.lang.IllegalArgumentException: not all nodes and buffers were consumed. nodes: [ArrowFieldNode [length=3, nullCount=0], ArrowFieldNode [length=3, nullCount=0]] buffers: [ArrowBuf[12], address:140565442268696, length:504, ArrowBuf[11], address:140565442252816, length:15880, ArrowBuf[13], address:140565442269200, length:32768]
	at org.apache.arrow.vector.StructVectorLoader.load(StructVectorLoader.java:97)
	at org.apache.arrow.c.Data.exportVectorSchemaRoot(Data.java:160)
	at org.apache.arrow.c.Data.exportVectorSchemaRoot(Data.java:133)
	at com.example.demo.BugDemo.export(BugDemo.java:116)
	at com.example.demo.BugDemo.run(BugDemo.java:53)
	at com.example.demo.BugDemo.main(BugDemo.java:141)
```

### Component(s)

Java

**Comment by lidavidm** [comment]
@irshadcc if you don't mind sharing, what ended up being the problem?

**Comment by irshadcc** [comment]
@lidavidm PromotableWriter changed the a field to Union Type causing mismatch between the schema and vector schema root's schema. I should have used structWriter.bigint() rather than structWriter.integer().
