### ISSUE TITLE
PyArrow 0.8.0 fails to create columns from a list

### ISSUE THREAD

**Issue by dmadeka** [apache/arrow#1801]
Pending the fix to the string arrays in `0.9.0`, I've been using `0.8.0`. Does anyone know why this fails in 0.8.0?

```python
>>> lst = np.random.randint(20000, size=10000).tolist()
>>> pa.lib.column('fcd', lst)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/table.pxi", line 186, in pyarrow.lib.column (/arrow/python/build/temp.linux-x86_64-2.7/lib.cxx:37799)
  File "pyarrow/table.pxi", line 158, in pyarrow.lib.chunked_array (/arrow/python/build/temp.linux-x86_64-2.7/lib.cxx:37598)
  File "pyarrow/array.pxi", line 174, in pyarrow.lib.array (/arrow/python/build/temp.linux-x86_64-2.7/lib.cxx:29283)
  File "pyarrow/array.pxi", line 25, in pyarrow.lib._sequence_to_array (/arrow/python/build/temp.linux-x86_64-2.7/lib.cxx:27875)
  File "pyarrow/error.pxi", line 87, in pyarrow.lib.check_status (/arrow/python/build/temp.linux-x86_64-2.7/lib.cxx:8645)
pyarrow.lib.ArrowTypeError: Object is not a sequence or iterable
```

**Comment by wesm** [comment]
Does this fail in 0.9.0? If so, could you create a JIRA with the bug report?

**Comment by dmadeka** [comment]
Works with 0.9.0! Curious which commit changed that --
