### ISSUE TITLE
pyarrow.lib.ArrowIOError when running PyTorch DataLoader in multithread

### ISSUE THREAD

**Issue by mbandrews** [apache/arrow#1946]
Not sure if this issue should go here or to the [pytorch](http://pytorch.org/docs/stable/index.html) page but ever since moving to `pyarrow==0.9.0`, I have trouble reading parquet files with pyarrow when using the standard pytorch [`DataLoader`](http://pytorch.org/docs/stable/data.html) with `num_workers > 0`. I've tried `pyarrow==0.7.1, 0.8.0, 0.9.0` with `pytorch==0.2.0_3, 0.4.0` and see the issue with `pyarrow==0.8.0, 0.9.0` which leads me to think this might be more of a `pyarrow` issue. In any case, below is some minimal code that produces the crash with dummy data (generated by [make_dummy_parquet.txt](https://github.com/apache/arrow/files/1948035/make_dummy_parquet.txt)):

```
import numpy as np
import pyarrow.parquet as pq
import torch
from torch.utils.data import Dataset, DataLoader

class ParquetDataset(Dataset):
    def __init__(self, filename):
        self.parquet = pq.ParquetFile(filename)
    def __getitem__(self, index):
        data = self.parquet.read_row_group(index).to_pydict()
        return {'X': np.float32(data['X'])[0], 'y': np.float32(data['y'])[0]}
    def __len__(self):
        return self.parquet.num_row_groups

batch_, workers_ = 2, 12
dset_train = ParquetDataset("test.snappy.parquet")
train_loader = DataLoader(dataset=dset_train, batch_size=batch_, shuffle=True, num_workers=workers_)

for i, data in enumerate(train_loader):
    print('batch:',i)

print('batch_size:',batch_, 'len(train_loader):', len(train_loader), 'num_workers:',workers_)
```

The output I get is not consistent. Sometimes it runs normally, but most times it crashes.

When it runs normally:
```
$ python tester2.py
batch: 0
batch: 1
batch: 2
batch: 3
batch: 4
batch: 5
batch: 6
batch: 7
batch: 8
batch: 9
batch: 10
batch: 11
batch: 12
batch: 13
batch: 14
batch: 15
batch_size: 2 len(train_loader): 16 num_workers: 12
```
When it doesn't:
```
$ python tester2.py
batch: 0
batch: 1
batch: 2
batch: 3
batch: 4
batch: 5
batch: 6
batch: 7
batch: 8
batch: 9
batch: 10
batch: 11
Traceback (most recent call last):
  File "tester2.py", line 23, in <module>
    for i, data in enumerate(train_loader):
  File "/zfsauton/home/ABC/work/pytorch_cu91/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 267, in __next__
    return self._process_next_batch(batch)
  File "/zfsauton/home/ABC/work/pytorch_cu91/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
pyarrow.lib.ArrowIOError: Traceback (most recent call last):
  File "/zfsauton/home/ABC/work/pytorch_cu91/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/zfsauton/home/ABC/work/pytorch_cu91/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "tester2.py", line 12, in __getitem__
    data = self.parquet.read_row_group(index).to_pydict()
  File "/zfsauton/home/ABC/work/pytorch_cu91/lib/python3.6/site-packages/pyarrow/parquet.py", line 123, in read_row_group
    nthreads=nthreads)
  File "_parquet.pyx", line 712, in pyarrow._parquet.ParquetReader.read_row_group
  File "error.pxi", line 79, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: Couldn't deserialize thrift: TProtocolException: Invalid data
Deserializing page header failed.
```
```
$ python tester2.py
batch: 0
batch: 1
batch: 2
Traceback (most recent call last):
  File "tester2.py", line 23, in <module>
    for i, data in enumerate(train_loader):
  File "/zfsauton/home/ABC/work/pytorch_cu91/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 267, in __next__
    return self._process_next_batch(batch)
  File "/zfsauton/home/ABC/work/pytorch_cu91/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
pyarrow.lib.ArrowIOError: Traceback (most recent call last):
  File "/zfsauton/home/ABC/work/pytorch_cu91/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/zfsauton/home/ABC/work/pytorch_cu91/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "tester2.py", line 12, in __getitem__
    data = self.parquet.read_row_group(index).to_pydict()
  File "/zfsauton/home/ABC/work/pytorch_cu91/lib/python3.6/site-packages/pyarrow/parquet.py", line 123, in read_row_group
    nthreads=nthreads)
  File "_parquet.pyx", line 712, in pyarrow._parquet.ParquetReader.read_row_group
  File "error.pxi", line 79, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: Couldn't deserialize thrift: TProtocolException: Invalid data
Deserializing page header failed.


Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f1e76436940>>
Traceback (most recent call last):
  File "/zfsauton/home/ABC/work/pytorch_cu91/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 333, in __del__
    self._shutdown_workers()
  File "/zfsauton/home/ABC/work/pytorch_cu91/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 319, in _shutdown_workers
    self.data_queue.get()
  File "/zfsauton/home/ABC/usr/local/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/zfsauton/home/ABC/work/pytorch_cu91/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd
    fd = df.detach()
  File "/zfsauton/home/ABC/usr/local/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/zfsauton/home/ABC/usr/local/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/zfsauton/home/ABC/usr/local/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/zfsauton/home/ABC/usr/local/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
```
At the moment, the workaround is to use an older version of `pyarrow`.

**Comment by wesm** [comment]
Interesting error. My best guess what is happening is that when multiprocessing is forking the process, some memory maps trampling each other -- @pitrou does that seem like something that could happen if forks are all memory-mapping the same file? 

I opened https://issues.apache.org/jira/browse/ARROW-2627 about making it easier to toggle this behavior on and off. You could test the hypothesis by changing `pq.ParquetFile(filename)` to `pq.ParquetFile(pa.OSFile(filename))`. Please let us know if this resolves the issue

Could you please open a JIRA with this bug report so that we can track the problem (and any fix) there? Thank you

**Comment by pitrou** [comment]
I don't think multiprocessing would disturb memory maps. What does PyTorch do with multiprocessing exactly?

**Comment by mbandrews** [comment]
Changing `pq.ParquetFile(filename)` to `pq.ParquetFile(pa.OSFile(filename))` doesn't seem to help. In fact, making this change even in the older `pyarrow==0.7.1` version where `pq.ParquetFile(filename)` still worked, now crashes too:

```
$ python tester2.py
batch: 0
Traceback (most recent call last):
  File "tester2.py", line 21, in <module>
    for i, data in enumerate(train_loader):
  File "/zfsauton/home/mbandrews/.conda/envs/conda_pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 272, in __next__
    return self._process_next_batch(batch)
  File "/zfsauton/home/mbandrews/.conda/envs/conda_pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
pyarrow.lib.ArrowIOError: Traceback (most recent call last):
  File "/zfsauton/home/mbandrews/.conda/envs/conda_pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/zfsauton/home/mbandrews/.conda/envs/conda_pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "tester2.py", line 12, in __getitem__
    data = self.parquet.read_row_group(index).to_pydict()
  File "/zfsauton/home/mbandrews/.conda/envs/conda_pytorch/lib/python3.6/site-packages/pyarrow/parquet.py", line 94, in read_row_group
    nthreads=nthreads)
  File "_parquet.pyx", line 444, in pyarrow._parquet.ParquetReader.read_row_group
  File "error.pxi", line 79, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: Couldn't deserialize thrift: TProtocolException: Invalid data
Deserializing page header failed.


Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f2258f43940>>
Traceback (most recent call last):
  File "/zfsauton/home/ABC/.conda/envs/conda_pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 349, in __del__
    self._shutdown_workers()
  File "/zfsauton/home/ABC/.conda/envs/conda_pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 328, in _shutdown_workers
    self.worker_result_queue.get()
  File "/zfsauton/home/ABC/.conda/envs/conda_pytorch/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/zfsauton/home/ABC/.conda/envs/conda_pytorch/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd
    fd = df.detach()
  File "/zfsauton/home/ABC/.conda/envs/conda_pytorch/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/zfsauton/home/ABC/.conda/envs/conda_pytorch/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/zfsauton/home/ABC/.conda/envs/conda_pytorch/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/zfsauton/home/ABC/.conda/envs/conda_pytorch/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
```
From the relevant Pytorch [documentation](https://github.com/pytorch/pytorch/blob/master/docs/source/notes/multiprocessing.rst):

> :mod:`torch.multiprocessing` is a drop in replacement for Python's :mod:`python:multiprocessing` module. It supports the exact same operations, but extends it, so that all tensors sent through a :class:`python:multiprocessing.Queue`, will have their data moved into shared memory and will only send a handle to another process.

The DataLoader itself is used to group/collate samples from the input file into batches. In multiprocessing, several [workers](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L75) are set up to do this in a [queue](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L253).

I've opened the JIRA ticket: https://issues.apache.org/jira/browse/ARROW-2710

**Comment by wesm** [comment]
Closing in favor of tracking the issue on JIRA
