### ISSUE TITLE
[Dev][Release] Submitting the PR for verifying the release fails to be created automatically

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#20345]
As discussed [on Zulip](https://ursalabs.zulipchat.com/#narrow/stream/180245-dev/topic/Relese.20verification.20pull.20request/near/291044659) a PR should be created automatically when executing the 02-source.sh script on the Release but it seems there was some issues when creating it:
```java

Traceback (most recent call last):
  File "/Users/kszucs/.conda/envs/arrow39/bin/archery", line 33, in <module>
    sys.exit(load_entry_point('archery', 'console_scripts', 'archery')())
  File "/Users/kszucs/.conda/envs/arrow39/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kszucs/.conda/envs/arrow39/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/kszucs/.conda/envs/arrow39/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kszucs/.conda/envs/arrow39/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kszucs/.conda/envs/arrow39/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kszucs/.conda/envs/arrow39/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kszucs/.conda/envs/arrow39/lib/python3.10/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/kszucs/Workspace/arrow/dev/archery/archery/crossbow/cli.py", line 196, in verify_release_candidate
    response = arrow.github_pr(title=pr_title, head=head_branch,
  File "/Users/kszucs/Workspace/arrow/dev/archery/archery/crossbow/core.py", line 550, in github_pr
    return repo.create_pull(title=title, base=base, head=head,
  File "/Users/kszucs/.conda/envs/arrow39/lib/python3.10/site-packages/github3/decorators.py", line 24, in auth_wrapper
    return func(self, *args, **kwargs)
  File "/Users/kszucs/.conda/envs/arrow39/lib/python3.10/site-packages/github3/repos/repo.py", line 1175, in create_pull
    return self._create_pull(data)
  File "/Users/kszucs/.conda/envs/arrow39/lib/python3.10/site-packages/github3/repos/repo.py", line 117, in _create_pull
    json = self._json(self._post(url, data=data), 201)
  File "/Users/kszucs/.conda/envs/arrow39/lib/python3.10/site-packages/github3/models.py", line 161, in _json
    raise exceptions.error_for(response)
github3.exceptions.UnprocessableEntity: 422 Validation Failed 
```
Once the PR is created the 03-binary-submit.sh script should add a comment to that PR to track the binary submission jobs but the job is missing the base branch to search the PR from. It should contain a new argument:
```java

--base-branch=${maint_branch} \ 
```

**Reporter**: [Raúl Cumplido](https://issues.apache.org/jira/browse/ARROW-17235) / @raulcd
**Assignee**: [Raúl Cumplido](https://issues.apache.org/jira/browse/ARROW-17235) / @raulcd

<sub>**Note**: *This issue was originally created as [ARROW-17235](https://issues.apache.org/jira/browse/ARROW-17235). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by raulcd** [comment]
This has been working for the past releases. We did some minor fixes so I am pretty sure this can be closed.
