### ISSUE TITLE
ImportError: cannot import name _orc

### ISSUE THREAD

**Issue by ishare** [apache/arrow#2100]
Meeting error import orc, could you give some insights on how to solve it. thanks!

Traceback (most recent call last):
  File "train.py", line 14, in <module>
    from pyarrow import orc
  File "~/virtualenv-2.7/lib/python2.7/site-packages/pyarrow/orc.py", line 21, in <module>
    from pyarrow import _orc
ImportError: cannot import name _orc

**Comment by xhochy** [comment]
How have you installed `pyarrow`?

**Comment by ishare** [comment]
installed via pip

**Comment by wesm** [comment]
@ishare you can obtain this functionality in the meantime by installing with conda

**Comment by leferrad** [comment]
Why was this issue closed? From version 0.15, I still have the same error, so I cannot use newer versions of pyarrow until ORC is available for usage. 
Here the very simple snippet to reproduce error (tested with pyarrow==0.16.0):
```python
from pyarrow import orc 
# Throws:
#     23 from pyarrow import types
#     24 from pyarrow.lib import Schema
# ---> 25 import pyarrow._orc as _orc
#      26 
#      27 
# 
# ModuleNotFoundError: No module named 'pyarrow._orc'
```

**Comment by xhochy** [comment]
The issue is tracked in JIRA, please comment there (obviously the issue is clear, all we need is someone to implement it).

**Comment by wesm** [comment]
If anyone comes across this while searching the internet, the latest JIRA issue about having `pyarrow.orc` in the wheels is https://issues.apache.org/jira/browse/ARROW-7811. We had to disable it a while ago due to a packaging issue and no one has volunteered to fix it yet
