### ISSUE TITLE
[Python] pickle error occurs when using pyarrow._plasma.PlasmaClient with multiprocess on mac (python3.8.5)

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#26629]
- **The environment is：**
  - OS: mac os catalina 10.15.6;
  - <font color="#ff0000">Python version: python3.8.5;</font>
- <font color="#ff0000">\*It's ok, when use python3.7(3.7.2 or 3.7.3) or python3.6(3.6.8).</font>\*
   The error occurs only in python3.8(3.8.5).
- **When I use 'pyarrow._plasma.PlasmaClient' in the 'multiprocessing.context.Process', the error occurs.**
  
- 
  - First, I have a subclass of 'multiprocessing.context.Process', named Executor;
     The defined code like this: 'class Executor(Process):' .
  - And then, I create a 'PlasmaClient' object in the '__init__' function of 'class Executor' .
  - Finally, I new a 'Executor' object, and call the 'start()' function. 
- **The code is:**
  
  ```java
  
  // code placeholder
  from multiprocessing.context import Process
  from time import sleep
  from pyarrow import plasma
  
  
  class Executor(Process):
      def __init__(self):
          super().__init__()
          self._plasma_client = plasma.connect("/tmp/plasma")
  
  
  if __name__ == "__main__":
      executor = Executor()
      executor.start()
      sleep(10)
  ```
- **The detail informations of traceback are as follows:**
  
  ```java
  
  // code placeholder
  Traceback (most recent call last):
    File "/Users/liangbinbin/PycharmProjects/waimai_data_cubeinsight/python/taf/tests/plasma_client_with_multiprocessing_test.py", line 15, in <module>
      executor.start()
    File "/Users/liangbinbin/Applications/anaconda3/envs/python3_8/lib/python3.8/multiprocessing/process.py", line 121, in start
      self._popen = self._Popen(self)
    File "/Users/liangbinbin/Applications/anaconda3/envs/python3_8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
      return _default_context.get_context().Process._Popen(process_obj)
    File "/Users/liangbinbin/Applications/anaconda3/envs/python3_8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
      return Popen(process_obj)
    File "/Users/liangbinbin/Applications/anaconda3/envs/python3_8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
      super().__init__(process_obj)
    File "/Users/liangbinbin/Applications/anaconda3/envs/python3_8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
      self._launch(process_obj)
    File "/Users/liangbinbin/Applications/anaconda3/envs/python3_8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
      reduction.dump(process_obj, fp)
    File "/Users/liangbinbin/Applications/anaconda3/envs/python3_8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
      ForkingPickler(file, protocol).dump(obj)
    File "stringsource", line 2, in pyarrow._plasma.PlasmaClient.__reduce_cython__
  TypeError: no default __reduce__ due to non-trivial __cinit__
  ```
-  And  the error does not occur, when I change 'multiprocessing.context.Process' to '<font color="#de350b">multiprocess.context.Process</font>' which use **dill** to serialize.
  
   

**Environment**: OS: mac os catalina 10.15.6;
Python version: python3.8.5;
**Reporter**: [BinbinLiang](https://issues.apache.org/jira/browse/ARROW-10676)

<sub>**Note**: *This issue was originally created as [ARROW-10676](https://issues.apache.org/jira/browse/ARROW-10676). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Plasma has been deprecated (https://github.com/apache/arrow/issues/33077) in Arrow 10.0 and subsequently removed in Arrow 12.0 (https://github.com/apache/arrow/issues/33243). Given Plasma is no longer an existing component, closing this issue.

For reference, see this mailing list discussion around possible alternatives: https://lists.apache.org/thread/lk277x3b9gjol42sjg27bst2ggm5s0j2
