### ISSUE TITLE
[Archery][C++] Error running "benchmark --diff"

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#26684]
When running:
```Java

archery benchmark diff --suite-filter vector_selection
```

I got the following error:
```Java

Traceback (most recent call last):
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 386, in pandas._libs.hashtable.Float64HashTable.get_item
TypeError: must be real number, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 103, in pandas._libs.index.IndexEngine.get_loc
KeyError: 'change'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/antoine/miniconda3/envs/pyarrow/bin/archery", line 33, in <module>
    sys.exit(load_entry_point('archery', 'console_scripts', 'archery')())
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/antoine/arrow/dev/dev/archery/archery/cli.py", line 575, in benchmark_diff
    formatted = _format_comparisons_with_pandas(comparisons_json)
  File "/home/antoine/arrow/dev/dev/archery/archery/cli.py", line 593, in _format_comparisons_with_pandas
    df['change %'] = df.pop('change').str[:-1].map(float)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/pandas/core/frame.py", line 4371, in pop
    return super().pop(item=item)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/pandas/core/generic.py", line 661, in pop
    result = self[item]
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/pandas/core/indexes/numeric.py", line 424, in get_loc
    return super().get_loc(key, method=method, tolerance=tolerance)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'change'
```

**Reporter**: [Antoine Pitrou](https://issues.apache.org/jira/browse/ARROW-10738) / @pitrou

<sub>**Note**: *This issue was originally created as [ARROW-10738](https://issues.apache.org/jira/browse/ARROW-10738). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by thisisnic** [comment]
This issue has been closed due to having no activity since 2020 or earlier. Feel free to reopen if this has been closed in error.
