### ISSUE TITLE
Error on Connect: FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by behzadba** [apache/arrow#2865]
I'm using python 3.6.6 64bit and just used pip to install pyarrow. But when I'm trying to connect I get this error while it does not look like an credential issue:

```
Traceback (most recent call last):
  File "hdfs.py", line 3, in <module>
    fs = pa.hdfs.connect(host='localhost', port=9000, user='dr.who')
  File "C:\Program Files\Python36\lib\site-packages\pyarrow\hdfs.py", line 183,
in connect
    extra_conf=extra_conf)
  File "C:\Program Files\Python36\lib\site-packages\pyarrow\hdfs.py", line 35, i
n __init__
    _maybe_set_hadoop_classpath()
  File "C:\Program Files\Python36\lib\site-packages\pyarrow\hdfs.py", line 135,
in _maybe_set_hadoop_classpath
    classpath = subprocess.check_output([hadoop_bin, 'classpath', '--glob'])
  File "C:\Program Files\Python36\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Program Files\Python36\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python36\lib\subprocess.py", line 997, in _execute_chil
d
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
I installed Hadoop locally on my windows machine by the way. Any idea?

**Comment by behzadba** [comment]
I changed hdfs.py file this way and it passed that issue:

```
def _maybe_set_hadoop_classpath():
    import subprocess

    if 'hadoop' in os.environ.get('CLASSPATH', ''):
        return

    if 'HADOOP_HOME' in os.environ:
        hadoop_bin = os.path.normpath(os.environ['HADOOP_HOME']) #'{0}/bin/hadoop'.format(os.environ['HADOOP_HOME'])
    else:
        hadoop_bin = 'hadoop'

    os.chdir(hadoop_bin)
    hadoop_bin_exe = os.path.join(hadoop_bin, 'hadoop.cmd')
    classpath = subprocess.check_output([hadoop_bin_exe, 'classpath', '--glob'])
    os.environ['CLASSPATH'] = classpath.decode('utf-8')
```
PS: my HADOOP_HOME env already was the bin folder of hadoop.
