### ISSUE TITLE
Supported file format in C#

### ISSUE THREAD

**Issue by amittleider** [apache/arrow#2869]
Thanks for publishing the beginning of the C# library. I'm looking forward to using it.

I have a question about the file format that is supported. I am trying to read a file into C# that I have created using the python Arrow libraries. I assume that I am doing something wrong.

1. Attempt 1: `pq.write_table(table, "mytable.parquet")`
2. Attempt 2: 
```python
a = table.to_batches()
buffer = a[0].serialize()
from pyarrow import OSFile
with pa.OSFile("mytable.fromstream", "wb") as f:
    f.write(buffer)
```

And on the C# side, reading like this: 

```C#
[Fact]
            public async Task TestReadFile()
            {
                using (var stream = System.IO.File.OpenRead("myFile"))
                {
                    using (var reader = new ArrowFileReader(stream))
                    {
                        var recordBatch = await reader.ReadNextRecordBatchAsync();
                        System.Console.WriteLine("Read record batch with {0} column(s)", recordBatch.ColumnCount);
                    }
                }
            }
```

In both cases, the result is the same exception:

```
Apache.Arrow.Tests.ArrowBufferTests+Allocate.TestReadFile:
    Outcome: Failed
    Error Message:
    System.IO.InvalidDataException : Invalid magic at offset <6>
    Stack Trace:
       at Apache.Arrow.Ipc.ArrowFileReader.<>c__DisplayClass14_0.<<ValidateMagicAsync>b__0>d.MoveNext() in /home/mitt/source/arrow/csharp/src/Apache.Arrow/Ipc/ArrowFileReader.cs:line 197
--- End of stack trace from previous location where exception was thrown ---
   at Apache.Arrow.Ipc.ArrowFileReader.ValidateMagicAsync() in /home/mitt/source/arrow/csharp/src/Apache.Arrow/Ipc/ArrowFileReader.cs:line 179
   at Apache.Arrow.Ipc.ArrowFileReader.ValidateFileAsync() in /home/mitt/source/arrow/csharp/src/Apache.Arrow/Ipc/ArrowFileReader.cs:line 167
   at Apache.Arrow.Ipc.ArrowFileReader.ReadSchemaAsync() in /home/mitt/source/arrow/csharp/src/Apache.Arrow/Ipc/ArrowFileReader.cs:line 83
   at Apache.Arrow.Ipc.ArrowFileReader.ReadNextRecordBatchAsync(CancellationToken cancellationToken) in /home/mitt/source/arrow/csharp/src/Apache.Arrow/Ipc/ArrowFileReader.cs:line 144
   at Apache.Arrow.Tests.ArrowBufferTests.Allocate.TestReadFile() in /home/mitt/source/arrow/csharp/test/Apache.Arrow.Tests/ArrowBufferTests.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
```

It appears that the buffer of the file does not match the `magic` buffer sequence. Here is my sequence:

```
[0] [byte]:172
[1] [byte]:1
[2] [byte]:0
[3] [byte]:0
[4] [byte]:20
[5] [byte]:0
```

I assume my python code is not generating the proper Arrow file.

Thanks

**Comment by xhochy** [comment]
Your code above is writing Parquet file and in the second attempt serialized objects. Both are not the Arrow file format.

You want to take a look at https://arrow.apache.org/docs/python/ipc.html#writing-and-reading-random-access-files

**Comment by amittleider** [comment]
Thanks, @xhochy .

I used the following python code to write the arrow file format to disk.

```python
hdf = pd.HDFStore("Myhdf.h5")
t5 = hdf["/5T/5T"] # This is a pandas dataframe
batches = table.to_batches()
filehandle = open('myfile', 'wb')  
writer = pa.RecordBatchFileWriter(filehandle, batches[0].schema)
writer.write(batches[0])
writer.close()
filehandle.close()
```
