### ISSUE TITLE
[Python] Installing pyarrow via pip on M1 causing issue

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#29457]
On installing pyarrow via pip, I am unable to use to start a FlightClient.
```java

(venv) ➜  trial python -V
Python 3.9.6

(venv) ➜  trial pip install pyarrow
Collecting pyarrow
  Downloading pyarrow-5.0.0-cp39-cp39-macosx_11_0_arm64.whl (12.3 MB)
     |████████████████████████████████| 12.3 MB 581 kB/s 
Collecting numpy>=1.16.6
  Downloading numpy-1.21.2-cp39-cp39-macosx_11_0_arm64.whl (12.4 MB)
     |████████████████████████████████| 12.4 MB 5.1 MB/s 
Installing collected packages: numpy, pyarrow
Successfully installed numpy-1.21.2 pyarrow-5.0.0

(venv) ➜  trial cat script.py 
from pyarrow.flight import FlightClient
(venv) ➜  trial python3 script.py 
Traceback (most recent call last):
  File "/Users/rohan/work/trial/script.py", line 1, in <module>
    from pyarrow.flight import FlightClient
  File "/Users/rohan/work/trial/venv/lib/python3.9/site-packages/pyarrow/flight.py", line 18, in <module>
    from pyarrow._flight import (  # noqa:F401
ModuleNotFoundError: No module named 'pyarrow._flight'
```
However, installing via conda (from conda-forge) works fine
```java

(py-flight) ➜  trial conda install pyarrow
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/rohan/miniforge3/envs/py-flight

  added / updated specs:
    - pyarrow

The following NEW packages will be INSTALLED:

  abseil-cpp         conda-forge/osx-arm64::abseil-cpp-20210324.2-hbdafb3b_0
  arrow-cpp          conda-forge/osx-arm64::arrow-cpp-5.0.0-py39h9b3a587_3_cpu
  aws-c-cal          conda-forge/osx-arm64::aws-c-cal-0.5.11-h4530763_0
  aws-c-common       conda-forge/osx-arm64::aws-c-common-0.6.2-h3422bc3_0
  aws-c-event-stream conda-forge/osx-arm64::aws-c-event-stream-0.2.7-h9972306_13
  aws-c-io           conda-forge/osx-arm64::aws-c-io-0.10.5-hea86ef8_0
  aws-checksums      conda-forge/osx-arm64::aws-checksums-0.1.11-h487e1a8_7
  aws-sdk-cpp        conda-forge/osx-arm64::aws-sdk-cpp-1.8.186-hb86bbe7_3
  bzip2              conda-forge/osx-arm64::bzip2-1.0.8-h3422bc3_4
  c-ares             conda-forge/osx-arm64::c-ares-1.17.2-h3422bc3_0
  ca-certificates    conda-forge/osx-arm64::ca-certificates-2021.5.30-h4653dfc_0
  gflags             conda-forge/osx-arm64::gflags-2.2.2-hc88da5d_1004
  glog               conda-forge/osx-arm64::glog-0.5.0-h5c6a83d_0
  grpc-cpp           conda-forge/osx-arm64::grpc-cpp-1.39.1-hc3f22eb_0
  krb5               conda-forge/osx-arm64::krb5-1.19.2-hd92b7a7_0
  libblas            conda-forge/osx-arm64::libblas-3.9.0-11_osxarm64_openblas
  libbrotlicommon    conda-forge/osx-arm64::libbrotlicommon-1.0.9-h3422bc3_5
  libbrotlidec       conda-forge/osx-arm64::libbrotlidec-1.0.9-h3422bc3_5
  libbrotlienc       conda-forge/osx-arm64::libbrotlienc-1.0.9-h3422bc3_5
  libcblas           conda-forge/osx-arm64::libcblas-3.9.0-11_osxarm64_openblas
  libcurl            conda-forge/osx-arm64::libcurl-7.78.0-h8fe1914_0
  libcxx             conda-forge/osx-arm64::libcxx-12.0.1-h168391b_0
  libedit            conda-forge/osx-arm64::libedit-3.1.20191231-hc8eb9b7_2
  libev              conda-forge/osx-arm64::libev-4.33-h642e427_1
  libevent           conda-forge/osx-arm64::libevent-2.1.10-h93437e4_3
  libgfortran        conda-forge/osx-arm64::libgfortran-5.0.0.dev0-11_0_1_hf114ba7_23
  libgfortran5       conda-forge/osx-arm64::libgfortran5-11.0.1.dev0-hf114ba7_23
  liblapack          conda-forge/osx-arm64::liblapack-3.9.0-11_osxarm64_openblas
  libnghttp2         conda-forge/osx-arm64::libnghttp2-1.43.0-hf3018f0_0
  libopenblas        conda-forge/osx-arm64::libopenblas-0.3.17-openmp_h5dd58f0_1
  libprotobuf        conda-forge/osx-arm64::libprotobuf-3.16.0-hccf11d3_0
  libssh2            conda-forge/osx-arm64::libssh2-1.9.0-hb80f160_6
  libthrift          conda-forge/osx-arm64::libthrift-0.14.2-h28a9c34_1
  libutf8proc        conda-forge/osx-arm64::libutf8proc-2.6.1-h27ca646_0
  llvm-openmp        conda-forge/osx-arm64::llvm-openmp-12.0.1-hf3c4609_1
  lz4-c              conda-forge/osx-arm64::lz4-c-1.9.3-hbdafb3b_1
  ncurses            conda-forge/osx-arm64::ncurses-6.2-h9aa5885_4
  numpy              conda-forge/osx-arm64::numpy-1.21.2-py39h1f3b974_0
  openssl            conda-forge/osx-arm64::openssl-1.1.1k-h3422bc3_1
  orc                conda-forge/osx-arm64::orc-1.6.10-h450e963_0
  parquet-cpp        conda-forge/noarch::parquet-cpp-1.5.1-2
  pip                conda-forge/noarch::pip-21.2.4-pyhd8ed1ab_0
  pyarrow            conda-forge/osx-arm64::pyarrow-5.0.0-py39h6134bab_3_cpu
  python             conda-forge/osx-arm64::python-3.9.6-h54d631c_1_cpython
  python_abi         conda-forge/osx-arm64::python_abi-3.9-2_cp39
  re2                conda-forge/osx-arm64::re2-2021.08.01-hbdafb3b_0
  readline           conda-forge/osx-arm64::readline-8.1-hedafd6a_0
  setuptools         conda-forge/osx-arm64::setuptools-57.4.0-py39h2804cbe_0
  snappy             conda-forge/osx-arm64::snappy-1.1.8-hc88da5d_3
  sqlite             conda-forge/osx-arm64::sqlite-3.36.0-h72a2b83_0
  tk                 conda-forge/osx-arm64::tk-8.6.11-he1e0b03_0
  tzdata             conda-forge/noarch::tzdata-2021a-he74cb21_1
  wheel              conda-forge/noarch::wheel-0.37.0-pyhd8ed1ab_1
  xz                 conda-forge/osx-arm64::xz-5.2.5-h642e427_1
  zlib               conda-forge/osx-arm64::zlib-1.2.11-h31e879b_1009
  zstd               conda-forge/osx-arm64::zstd-1.5.0-h861e0a7_0

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(py-flight) ➜  trial cat script.py 
from pyarrow.flight import FlightClient
(py-flight) ➜  trial python3 script.py

```
OS Version:
```java

(py-flight) ➜  trial sw_vers
ProductName:	macOS
ProductVersion:	11.5.2
BuildVersion:	20G95
```

**Reporter**: [Rohan Mishra](https://issues.apache.org/jira/browse/ARROW-13833)
#### Related issues:
- [[Python] No module named 'pyarrow._flight' (MacOS)](https://github.com/apache/arrow/issues/29294) (duplicates)

<sub>**Note**: *This issue was originally created as [ARROW-13833](https://issues.apache.org/jira/browse/ARROW-13833). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Duplicate of https://github.com/apache/arrow/issues/29294

At the time the MacOS wheels did not yet include flight (solved by https://github.com/apache/arrow/issues/32112)
