### ISSUE TITLE
[Java] SplitAndTransfer throws for (0,0) if vector empty

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30866]
I've hit a bug where `splitAndTransfer` on vectors throws if the vector is completely empty and the offset buffer is empty.

An easy repro is:
```

        BufferAllocator allocator = new RootAllocator(Long.MAX_VALUE);
        ListVector listVector = ListVector.empty("listVector", allocator);
        listVector.getTransferPair(listVector.getAllocator()).splitAndTransfer(0, 0);
```

This results in the following stacktrace:
```

java.lang.IndexOutOfBoundsException: index: 0, length: 4 (expected: range(0, 0))
	at io.netty.buffer.ArrowBuf.checkIndexD(ArrowBuf.java:335)
	at io.netty.buffer.ArrowBuf.chk(ArrowBuf.java:322)
	at io.netty.buffer.ArrowBuf.getInt(ArrowBuf.java:441)
	at org.apache.arrow.vector.complex.ListVector$TransferImpl.splitAndTransfer(ListVector.java:484)
```

In production we hit this when calling `VectorSchemaRoot.slice`. The schema root contains a `ListVector` with a `VarCharVector` value vector. The list vector isn't empty, but all the strings in the var char vector are. `splitAndTransfer` on the list vector works, but then when underlying var char vector is split we get the same exception:

```

java.lang.IndexOutOfBoundsException: index: 0, length: 4 (expected: range(0, 0))
	at io.netty.buffer.ArrowBuf.checkIndexD(ArrowBuf.java:335)
	at io.netty.buffer.ArrowBuf.chk(ArrowBuf.java:322)
	at io.netty.buffer.ArrowBuf.getInt(ArrowBuf.java:441)
	at org.apache.arrow.vector.BaseVariableWidthVector.splitAndTransferOffsetBuffer(BaseVariableWidthVector.java:728)
	at org.apache.arrow.vector.BaseVariableWidthVector.splitAndTransferTo(BaseVariableWidthVector.java:712)
	at org.apache.arrow.vector.VarCharVector$TransferImpl.splitAndTransfer(VarCharVector.java:321)
	at org.apache.arrow.vector.complex.ListVector$TransferImpl.splitAndTransfer(ListVector.java:496)
	at org.apache.arrow.vector.VectorSchemaRoot.lambda$slice$1(VectorSchemaRoot.java:308)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.apache.arrow.vector.VectorSchemaRoot.slice(VectorSchemaRoot.java:310)
``` 

**Reporter**: [David Vogelbacher](https://issues.apache.org/jira/browse/ARROW-15382)
#### PRs and other links:
- [GitHub Pull Request #12250](https://github.com/apache/arrow/pull/12250)

<sub>**Note**: *This issue was originally created as [ARROW-15382](https://issues.apache.org/jira/browse/ARROW-15382). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by lidavidm** [comment]
Issue resolved by pull request 41066
https://github.com/apache/arrow/pull/41066
