### ISSUE TITLE
python plasma store ArrowCapacityError

### ISSUE THREAD

**Issue by fayeshine** [apache/arrow#3292]
```
Traceback (most recent call last):

  File "<ipython-input-5-6ad29a9635f6>", line 1, in <module>
    object_id = client.put(data)

  File "pyarrow/_plasma.pyx", line 435, in pyarrow._plasma.PlasmaClient.put

  File "pyarrow/serialization.pxi", line 337, in pyarrow.lib.serialize

  File "pyarrow/error.pxi", line 93, in pyarrow.lib.check_status

ArrowCapacityError: BinaryArray cannot contain more than 2147483646 bytes, have 2398461754
```

**Comment by wesm** [comment]
Can you provide a reproducible example?
