### ISSUE TITLE
Support Python enums in pyarrow

### ISSUE THREAD

**Issue by little-arhat** [apache/arrow#33729]
### Describe the bug, including details regarding any error messages, version, and platform.

Hello! 

Filing this as a bug, though it could be feature request or even usage question.

Code:
```
import pyarrow
from enum import Enum
import pandas as pd

class Unit(Enum):
    A = "A"
    B = "B"

df = pd.DataFrame({'x': [Unit.A, Unit.B]})

print(pyarrow.Table.from_pandas(df))
```

Expected:

smth like
```
pyarrow.Table
x: dictionary<values=string, indices=int8, ordered=0>
----
x: [  -- dictionary:
["A","B"]  -- indices:
[0,1]]
```

Got:

```
Traceback (most recent call last):
  File "x.py", line 12, in <module>
    print(pyarrow.Table.from_pandas(df))
  File "pyarrow/table.pxi", line 3475, in pyarrow.lib.Table.from_pandas
  File "/Users/a/venv/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 611, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/Users/avenv/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 611, in <listcomp>
    arrays = [convert_column(c, f)
  File "/Users/a/venv/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 598, in convert_column
    raise e
  File "/Users/a/venv/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 592, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 316, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: ("Could not convert <Unit.A: 'A'> with type Unit: did not recognize Python value type when inferring an Arrow data type", 'Conversion failed for column x with type object')
```

Extracting `.name` from enum values and converting to `category` works as expected. 

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
In general we don't support converting "random" python objects that don't have a direct mapping to one of the arrow types (so some exceptions from the stdlib are Decimals and datetime objects). 

If you want to convert such an array or pandas column to arrow, you can do the conversion yourself in advance (i.e. in your case extracting the name from each value, and converting to a Categorical).

**Comment by khughitt** [comment]
Would it make sense to support the specialized int/str variants of Enum?

- [enum.IntEnum](https://docs.python.org/3/library/enum.html#enum.IntEnum)
- [enum.StrEnum](https://docs.python.org/3/library/enum.html#enum.StrEnum)
- [enum.IntFlag](https://docs.python.org/3/library/enum.html#enum.IntFlag)?
