### ISSUE TITLE
BUG: mode() throws an error for a series with string[pyarrow] dtype

### ISSUE THREAD

**Issue by ParthivNaresh** [apache/arrow#34070]
### Describe the bug, including details regarding any error messages, version, and platform.

```python
import pandas as pd

series = pd.Series(["red", "yellow", "red", "green", pd.NA], dtype="string[pyarrow]")
series.mode()
=======================================
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../pandas/core/series.py", line 2072, in mode
    res_values = values._mode(dropna=dropna)
  File ".../pandas/core/arrays/arrow/array.py", line 1311, in _mode
    modes = pc.mode(data, pc.count_distinct(data).as_py())
  File ".../pyarrow/compute.py", line 255, in wrapper
    return func.call(args, options, memory_pool)
  File "pyarrow/_compute.pyx", line 355, in pyarrow._compute.Function.call
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 121, in pyarrow.lib.check_status
pyarrow.lib.ArrowNotImplementedError: Function 'mode' has no kernel matching input types (string)
```
Using the `string[pyarrow]` dtype prevents the usage of `mode()`.

pandas : 2.0.0.dev0+1430.gb2a26ecc5
numpy : 1.23.4
pyarrow : 9.0.0

### Component(s)

Python

**Comment by thisisnic** [comment]
This issue has been marked as stale because it has had no activity in the past 2 years. Please remove the stale label or comment below, or this issue will be closed in 14 days.
