### ISSUE TITLE
Allow converting strings to dates without using datetimes as an intermediate step

### ISSUE THREAD

**Issue by Kodiologist** [apache/arrow#34121]
### Describe the enhancement requested

```
import pyarrow as pa, pyarrow.compute as C
x = pyarrow.array(['2008-01-01', '2008-01-02', '2008-01-03'])
```

This works fine:

```
>>> C.strptime(x, format = '%Y-%m-%d', unit = 's').cast('date32[day]')
<pyarrow.lib.Date32Array object at 0x7fce3227c880>
[
  2008-01-01,
  2008-01-02,
  2008-01-03
]
```

But this isn't allowed:

```
>>> C.strptime(x, format = '%Y-%m-%d', unit = 'day')
Traceback (most recent call last):
  File "pyarrow/_compute.pyx", line 1515, in pyarrow._compute._StrptimeOptions._set_options
KeyError: 'day'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/arferk01/.local/lib/python3.10/site-packages/pyarrow/compute.py", line 251, in wrapper
    options = _handle_options(func_name, options_class, options,
  File "/home/arferk01/.local/lib/python3.10/site-packages/pyarrow/compute.py", line 214, in _handle_options
    return options_class(*args, **kwargs)
  File "pyarrow/_compute.pyx", line 1538, in pyarrow._compute.StrptimeOptions.__init__
  File "pyarrow/_compute.pyx", line 1519, in pyarrow._compute._StrptimeOptions._set_options
  File "pyarrow/_compute.pyx", line 619, in pyarrow._compute._raise_invalid_function_option
ValueError: "day" is not a valid time unit
```

It seems wasteful to have to compute a full seconds-level POSIX timestamp when the only thing you have and that you want is the date.

Related: #31254.

### Component(s)

Python

**Comment by rok** [comment]
@Kodiologist This also suggested in #33357 and it seems like a reasonable improvement, but would require some C++ work. PRs are most welcome :).

**Comment by Kodiologist** [comment]
I saw that issue but got the impression it had to do with code specific to reading CSVs rather than the more generic features for conversion between data types.

**Comment by rok** [comment]
I believe we currently use one generic parser object for both code paths, but CSV parser might have some additional requirements so I'd keep both open.

**Comment by thisisnic** [comment]
This issue has been marked as stale because it has had no activity in the past 2 years. Please remove the stale label or comment below, or this issue will be closed in 14 days.
