### ISSUE TITLE
[CI][GLib] AMD64 Windows MinGW 64 GLib & Ruby is failing

### ISSUE THREAD

**Issue by wgtmac** [apache/arrow#34328]
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/apache/arrow/actions/runs/4261050340/jobs/7414917058

```
Omission: parquet::RowGroupMetaData::Equals() isn't stable. [test: #==(TestParquetRowGroupMetadata)]
/Users/runner/work/arrow/arrow/c_glib/test/parquet/test-row-group-metadata.rb:48:in `block in <class:TestParquetRowGroupMetadata>'
===============================================================================
.........F
===============================================================================
Failure: test: #has_n_distinct_values?(TestParquetStatistics):
        @statistics.has_n_distinct_values?
        |           |
        |           false
        #<Parquet::Int32Statistics:0x7f8c66dca268 ptr=0x7f8c67d48700>
/Users/runner/work/arrow/arrow/c_glib/test/parquet/test-statistics.rb:53:in `block in <class:TestParquetStatistics>'
     50:   end
     51: 
     52:   test("#has_n_distinct_values?") do
  => 53:     assert do
     54:       @statistics.has_n_distinct_values?
     55:     end
     56:   end

```

### Component(s)

GLib, Ruby

**Comment by wgtmac** [comment]
@kou

**Comment by kou** [comment]
It seems that this failure isn't happen on main: https://github.com/apache/arrow/actions/workflows/ruby.yml?query=branch%3Amain

This may be related to #34054.
