### ISSUE TITLE
Arrow version 5 or later fails to compile/link with gcc version 7 (or earlier)

### ISSUE THREAD

**Issue by abcbarryn** [apache/arrow#34341]
### Describe the bug, including details regarding any error messages, version, and platform.

When linking the shared library with gcc 7 I get several errors like this:

``_ZN5arrow6ResultISt10unique_ptrINS_7compute11KernelStateESt14default_deleteIS3_EEEC2ERKNS_6StatusE.part.688' referenced in section `.text' of CMakeFiles/arrow_objlib.dir/compute/kernels/scalar_string_ascii.cc.o: defined in discarded section `.text._ZN5arrow6ResultISt10unique_ptrINS_7compute11KernelStateESt14default_deleteIS3_EEEC2ERKNS_6StatusE.part.688[_ZN5arrow6ResultISt10unique_ptrINS_7compute11KernelStateESt14default_deleteIS3_EEEC5ERKNS_6StatusE]' of CMakeFiles/arrow_objlib.dir/compute/kernels/scalar_string_ascii.cc.o`

### Component(s)

C++

**Comment by abcbarryn** [comment]
It works using gcc11, but not gcc7.

**Comment by abcbarryn** [comment]
Below is the original error with the original source before I started trying to fix it. I checked with the latest version of the source and it is still occurring. in gcc c++ version 7, std::char_traits<char>::length(const char_type*) does not return a contstexpr.

```
In file included from /usr/include/c++/7/bits/basic_string.h:48:0,
                 from /usr/include/c++/7/string:52,
                 from /usr/include/c++/7/bits/locale_classes.h:40,
                 from /usr/include/c++/7/bits/ios_base.h:41,
                 from /usr/include/c++/7/ios:42,
                 from /usr/src/arrow-apache-arrow-12.0.0/cpp/src/arrow/vendored/datetime/date.h:53,
                 from /usr/src/arrow-apache-arrow-12.0.0/cpp/src/arrow/vendored/datetime/tz.h:105,
                 from /usr/src/arrow-apache-arrow-12.0.0/cpp/src/arrow/vendored/datetime/tz_private.h:31,
                 from /usr/src/arrow-apache-arrow-12.0.0/cpp/src/arrow/vendored/datetime/tz.cpp:90:
/usr/include/c++/7/string_view: In function ‘std::string_view arrow_vendored::date::extract_tz_name(const char*)’:
/usr/src/arrow-apache-arrow-12.0.0/cpp/src/arrow/vendored/datetime/tz.cpp:3768:38:   in constexpr expansion of ‘std::basic_string_view<char>(((const char*)"zoneinfo"))’
/usr/include/c++/7/string_view:100:58: error: call to non-constexpr function ‘static std::size_t std::char_traits<char>::length(const char_type*)’
       : _M_len{__str == nullptr ? 0 : traits_type::length(__str)},
                                       ~~~~~~~~~~~~~~~~~~~^~~~~~~
make[2]: *** [src/arrow/CMakeFiles/arrow_objlib.dir/vendored/datetime/tz.cpp.o] Error 1
make[1]: *** [src/arrow/CMakeFiles/arrow_objlib.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by abcbarryn** [comment]
Arrow version 5 is the latest one I found that will compile with gcc version 7.

**Comment by abcbarryn** [comment]
This is probably related: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80265

**Comment by abcbarryn** [comment]
On the one hand, you could update the build requirements to reflect reality.
On the other hand, this would definitely make it harder to build arrow, and would make it more difficult to build pyarrow as a portable wheel.
On the gripping hand, I was able to fix many (but not all) of these errors by forcing HAS_STRING_VIEW to 0, but that doesn't help arrow-apache-arrow-12.0.0/cpp/src/arrow/compute/exec/expression.cc and a few other files. I need a little help there.

**Comment by westonpace** [comment]
To start with we can probably remove "(or earlier)".  This is by design and is stated in [our docs](https://arrow.apache.org/docs/developers/cpp/building.html):

> A C++17-enabled compiler. On Linux, gcc 7.1 and higher should be sufficient. For Windows, at least Visual Studio VS2017 is required.

Can you provide more details on exactly which version of `gcc` you are trying to work with?

**Comment by abcbarryn** [comment]
I tried GCC 7.1.1+r248970-1.4

**Comment by abcbarryn** [comment]
So I updated now to gcc 11.2.1, and now pyarrow 11 (and 5) will build, but with 11 I get an error at runtime, version 5 works correctly though.

# python
Python 3.9.16 (main, Dec 06 2022, 18:42:13) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.9/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
ImportError: /usr/local/lib64/python3.9/site-packages/pyarrow/libarrow_python.so: undefined symbol: _ZN5arrow2io13FileInterface10CloseAsyncEv
>>> quit()

**Comment by westonpace** [comment]
Normally that error would indicate that you built `libarrow_python.so` targeting one version of the arrow headers (e.g. 5) and are linking with libarrow.so of a different version.
