### ISSUE TITLE
[CI][C++] Nightly tests `test-build-cpp-fuzz` fails with `Duplicate hash`

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#34643]
### Describe the bug, including details regarding any error messages, version, and platform.

For the last ~5 days the nightly tests for [test-build-cpp-fuzz](https://github.com/ursacomputing/crossbow/actions/runs/4463511847/jobs/7838805718) have been failing with:
```
 + cp --backup=numbered /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-bigendian/generated_nested_large_offsets.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-bigendian/generated_extension.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-bigendian/generated_primitive_no_batches.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-bigendian/generated_recursive_nested.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-bigendian/generated_dictionary_unsigned.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-bigendian/generated_nested.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-bigendian/generated_union.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-bigendian/generated_duplicate_fieldnames.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-bigendian/generated_dictionary.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-bigendian/generated_null.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-bigendian/generated_decimal.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-bigendian/generated_interval.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-bigendian/generated_primitive.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-bigendian/generated_datetime.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-bigendian/generated_null_trivial.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-bigendian/generated_primitive_zerolength.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-bigendian/generated_decimal256.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-bigendian/generated_map.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-bigendian/generated_primitive_large_offsets.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-bigendian/generated_custom_metadata.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-bigendian/generated_nested_dictionary.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-bigendian/generated_map_non_canonical.stream /src/arrow/testing/data/arrow-ipc-stream/integration/0.17.1/generated_union.stream /src/arrow/testing/data/arrow-ipc-stream/integration/2.0.0-compression/generated_uncompressible_zstd.stream /src/arrow/testing/data/arrow-ipc-stream/integration/2.0.0-compression/generated_zstd.stream /src/arrow/testing/data/arrow-ipc-stream/integration/2.0.0-compression/generated_lz4.stream /src/arrow/testing/data/arrow-ipc-stream/integration/2.0.0-compression/generated_uncompressible_lz4.stream /src/arrow/testing/data/arrow-ipc-stream/integration/0.14.1/generated_primitive_no_batches.stream /src/arrow/testing/data/arrow-ipc-stream/integration/0.14.1/generated_nested.stream /src/arrow/testing/data/arrow-ipc-stream/integration/0.14.1/generated_dictionary.stream /src/arrow/testing/data/arrow-ipc-stream/integration/0.14.1/generated_decimal.stream /src/arrow/testing/data/arrow-ipc-stream/integration/0.14.1/generated_interval.stream /src/arrow/testing/data/arrow-ipc-stream/integration/0.14.1/generated_primitive.stream /src/arrow/testing/data/arrow-ipc-stream/integration/0.14.1/generated_datetime.stream /src/arrow/testing/data/arrow-ipc-stream/integration/0.14.1/generated_primitive_zerolength.stream /src/arrow/testing/data/arrow-ipc-stream/integration/0.14.1/generated_map.stream /src/arrow/testing/data/arrow-ipc-stream/integration/4.0.0-shareddict/generated_shared_dict.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_nested_large_offsets.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_extension.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_primitive_no_batches.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_recursive_nested.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_dictionary_unsigned.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_nested.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_union.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_duplicate_fieldnames.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_dictionary.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_null.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_decimal.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_interval.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_primitive.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_datetime.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_null_trivial.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_primitive_zerolength.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_decimal256.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_map.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_primitive_large_offsets.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_custom_metadata.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_nested_dictionary.stream /src/arrow/testing/data/arrow-ipc-stream/integration/1.0.0-littleendian/generated_map_non_canonical.stream /tmp/corpus
+ /src/arrow/cpp/build-support/fuzzing/pack_corpus.py /tmp/corpus /out/arrow-ipc-stream-fuzz_seed_corpus.zip
Traceback (most recent call last):
  File "/src/arrow/cpp/build-support/fuzzing/pack_corpus.py", line 54, in <module>
    main(sys.argv[1], sys.argv[2])
  File "/src/arrow/cpp/build-support/fuzzing/pack_corpus.py", line 47, in main
    process_dir(Path(corpus_dir), zip_output)
  File "/src/arrow/cpp/build-support/fuzzing/pack_corpus.py", line 39, in process_dir
    raise ValueError("Duplicate hash: {0} (in file {1})"
ValueError: Duplicate hash: 19530341bcb2ce81c942121d5719bf1ed35c2b8c (in file /tmp/corpus/generated_uncompressible_lz4.stream)
ERROR:root:Building fuzzers failed.
Error: Process completed with exit code 1.
```
Between the last success and the first failure those are the commits that were merged:
https://github.com/apache/arrow/compare/fe88d9ad5c346786842913c8d2a369db099b5406...69132a177b0a0e8b7f6a8dac48e7e66fc521013b

### Component(s)

C++, Continuous Integration

**Comment by lidavidm** [comment]
I do see 
```
a88891b8934f9123e854d0f0369e49385175460c16a6bfb8b7fcb333d318d372  generated_uncompressible_lz4.stream
a88891b8934f9123e854d0f0369e49385175460c16a6bfb8b7fcb333d318d372  generated_uncompressible_zstd.stream
```

possibly I oops'd when generating the files and didn't notice. I'll have to figure out how to poke the files by hand to confirm

**Comment by lidavidm** [comment]
https://github.com/apache/arrow-testing/pull/88

I poked at it with a Java debugger and the LZ4 files were both ZSTD encoded (oops). I rewrote the files with LZ4, also tested that (at least in Java) the code path for an uncompressed buffer is actually hit.
