### ISSUE TITLE
[Ruby] gem install red-arrow fails on MacOS / Ruby 3.2.1

### ISSUE THREAD

**Issue by collimarco** [apache/arrow#34801]
### Describe the bug, including details regarding any error messages, version, and platform.

I have run:

```
brew install apache-arrow
brew install apache-arrow-glib
gem install red-arrow
```

However the gem installation fails (I am using MacOS / Ruby 3.2.1).

```
$ gem install red-arrow
Building native extensions. This could take a while...
Successfully installed gobject-introspection-4.1.2
Building native extensions. This could take a while...
Successfully installed gio2-4.1.2
Successfully installed extpp-0.1.1
Building native extensions. This could take a while...
ERROR:  Error installing red-arrow:
	ERROR: Failed to build gem native extension.

    current directory: /Users/collimarco/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/red-arrow-11.0.0/ext/arrow
/Users/collimarco/.rbenv/versions/3.2.1/bin/ruby -I /Users/collimarco/.rbenv/versions/3.2.1/lib/ruby/3.2.0 extconf.rb
checking --enable-debug-build option... no
checking C++ compiler... clang++
checking g++ version... 14 (gnu++17)
checking for --enable-debug-build option... no
checking for -Wall option to compiler... yes
checking for -Wcast-align option to compiler... yes
checking for -Wextra option to compiler... no
checking for -Wformat=2 option to compiler... yes
checking for -Winit-self option to compiler... yes
checking for -Wlarger-than-65500 option to compiler... yes
checking for -Wmissing-declarations option to compiler... yes
checking for -Wmissing-format-attribute option to compiler... yes
checking for -Wmissing-include-dirs option to compiler... yes
checking for -Wmissing-noreturn option to compiler... yes
checking for -Wmissing-prototypes option to compiler... yes
checking for -Wnested-externs option to compiler... yes
checking for -Wold-style-definition option to compiler... yes
checking for -Wpacked option to compiler... yes
checking for -Wp,-D_FORTIFY_SOURCE=2 option to compiler... yes
checking for -Wpointer-arith option to compiler... yes
checking for -Wundef option to compiler... yes
checking for -Wout-of-line-declaration option to compiler... yes
checking for -Wunsafe-loop-optimizations option to compiler... no
checking for -Wwrite-strings option to compiler... yes
checking for Homebrew... yes
checking for Homebrew... yes
checking for arrow version (>= 11.0.0)... yes (11.0.0)
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/collimarco/.rbenv/versions/3.2.1/bin/$(RUBY_BASE_NAME)
	--enable-debug-build
	--disable-debug-build
	--enable-debug-build
	--disable-debug-build
	--with-pkg-config
	--without-pkg-config
	--with-override-variables
	--without-override-variables
/Users/collimarco/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/pkg-config-1.5.1/lib/pkg-config.rb:500:in `parse_pc': .pc doesn't exist: <openssl> (PackageConfig::NotFoundError)
	from /Users/collimarco/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/pkg-config-1.5.1/lib/pkg-config.rb:344:in `declaration'
	from /Users/collimarco/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/pkg-config-1.5.1/lib/pkg-config.rb:289:in `requires_private'
	from /Users/collimarco/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/pkg-config-1.5.1/lib/pkg-config.rb:547:in `block in all_required_packages'
	from /Users/collimarco/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/pkg-config-1.5.1/lib/pkg-config.rb:370:in `collect_requires'
	from /Users/collimarco/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/pkg-config-1.5.1/lib/pkg-config.rb:376:in `block in collect_requires'
	from /Users/collimarco/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/pkg-config-1.5.1/lib/pkg-config.rb:371:in `each'
	from /Users/collimarco/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/pkg-config-1.5.1/lib/pkg-config.rb:371:in `collect_requires'
	from /Users/collimarco/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/pkg-config-1.5.1/lib/pkg-config.rb:546:in `all_required_packages'
	from /Users/collimarco/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/pkg-config-1.5.1/lib/pkg-config.rb:394:in `collect_cflags'
	from /Users/collimarco/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/pkg-config-1.5.1/lib/pkg-config.rb:302:in `cflags_only_other'
	from /Users/collimarco/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/pkg-config-1.5.1/lib/pkg-config.rb:607:in `cflags_only_other'
	from /Users/collimarco/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/pkg-config-1.5.1/lib/pkg-config.rb:659:in `have_package'
	from /Users/collimarco/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/glib2-4.1.2/lib/mkmf-gnome.rb:477:in `required_pkg_config_package'
	from extconf.rb:41:in `<main>'
```

### Component(s)

Ruby

**Comment by collimarco** [comment]
@kou Thanks a lot! It worked! 

Does that mean that it is not compatible with OpenSSL v3?

**Comment by kou** [comment]
What did you mean "not compatible with OpenSSL v3"?
Did you mean `libarrow.so uses `libssl.1.1.dylib` not `libssl.3.dylib`?
If so, the answer is yes.

If you don't like it, please open a pull request to Homebrew: https://github.com/Homebrew/homebrew-core/blob/11b553b818df335698b88a656113db32771198db/Formula/apache-arrow.rb#L30

**Comment by collimarco** [comment]
Ok, Thanks a lot for the clarification!

A last question:

```
table.slice { |slicer| (slicer['status'] == 200) & (slicer['message'].include? '2OCXG') }
```

`include?` does not exists in this case and raises an error. Is there a place where I can find all the matchers available for Ruby? In particular, is there a method for matching a word in a string (substring matching)?

**Comment by kou** [comment]
We can use `match_substring` compute function: https://arrow.apache.org/docs/cpp/compute.html#containment-tests

But it can't be used with red-arrow 11.0.0. It'll be able to use with red-arrow 12.0.0 by #15285 .

But there isn't a shortcut API to use `match_substring` yet. So we can't use `slicer['message'].match_substring('20CXG')` like API yet. Could you open a new issue for easy to use `match_substring` API?

**Comment by collimarco** [comment]
@kou Thanks. I am closing this issue and moved the other topic here: https://github.com/apache/arrow/issues/34819

**Comment by kou** [comment]
Thanks.

I reopen this. I want to use this to resolve avoiding `PKG_CONFIG_PATH=$(brew --prefix openssl@1.1)/lib/pkgconfig ...` workaround.
