### ISSUE TITLE
[CI][C#] pythonnet requires envvar to be set 

### ISSUE THREAD

**Issue by assignUser** [apache/arrow#35063]
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/ursacomputing/crossbow/actions/runs/4667712326/jobs/8263854333#step:7:67

### Component(s)

C#, Continuous Integration

**Comment by raulcd** [comment]
this should have been closed with the merge, right? @kou @assignUser

**Comment by kou** [comment]
Ah, yes.
Merge script reported an network error when I merge #35061. So I set milestone manually but forgot to close this .Sorry.

**Comment by assignUser** [comment]
This issue was not fixed by the PR, I just opened it while working on the PR. Sorry for the confusion.

**Comment by raulcd** [comment]
Thanks, I see the error seems to be this one, adding it for easy of reference:
```
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:02.15]     Apache.Arrow.Tests.CDataSchemaPythonTest.ImportSchema [FAIL]
  Failed Apache.Arrow.Tests.CDataSchemaPythonTest.ImportSchema [1 ms]
  Error Message:
   Python.Runtime.BadPythonDllException : Runtime.PythonDLL was not set or does not point to a supported Python runtime DLL. See https://github.com/pythonnet/pythonnet#embedding-python-in-net
---- System.MissingMethodException : Failed to load symbol Py_IncRef: dlsym(RTLD_DEFAULT, Py_IncRef): symbol not found
  Stack Trace:
     at Python.Runtime.Runtime.TryUsingDll[T](Func`1 op)
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize()
   at Apache.Arrow.Tests.CDataSchemaPythonTest..ctor() in /Users/runner/work/crossbow/crossbow/arrow/csharp/test/Apache.Arrow.Tests/CDataInterfacePythonTests.cs:line 35
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
----- Inner Stack Trace -----
   at Python.Runtime.Platform.PosixLoader.GetFunction(IntPtr dllHandle, String name)
   at Python.Runtime.Runtime.Delegates.GetFunctionByName(String functionName, IntPtr libraryHandle)
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.InvalidOperationException: GIL must always be released, and it must be released from the same thread that acquired it.
   at Python.Runtime.Py.GILState.Finalize()


Failed!  - Failed:     1, Passed:   769, Skipped:     0, Total:   770, Duration: 638 ms - Apache.Arrow.Tests.dll (net7.0)
Test Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---.
```

**Comment by raulcd** [comment]
CC @wjones127

**Comment by assignUser** [comment]
This also causes the nuget build to fail

**Comment by raulcd** [comment]
The log around the `PYTHONNET_PYDLL` I shared is found on the nuget job: https://github.com/ursacomputing/crossbow/actions/runs/4676295290/jobs/8291018398#step:7:392
which as @assignUser said fails with the same error.

**Comment by assignUser** [comment]
I found the cause of the empty envvar but I don't know what causes it. I ssh'ed into a macos runner and tried to use `find_libpython` but it only openend pythonbahs?? locally it works as expected and just provides the library location.

```
bash-3.2$ python3 -m find_libpython
/Library/Frameworks/Python.framework/Versions/3.11/Pythonbash-3.2$ 
```

**Comment by wjones127** [comment]
Very confused as to how the archery one is failing where it is. When I run this locally:

```
ARCH=arm64v8 archery docker run ubuntu-csharp
```

I find I need to add

```
apt update && apt install -y python3 pip
```

To the docker command. But once I do, the job passes successfully.

**Comment by wjones127** [comment]
For the verification release, I think why this is messed up in CI and not locally is this line:

https://github.com/apache/arrow/blob/49631057e9cdbf991e11e0be4b9aa0dadf616850/csharp/test/Apache.Arrow.Tests/CDataInterfacePythonTests.cs#L35
