### ISSUE TITLE
[CI][C++] Fuzzer nightly tests are failing with duplicate hash error on "generated_uncompressible_zstd.stream"

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#35187]
### Describe the bug, including details regarding any error messages, version, and platform.

The nightly [test-build-cpp-fuzz](https://github.com/ursacomputing/crossbow/actions/runs/4716178128/jobs/8363669173) has been failing for the last days with the following error:
```
 + /src/arrow/cpp/build-support/fuzzing/pack_corpus.py /tmp/corpus /out/arrow-ipc-stream-fuzz_seed_corpus.zip
Traceback (most recent call last):
  File "/src/arrow/cpp/build-support/fuzzing/pack_corpus.py", line 54, in <module>
    main(sys.argv[1], sys.argv[2])
  File "/src/arrow/cpp/build-support/fuzzing/pack_corpus.py", line 47, in main
    process_dir(Path(corpus_dir), zip_output)
  File "/src/arrow/cpp/build-support/fuzzing/pack_corpus.py", line 39, in process_dir
    raise ValueError("Duplicate hash: {0} (in file {1})"
ValueError: Duplicate hash: 19530341bcb2ce81c942121d5719bf1ed35c2b8c (in file /tmp/corpus/generated_uncompressible_zstd.stream)
ERROR:root:Building fuzzers failed.
```

### Component(s)

C++, Continuous Integration

**Comment by raulcd** [comment]
This is hapenning on 12.0.0 but I don't think this is a blocker.

**Comment by kou** [comment]
This is caused by #34631.
It reverts `arrow-testing` update by #34646.
