### ISSUE TITLE
[CI] Some TPCH benchmarks started failing

### ISSUE THREAD

**Issue by ElenaHenderson** [apache/arrow#35383]
### Describe the bug, including details regarding any error messages, version, and platform.

When  https://github.com/apache/arrow/pull/34912 was merged, some TPCH benchmarks started failing. Here is a build with failed benchmarks: https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-test-mac-arm/builds/2835

https://github.com/apache/arrow/pull/35364 fixed some of these failing TPCH benchmarks but these benchmarks are still failing:

<img width="641" alt="Screen Shot 2023-05-01 at 11 29 41 AM" src="https://user-images.githubusercontent.com/5522472/235506807-f830d7fd-3ad3-40e0-89dc-167de1fdf77e.png">

### Component(s)

Benchmarking

**Comment by kou** [comment]
@icexelloss @rtpsw Could you take a look at this?

**Comment by kou** [comment]
BTW, it's difficult to find error messages from the log. Is this a related error for this?

https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-test-mac-arm/builds/2835#0187d7f0-b6aa-4a1a-b054-5873f056fdda/6-1380

```text


[230501-13:39:32.996] [66823] [buildkite.benchmark.run] INFO: Started executing -> conbench tpch --iterations=3 --all=true --drop-caches=true --run-id=$RUN_ID --run-name="$RUN_NAME" --run-reason="$RUN_REASON"
--
  | Traceback (most recent call last):
  | File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/psutil/_psosx.py", line 346, in wrapper
  | return fun(self, *args, **kwargs)
  | File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/psutil/_common.py", line 480, in wrapper
  | raise raise_from(err, None)
  | File "<string>", line 3, in raise_from
  | File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/psutil/_common.py", line 478, in wrapper
  | return fun(self)
  | File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/psutil/_psosx.py", line 373, in _get_kinfo_proc
  | ret = cext.proc_kinfo_oneshot(self.pid)
  | ProcessLookupError: [Errno 3] assume no such process (originated from sysctl(kinfo_proc), len == 0)
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/psutil/__init__.py", line 361, in _init
  | self.create_time()
  | File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/psutil/__init__.py", line 719, in create_time
  | self._create_time = self._proc.create_time()
  | File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/psutil/_psosx.py", line 346, in wrapper
  | return fun(self, *args, **kwargs)
  | File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/psutil/_psosx.py", line 471, in create_time
  | return self._get_kinfo_proc()[kinfo_proc_map['ctime']]
  | File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/psutil/_psosx.py", line 351, in wrapper
  | raise NoSuchProcess(self.pid, self._name)
  | psutil.NoSuchProcess: process no longer exists (pid=44552)
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/runpy.py", line 194, in _run_module_as_main
  | return _run_code(code, main_globals, None,
  | File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/runpy.py", line 87, in _run_code
  | exec(code, run_globals)
  | File "/opt/homebrew/var/buildkite-agent/builds/test-mac-arm/apache-arrow/arrow-bci-benchmark-on-test-mac-arm/buildkite/benchmark/monitor_memory.py", line 24, in <module>
  | mem_rss_bytes = psutil.Process(proc.pid).memory_info().rss
  | File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/psutil/__init__.py", line 332, in __init__
  | self._init(pid)
  | File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/psutil/__init__.py", line 373, in _init
  | raise NoSuchProcess(pid, msg='process PID not found')
  | psutil.NoSuchProcess: process PID not found (pid=44552)

```

Can we improve log output?
