### ISSUE TITLE
[CI] New version of urllib3 seems to be causing GCS tests to fail

### ISSUE THREAD

**Issue by westonpace** [apache/arrow#35410]
### Describe the bug, including details regarding any error messages, version, and platform.

The GCS tests all started failing (e.g. [this example](https://github.com/apache/arrow/actions/runs/4874841668/jobs/8696281630)).

From a diff with the most recent passing version it seems the only thing that changed is the urllib3 version:

Old: urllib3-1.26.15-py2.py3-none-any.whl
New: urllib3-2.0.1-py3-none-any.whl

This seems unlikely to be related to gcs3 but...the error is below and seems to be related to urllib3 so maybe this isn't so far fetched.

```
2023-05-03T17:56:54.4311843Z Traceback (most recent call last):
2023-05-03T17:56:54.4312710Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\requests_toolbelt\_compat.py", line 48, in <module>
2023-05-03T17:56:54.4314727Z     from requests.packages.urllib3.contrib import appengine as gaecontrib
2023-05-03T17:56:54.4319747Z ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\urllib3\contrib\__init__.py)
2023-05-03T17:56:54.4323850Z 
2023-05-03T17:56:54.4325424Z During handling of the above exception, another exception occurred:
2023-05-03T17:56:54.4339984Z 
2023-05-03T17:56:54.4341483Z Traceback (most recent call last):
2023-05-03T17:56:54.4342016Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\runpy.py", line 183, in _run_module_as_main
2023-05-03T17:56:54.4342462Z     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2023-05-03T17:56:54.4342905Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\runpy.py", line 142, in _get_module_details
2023-05-03T17:56:54.4343532Z     return _get_module_details(pkg_main_name, error)
2023-05-03T17:56:54.4343965Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\runpy.py", line 109, in _get_module_details
2023-05-03T17:56:54.4344341Z     __import__(pkg_name)
2023-05-03T17:56:54.4344771Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\testbench\__init__.py", line 15, in <module>
2023-05-03T17:56:54.4345166Z     from . import (
2023-05-03T17:56:54.4345597Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\testbench\common.py", line 31, in <module>
2023-05-03T17:56:54.4346056Z     from requests_toolbelt import MultipartDecoder
2023-05-03T17:56:54.4346538Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\requests_toolbelt\__init__.py", line 12, in <module>
2023-05-03T17:56:54.4347029Z     from .adapters import SSLAdapter, SourceAddressAdapter
2023-05-03T17:56:54.4347881Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\requests_toolbelt\adapters\__init__.py", line 12, in <module>
2023-05-03T17:56:54.4348350Z     from .ssl import SSLAdapter
2023-05-03T17:56:54.4348821Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\requests_toolbelt\adapters\ssl.py", line 16, in <module>
2023-05-03T17:56:54.4349270Z     from .._compat import poolmanager
2023-05-03T17:56:54.4349768Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\requests_toolbelt\_compat.py", line 50, in <module>
2023-05-03T17:56:54.4350245Z     from urllib3.contrib import appengine as gaecontrib
2023-05-03T17:56:54.4350808Z ImportError: cannot import name 'appengine' from 'urllib3.contrib' (C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\urllib3\contrib\__init__.py)
2023-05-03T17:56:54.4351658Z Traceback (most recent call last):
2023-05-03T17:56:54.4352696Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\requests_toolbelt\_compat.py", line 48, in <module>
2023-05-03T17:56:54.4353228Z     from requests.packages.urllib3.contrib import appengine as gaecontrib
2023-05-03T17:56:54.4353887Z ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\urllib3\contrib\__init__.py)
2023-05-03T17:56:54.4354307Z 
2023-05-03T17:56:54.4354502Z During handling of the above exception, another exception occurred:
2023-05-03T17:56:54.4354733Z 
2023-05-03T17:56:54.4354860Z Traceback (most recent call last):
2023-05-03T17:56:54.4355275Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\runpy.py", line 183, in _run_module_as_main
2023-05-03T17:56:54.4355883Z     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2023-05-03T17:56:54.4356925Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\runpy.py", line 142, in _get_module_details
2023-05-03T17:56:54.4357517Z     return _get_module_details(pkg_main_name, error)
2023-05-03T17:56:54.4358523Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\runpy.py", line 109, in _get_module_details
2023-05-03T17:56:54.4358903Z     __import__(pkg_name)
2023-05-03T17:56:54.4359334Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\testbench\__init__.py", line 15, in <module>
2023-05-03T17:56:54.4360008Z     from . import (
2023-05-03T17:56:54.4360550Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\testbench\common.py", line 31, in <module>
2023-05-03T17:56:54.4361020Z     from requests_toolbelt import MultipartDecoder
2023-05-03T17:56:54.4361701Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\requests_toolbelt\__init__.py", line 12, in <module>
2023-05-03T17:56:54.4362222Z     from .adapters import SSLAdapter, SourceAddressAdapter
2023-05-03T17:56:54.4362746Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\requests_toolbelt\adapters\__init__.py", line 12, in <module>
2023-05-03T17:56:54.4363185Z     from .ssl import SSLAdapter
2023-05-03T17:56:54.4363646Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\requests_toolbelt\adapters\ssl.py", line 16, in <module>
2023-05-03T17:56:54.4364105Z     from .._compat import poolmanager
2023-05-03T17:56:54.4364568Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\requests_toolbelt\_compat.py", line 50, in <module>
2023-05-03T17:56:54.4365046Z     from urllib3.contrib import appengine as gaecontrib
2023-05-03T17:56:54.4365610Z ImportError: cannot import name 'appengine' from 'urllib3.contrib' (C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\urllib3\contrib\__init__.py)
```

### Component(s)

Continuous Integration

**Comment by westonpace** [comment]
Ah, `storage-testbench` already upgraded `requests-toolbelt` (https://github.com/googleapis/storage-testbench/pull/492) so we just need a new release of `storage-testbench`.

**Comment by westonpace** [comment]
I've added a PR that pin `urllib3<2`.  However, once gcs-testbench releases a new version we can remove this pinning.  CC @coryan

**Comment by westonpace** [comment]
@coryan thanks for the quick response.  The new version appears to be working fine.
