### ISSUE TITLE
Null fixed-length lists cannot be read from parquet file

### ISSUE THREAD

**Issue by spenczar** [apache/arrow#35692]
### Describe the bug, including details regarding any error messages, version, and platform.

At least from pyarrow (and possibly for c++ more generally), null fixed-length lists cannot be read into a table from a parquet file, but they _can_ be written.

```python
import pyarrow as pa
import pyarrow.parquet as pq
array = pa.nulls(1, pa.list_(pa.int32(), 2))
table = pa.table([array], names=["values"])
pq.write_table(table, "list_table.parquet")
pq.read_table("list_table.parquet")
```
gives
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/swnelson/code/personal/quivr/.quivr-venv/lib/python3.11/site-packages/pyarrow/parquet/core.py", line 2986, in read_table
    return dataset.read(columns=columns, use_threads=use_threads,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/swnelson/code/personal/quivr/.quivr-venv/lib/python3.11/site-packages/pyarrow/parquet/core.py", line 2614, in read
    table = self._dataset.to_table(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_dataset.pyx", line 546, in pyarrow._dataset.Dataset.to_table
  File "pyarrow/_dataset.pyx", line 3449, in pyarrow._dataset.Scanner.to_table
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Expected all lists to be of size=2 but index 1 had size=0
```

This error does _not_ occur for variable-length lists.

This is with pyarrow version 12.0.0.

### Component(s)

Parquet, Python

**Comment by mapleFU** [comment]
Seems that `FixedSizeListReader` in C++ parquet report that error, I'll try to reproduce it

**Comment by spenczar** [comment]
Agreed, this section looks a little off to me:
https://github.com/apache/arrow/blob/8a856c90f9b8fa33de636f98eb33123ccc304b25/cpp/src/parquet/arrow/reader.cc#L676-L682

The offset difference `size` _should_ be zero for null values. I think that code needs to be checking the validity buffer.

**Comment by mapleFU** [comment]
I'll try to write a quick fixing for it :-)

**Comment by jorisvandenbossche** [comment]
FWIW this was a "known" limitation (although the error message isn't very clear ..), and the older issue about this is at:

* https://github.com/apache/arrow/issues/25841

**Comment by jorisvandenbossche** [comment]
The older issue for that might be https://github.com/apache/arrow/issues/24425

**Comment by mapleFU** [comment]
Okay, I'll try to implement them later...

**Comment by wgtmac** [comment]
Issue resolved by pull request 50271
https://github.com/apache/arrow/pull/50271
