### ISSUE TITLE
[Java] maven add the flight-core failed 

### ISSUE THREAD

**Issue by Cai-Yao** [apache/arrow#35759]
### Describe the usage question you have. Please include as many useful details as  possible.

I add these in the pom.xml
``` 
<dependencies>
      <dependency>
          <groupId>org.apache.arrow</groupId>
          <artifactId>flight-core</artifactId>
          <version>${arrow.version}</version>
      </dependency>
  </dependencies>
```
In building, it will occur the problem
```
Exception in thread "main" java.lang.StackOverflowError
	at org.eclipse.aether.util.graph.visitor.PathRecordingDependencyVisitor.visitEnter(PathRecordingDependencyVisitor.java:102)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:343)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
```
What is wrong in my setting?

### Component(s)

Java

**Comment by lidavidm** [comment]
What version of maven, what is the value of `${arrow.version}`, and is it possible to share the full pom.xml?

**Comment by lidavidm** [comment]
Thanks.

I grabbed a copy of Apache Doris and put your pom.xml in place of fe/fe-core/pom.xml.

I can't fully build for other reasons, but at least maven gets past package resolution and gets to compilation of fe-core, so I'm not able to reproduce here.

Do you happen to have a branch to look at?

(Also, it looks like Doris uses very old versions of Arrow? 9.0.0 is somewhat recent but I saw 7.0.0 in the build as well.)

**Comment by lidavidm** [comment]
Thanks! I can reproduce now. Let me see...

**Comment by lidavidm** [comment]
It seems something like https://issues.apache.org/jira/browse/MNG-6737

Doris appears to pin gRPC 1.30.0 in this commit but Flight uses 1.47.0. If I change Doris's pin to 1.47.0 it appears to get past dependency resolution. (Compilation fails but I'm not running the full build script so I probably have something else wrong.)

**Comment by lidavidm** [comment]
@Cai-Yao it sounds like from the other issue that you got past this problem?

**Comment by Cai-Yao** [comment]
> @Cai-Yao it sounds like from the other issue that you got past this problem?

Thanks for your reply, I still haven't located the cause of this problem and I am currently solving it by:

```
<dependency>
    <groupId>org.apache.arrow</groupId>
    <artifactId>flight-core</artifactId>
    <scope>system</scope>
    <systemPath>${pom.basedir}/libs/flight-core-9.0.0.jar</systemPath>
</dependency>
```

I'm not very good at JAVA and will ask the Doris guys for help later to see if it's a problem with some dependencies.

**Comment by xinyiZzz** [comment]
The Maven dependency issue introduced by Apache Doris into Arrow Flight has been resolved.
Here: https://github.com/apache/doris/pull/24314

This issue can be closed, thanks @lidavidm

**Comment by lidavidm** [comment]
Great, glad to hear it!
