### ISSUE TITLE
Confusing error with comparison operators with decimal and unsupported type

### ISSUE THREAD

**Issue by rohanjain101** [apache/arrow#35957]
### Describe the bug, including details regarding any error messages, version, and platform.

```
>>> arr1 = pa.array([decimal.Decimal("1.23")])
>>> arr2 = pa.array(["abc"])
>>> pa.compute.greater(arr1, arr2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ca2_ps_311\Lib\site-packages\pyarrow\compute.py", line 242, in wrapper
    return func.call(args, None, memory_pool)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow\_compute.pyx", line 367, in pyarrow._compute.Function.call
  File "pyarrow\error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Not an integer type: 13
>>>
```

I would expect this to raise a kernel matching error, it seems thats the error that would be raised for all cases other than decimal:

```
>>> arr2 = pa.array(["abc"])
>>> arr3 = pa.array([1.23])
>>> pa.compute.greater(arr2, arr3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ca2_ps_311\Lib\site-packages\pyarrow\compute.py", line 242, in wrapper
    return func.call(args, None, memory_pool)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow\_compute.pyx", line 367, in pyarrow._compute.Function.call
  File "pyarrow\error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\error.pxi", line 121, in pyarrow.lib.check_status
pyarrow.lib.ArrowNotImplementedError: Function 'greater' has no kernel matching input types (string, double)
>>>
```

```
>>> pa.__version__
'12.0.0'
>>>
```

### Component(s)

Python

**Comment by westonpace** [comment]
The problem is in the `CheckDecimals` method here: https://github.com/apache/arrow/blob/apache-arrow-12.0.0/cpp/src/arrow/compute/kernels/scalar_arithmetic.cc#L649

This is part of `ArithmeticFunction::DispatchBest` which attempts to implicitly cast one of the arguments to find a matching kernel (e.g. if we are doing `add(int32,int64)` then we can cast the int32 column to an int64 column).  However, we should probably be failing early if one of the types is "non-arithmetic" (arithmetic types being integer, floating, decimal, and temporal)

**Comment by Sarvesh788** [comment]
Can I work on this issue?

**Comment by Sarvesh788** [comment]
<img width="792" alt="Screenshot 2023-06-13 171925" src="https://github.com/apache/arrow/assets/101782944/2d9cf338-3049-4310-8e4a-8d0a95312546">
@westonpace Do you expect something like this?

**Comment by westonpace** [comment]
Yes, that would be great (though we'll want to add at least one test case too).  Looking in more detail it seems that `is_temporal` might miss the interval types (I had thought intervals were temporal).  I think we can do some basic arithmetic on intervals.

So we could add `is_interval` but then it gets very cluttered.  I wonder if we might just want to add a new type test `is_arithmetic` in type_traits.h.

Another option we could do is to use `is_primitive` which looks like it ends up being the same list except it also includes `boolean` which we don't support for arithmetic.

**Comment by westonpace** [comment]
> Also, I am not sure how testing works is it something like this?

I was hoping for something like this:

```
    // Divide by zero raises
    this->AssertBinopRaises(Power, MakeArray(0), MakeArray(-1),
                            "integers to negative integer powers are not allowed");
```

Except it would test adding a decimal (or int or float) with a string and make sure the resulting error message was `StatusCode::Invalid` and meaningful.

You can add the tests to `src/arrow/compute/kernels/scalar_arithmetic_test.cc`

Thanks!

**Comment by Sarvesh788** [comment]
Really sorry for such a delay. Should I go forward and create a pr? 
<img width="533" alt="image" src="https://github.com/apache/arrow/assets/101782944/e0c982dc-66c7-4d60-aea6-41782b41c0f4">

**Comment by westonpace** [comment]
@Sarvesh788 don't worry about the delay.  Yes, a PR would be great.  Thanks!

**Comment by zanmato1984** [comment]
Issue resolved by pull request 48639
https://github.com/apache/arrow/pull/48639
