### ISSUE TITLE
Dataset.to_table filter error

### ISSUE THREAD

**Issue by vdytyniak-exos** [apache/arrow#36719]
### Describe the bug, including details regarding any error messages, version, and platform.

We faced an issue while trying to use row filter in `Dataset.to_table`:

```
import pyarrow.dataset as ds
import pyarrow as pa
import pyarrow.parquet as pq

amount = pa.array([9999999, 100000001])

table = pa.Table.from_arrays([amount], names=["amount"])
pq.write_table(table, 'mre.parquet')

table = ds.dataset('mre.parquet').to_table(filter=ds.field('amount') / 1e8 > 1) # fails
table = ds.dataset('mre.parquet').to_table(filter=ds.field('amount') / 100000000 > 1) # works
```

Error:
```
Traceback (most recent call last):
  File "/Users/dytyniak/projects/my_project/local_utils/testing.py", line 29, in <module>
    table = ds.dataset('mre.parquet').to_table(filter=ds.field('amount') / 1e8 > 1)
  File "pyarrow/_dataset.pyx", line 546, in pyarrow._dataset.Dataset.to_table
  File "pyarrow/_dataset.pyx", line 3449, in pyarrow._dataset.Scanner.to_table
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Integer value 100000001 not in range: -16777216 to 16777216
```

### Component(s)

Python

**Comment by westonpace** [comment]
Python considers `1e8` to be a `float` and not an `int`:

```
>>> import pyarrow as pa
>>> pa.array([1e8])
<pyarrow.lib.DoubleArray object at 0x7fbfe5933b20>
[
  100000000
]
>>> pa.array([100000000])
<pyarrow.lib.Int64Array object at 0x7fbfe5933ca0>
[
  100000000
]
>>> type(1e8)
<class 'float'>
>>> type(100000000)
<class 'int'>
```

So then arrow sees:

`int64_field / double_literal`.

Arrow refactors this into...

```
cast(int64_field, float32) / cast(double_literal, float32)
```

The expression`cast(int64_field, float32)` is then failing because `100000001` is outside the range of integers that can be safely cast to floats.

One fix would be:

```
table = ds.dataset('mre.parquet').to_table(filter=ds.field('amount') / int(1e8) > 1)
```

**Comment by vdytyniak-exos** [comment]
Thank you for the details. Does it make sense to cast both to float64?

**Comment by westonpace** [comment]
> Thank you for the details. Does it make sense to cast both to float64?

That probably depends on your use case.  I think a good argument could be made that any implicit casting from integer types to floating point types should always prefer float64.

**Comment by vdytyniak-exos** [comment]
What should I do with this issue in that case?
