### ISSUE TITLE
[Packaging][C#] Nuget build is failing on maintenance branch for 13.0.0

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#36863]
### Describe the bug, including details regarding any error messages, version, and platform.

The nuget job is failing on our maintenance branch but does not seem to be failing on main:
https://github.com/ursacomputing/crossbow/actions/runs/5654516424/job/15319395743
I had a minor conflict when cherry-picking but it does not seem related. This was the conflict:
```
$ git diff
diff --cc csharp/test/Apache.Arrow.Tests/Apache.Arrow.Tests.csproj
index cdbfe47,805fb5a..0000000
--- a/csharp/test/Apache.Arrow.Tests/Apache.Arrow.Tests.csproj
+++ b/csharp/test/Apache.Arrow.Tests/Apache.Arrow.Tests.csproj
@@@ -21,4 -24,12 +24,16 @@@
      <ProjectReference Include="..\..\src\Apache.Arrow\Apache.Arrow.csproj" />
    </ItemGroup>
  
- </Project>
++<<<<<<< HEAD
++</Project>
++=======
+   <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible($(TargetFramework), 'net6.0'))">
+     <Compile Remove="TimeOnlyTests.cs" />
+   </ItemGroup>
+ 
+   <ItemGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible($(TargetFramework), 'net5.0'))">
+     <Compile Remove="Extensions\Net472Extensions.cs" />
+   </ItemGroup>
+ 
+ </Project>
++>>>>>>> b557e85 (GH-36812: [C#] Fix C API support to work with .NET desktop framework (#36813))
```
I ended up deleting:
```
I ended up deleting the:
+   <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible($(TargetFramework), 'net6.0'))">
+     <Compile Remove="TimeOnlyTests.cs" />
+   </ItemGroup>
```
because https://github.com/apache/arrow/issues/34620 is not part of the release.

Here the full log of the failure:
```
 + dotnet test
/arrow/csharp /
  Determining projects to restore...
  All projects are up-to-date for restore.
  Apache.Arrow -> /arrow/csharp/artifacts/Apache.Arrow/Debug/netstandard1.3/Apache.Arrow.dll
  Apache.Arrow -> /arrow/csharp/artifacts/Apache.Arrow/Debug/netstandard2.0/Apache.Arrow.dll
  Apache.Arrow -> /arrow/csharp/artifacts/Apache.Arrow/Debug/netcoreapp3.1/Apache.Arrow.dll
  Apache.Arrow -> /arrow/csharp/artifacts/Apache.Arrow/Debug/net6.0/Apache.Arrow.dll
  Apache.Arrow.Tests -> /arrow/csharp/artifacts/Apache.Arrow.Tests/Debug/net7.0/Apache.Arrow.Tests.dll
Test run for /arrow/csharp/artifacts/Apache.Arrow.Tests/Debug/net7.0/Apache.Arrow.Tests.dll (.NETCoreApp,Version=v7.0)
  Apache.Arrow.IntegrationTest -> /arrow/csharp/artifacts/Apache.Arrow.IntegrationTest/Debug/net7.0/Apache.Arrow.IntegrationTest.dll
Microsoft (R) Test Execution Command Line Tool Version 17.6.3 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

  Apache.Arrow.Flight -> /arrow/csharp/artifacts/Apache.Arrow.Flight/Debug/netstandard2.1/Apache.Arrow.Flight.dll
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
The active test run was aborted. Reason: Test host process crashed

Passed!  - Failed:     0, Passed:  1114, Skipped:     0, Total:  1114, Duration: 1 s - Apache.Arrow.Tests.dll (net7.0)
Test Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---.
  Apache.Arrow.Flight -> /arrow/csharp/artifacts/Apache.Arrow.Flight/Debug/netstandard2.0/Apache.Arrow.Flight.dll
  Apache.Arrow.Compression -> /arrow/csharp/artifacts/Apache.Arrow.Compression/Debug/netstandard2.0/Apache.Arrow.Compression.dll
  Apache.Arrow.Compression.Tests -> /arrow/csharp/artifacts/Apache.Arrow.Compression.Tests/Debug/net7.0/Apache.Arrow.Compression.Tests.dll
Test run for /arrow/csharp/artifacts/Apache.Arrow.Compression.Tests/Debug/net7.0/Apache.Arrow.Compression.Tests.dll (.NETCoreApp,Version=v7.0)
Microsoft (R) Test Execution Command Line Tool Version 17.6.3 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     8, Skipped:     0, Total:     8, Duration: 29 ms - Apache.Arrow.Compression.Tests.dll (net7.0)
  Apache.Arrow.Flight.AspNetCore -> /arrow/csharp/artifacts/Apache.Arrow.Flight.AspNetCore/Debug/netcoreapp3.1/Apache.Arrow.Flight.AspNetCore.dll
  Apache.Arrow.Flight.TestWeb -> /arrow/csharp/artifacts/Apache.Arrow.Flight.TestWeb/Debug/net7.0/Apache.Arrow.Flight.TestWeb.dll
  Apache.Arrow.Flight.Tests -> /arrow/csharp/artifacts/Apache.Arrow.Flight.Tests/Debug/net7.0/Apache.Arrow.Flight.Tests.dll
Test run for /arrow/csharp/artifacts/Apache.Arrow.Flight.Tests/Debug/net7.0/Apache.Arrow.Flight.Tests.dll (.NETCoreApp,Version=v7.0)
Microsoft (R) Test Execution Command Line Tool Version 17.6.3 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:42639
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /arrow/csharp/artifacts/Apache.Arrow.Flight.Tests/Debug/net7.0
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:41381
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /arrow/csharp/artifacts/Apache.Arrow.Flight.Tests/Debug/net7.0
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:39049
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /arrow/csharp/artifacts/Apache.Arrow.Flight.Tests/Debug/net7.0
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:36315
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /arrow/csharp/artifacts/Apache.Arrow.Flight.Tests/Debug/net7.0
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:44449
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /arrow/csharp/artifacts/Apache.Arrow.Flight.Tests/Debug/net7.0
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:32851
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /arrow/csharp/artifacts/Apache.Arrow.Flight.Tests/Debug/net7.0
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:40155
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /arrow/csharp/artifacts/Apache.Arrow.Flight.Tests/Debug/net7.0
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:38051
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /arrow/csharp/artifacts/Apache.Arrow.Flight.Tests/Debug/net7.0
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:39785
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /arrow/csharp/artifacts/Apache.Arrow.Flight.Tests/Debug/net7.0
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:36593
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /arrow/csharp/artifacts/Apache.Arrow.Flight.Tests/Debug/net7.0
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:36325
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /arrow/csharp/artifacts/Apache.Arrow.Flight.Tests/Debug/net7.0
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:33377
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /arrow/csharp/artifacts/Apache.Arrow.Flight.Tests/Debug/net7.0
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...

Passed!  - Failed:     0, Passed:    12, Skipped:     0, Total:    12, Duration: 309 ms - Apache.Arrow.Flight.Tests.dll (net7.0)
1
Error: `docker-compose --file /home/runner/work/crossbow/crossbow/arrow/docker-compose.yml run --rm ubuntu-csharp` exited with a non-zero exit code 1, see the process log above.

```

### Component(s)

C#, Continuous Integration, Packaging

**Comment by raulcd** [comment]
@westonpace @CurtHagenlocher could you help me with this one related to the 13.0.0 maintenance branch. Any idea on what is the issue?

**Comment by CurtHagenlocher** [comment]
@raulcd Does this happen consistently? The call stack suggests a network issue which I imagine could be transient.

**Comment by raulcd** [comment]
> @raulcd Does this happen consistently? The call stack suggests a network issue which I imagine could be transient.

I retried when opening the ticket and I just retried a third time now and it failed again: https://github.com/ursacomputing/crossbow/actions/runs/5654516424/job/15319395743

**Comment by CurtHagenlocher** [comment]
Oh, I see; the communications channel here is not part of a Flight test but with the test runner and is a result of the test process crashing.

**Comment by raulcd** [comment]
I have been able to reproduce locally from the `maint-13.0.0` branch with:
```
$ docker-compose build ubuntu-csharp
$ docker-compose run --rm ubuntu-csharp
```
I can confirm that the issue is not reproducible on the main branch where the same docker-compose run is successful.

**Comment by CurtHagenlocher** [comment]
I'm not setup to develop under Linux and have never been able to run the Python interop tests on my Macbook. If you temporarily comment out PythonEngine.Shutdown in line 63 of CDataInterfacePythonTests.cs, does it fix the problem?

**Comment by CurtHagenlocher** [comment]
Wait, it succeeds on the main branch?

**Comment by raulcd** [comment]
It does succeed on main.
If I comment on the `maint-13.0.0`:
```
$ git diff
diff --git a/csharp/test/Apache.Arrow.Tests/CDataInterfacePythonTests.cs b/csharp/test/Apache.Arrow.Tests/CDataInterfacePythonTests.cs
index 4c53b98..ca8d57a 100644
--- a/csharp/test/Apache.Arrow.Tests/CDataInterfacePythonTests.cs
+++ b/csharp/test/Apache.Arrow.Tests/CDataInterfacePythonTests.cs
@@ -60,7 +60,7 @@ namespace Apache.Arrow.Tests
 
             public void Dispose()
             {
-                PythonEngine.Shutdown();
+               // PythonEngine.Shutdown();
             }
         }

```
It also succeeds.

**Comment by CurtHagenlocher** [comment]
The Shutdown is only required to prevent a hang on exit under .NET 4.7.2, for which tests are not yet running anyway in CI. But I can think of no reason that the behavior would be different in the main branch than in the release branch. As an unblocker, instead of commenting out entirely perhaps consider

```
#if !NET5_0_OR_GREATER
                PythonEngine.Shutdown();
#endif
```

**Comment by westonpace** [comment]
FWIW, I can reproduce this locally.  The error message itself seems to be a red herring.  The problem, I think, is that pythonnet is somehow crashing the process (e.g. segfault).  The error message above is just saying "the test process crashed".  It isn't actually giving us any hint to the location or reasoning of the crash.  Oddly, commenting out the shutdown does not stop the crash on my system.  Though unsetting PYTHONNET_PYDLL (and skipping these tests) does prevent the crash.

**Comment by westonpace** [comment]
@raulcd @CurtHagenlocher The root cause, I think, is that we need to cherry pick https://github.com/apache/arrow/issues/36688 (https://github.com/apache/arrow/commit/b4775012ab0f7d8f996538af69f7d1c732f16ff0)  You mentioned that you cherry picked this one already and the issue still reproduced.  However, this fixes it for me locally and it matches the stack trace I got from further debugging which was:

```
OS Thread Id: 0x11059
        Child SP               IP Call Site
00007F1BAEFFB800 00007f5d28cea49f [HelperMethodFrame_1OBJ: 00007f1baeffb800] 
00007F1BAEFFB930 00007F5CA9768CCD System.Runtime.CompilerServices.CastHelpers.ChkCast_Helper(Void*, System.Object) [/_/src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/CastHelpers.cs @ 390]
00007F1BAEFFB960 00007F5CB075D760 Apache.Arrow.C.CArrowArrayStreamExporter+ExportedArrayStream.Free(Void**) [/home/pace/dev/arrow/csharp/src/Apache.Arrow/C/CArrowArrayStreamExporter.cs @ 169]
00007F1BAEFFB9B0 00007F5CB075D68B Apache.Arrow.C.CArrowArrayStreamExporter.Release(Apache.Arrow.C.CArrowArrayStream*) [/home/pace/dev/arrow/csharp/src/Apache.Arrow/C/CArrowArrayStreamExporter.cs @ 138]
00007F1BAEFFBA30 00007f1b72cfa607 [InlinedCallFrame: 00007f1baeffba30] 
00007F1BAEFFBA30 00007f5cac346125 [InlinedCallFrame: 00007f1baeffba30] 
00007F1BAEFFBA20 00007F5CAC346125 Python.Runtime.Runtime.Py_DecRef(Python.Runtime.StolenReference)
00007F1BAEFFBAC0 00007F5CAC345DCC Python.Runtime.Runtime.XDecref(Python.Runtime.StolenReference)
00007F1BAEFFBAE0 00007F5CB070D944 Python.Runtime.Finalizer.DisposeAll()
00007F1BAEFFBC40 00007F5CB075D239 Python.Runtime.Runtime.TryCollectingGarbage(Int32, Boolean)
00007F1BAEFFBCB0 00007F5CB075D148 Python.Runtime.Runtime.TryCollectingGarbage(Int32)
00007F1BAEFFBCD0 00007F5CB075CFB0 Python.Runtime.Runtime.Shutdown()
00007F1BAEFFBCF0 00007F5CB075CDC7 Python.Runtime.PythonEngine.Shutdown()
```

Can you try cherry picking this one commit and see if that fixes it?

**Comment by raulcd** [comment]
Sorry, I did cherry-pick all except that one, because with that one locally on top of `maint-13.0.0` I start getting a bunch of errors:
```
Passed!  - Failed:     0, Passed:    12, Skipped:     0, Total:    12, Duration: 224 ms - Apache.Arrow.Flight.Tests.dll (net7.0)
+ for pdb in artifacts/Apache.Arrow/*/*/Apache.Arrow.pdb
+ sourcelink test artifacts/Apache.Arrow/Debug/net6.0/Apache.Arrow.pdb
203 Documents with errors:
9afcfa9fd34fa0c52bcb1adc2257fb4f73f9729b51fdd56d64b62b9c9ecf119d sha256 csharp /arrow/csharp/src/Apache.Arrow/Arrays/Array.cs
https://raw.githubusercontent.com/raulcd/arrow/f0f27d748aaea1052744da2b2fc04950304d00fe/csharp/src/Apache.Arrow/Arrays/Array.cs
error: url failed NotFound: Not Found
f284d1cb901049b7f4cf0cecbb04fa8d901205d6db59d840bf6d2773c5919fcb sha256 csharp /arrow/csharp/src/Apache.Arrow/Arrays/ArrayData.cs
https://raw.githubusercontent.com/raulcd/arrow/f0f27d748aaea1052744da2b2fc04950304d00fe/csharp/src/Apache.Arrow/Arrays/ArrayData.cs
error: url failed NotFound: Not Found
6d2a52728920cbd2fc1be948d0d51c12e3aa449bb964a1cb9381c1f4ec3406a1 sha256 csharp /arrow/csharp/src/Apache.Arrow/Arrays/ArrayDataConcatenator.cs
https://raw.githubusercontent.com/raulcd/arrow/f0f27d748aaea1052744da2b2fc04950304d00fe/csharp/src/Apache.Arrow/Arrays/ArrayDataConcatenator.cs
error: url failed NotFound: Not Found
5a73a91d315f424fe427a79f8220f335201ca51dac3f32040fc9da8860c713ce sha256 csharp /arrow/csharp/src/Apache.Arrow/Arrays/ArrayDataTypeComparer.cs
https://raw.githubusercontent.com/raulcd/arrow/f0f27d748aaea1052744da2b2fc04950304d00fe/csharp/src/Apache.Arrow/Arrays/ArrayDataTypeComparer.cs
error: url failed NotFound: Not Found
9a7eceb04d09c3fbad488c3aecfcdf14491f7622d8d1bd73fd9e8ba492c3e2b1 sha256 csharp /arrow/csharp/src/Apache.Arrow/Arrays/ArrowArrayBuilderFactory.cs
https://raw.githubusercontent.com/raulcd/arrow/f0f27d748aaea1052744da2b2fc04950304d00fe/csharp/src/Apache.Arrow/Arrays/ArrowArrayBuilderFactory.cs
error: url failed NotFound: Not Found
9e53fda62c9eed119e7439c13d7dbd81fac2ce4ebd37a3a58df8df6e00a02a91 sha256 csharp /arrow/csharp/src/Apache.Arrow/Arrays/ArrowArrayConcatenator.cs
https://raw.githubusercontent.com/raulcd/arrow/f0f27d748aaea1052744da2b2fc04950304d00fe/csharp/src/Apache.Arrow/Arrays/ArrowArrayConcatenator.cs
error: url failed NotFound: Not Found
...
https://raw.githubusercontent.com/raulcd/arrow/f0f27d748aaea1052744da2b2fc04950304d00fe/csharp/src/Apache.Arrow/Types/UInt8Type.cs
error: url failed NotFound: Not Found
4fec63cc0247b7a5640467d6305c0eb6413fc17f260b2a5f787dd2acefa21663 sha256 csharp /arrow/csharp/src/Apache.Arrow/Types/UnionType.cs
https://raw.githubusercontent.com/raulcd/arrow/f0f27d748aaea1052744da2b2fc04950304d00fe/csharp/src/Apache.Arrow/Types/UnionType.cs
error: url failed NotFound: Not Found
87a26c9a282a85e706eaa3cb8bdb956add31770d1a41d445cd0d161cb5ebb0d4 sha256 csharp /arrow/csharp/src/Apache.Arrow/Utility.cs
https://raw.githubusercontent.com/raulcd/arrow/f0f27d748aaea1052744da2b2fc04950304d00fe/csharp/src/Apache.Arrow/Utility.cs
error: url failed NotFound: Not Found
sourcelink test failed
```

**Comment by westonpace** [comment]
Yikes.  That seems unrelated.  Maybe you need to clean your verification environment?  I'm sorry, I don't really know how sourcelink works.  I believe it is checking the published nuget packages to ensure that they have source archives uploaded alongside the binary archives.

**Comment by CurtHagenlocher** [comment]
Oh, thank you, yes. I hadn't realized that change wasn't in the release branch and it's definitely a must-have.
