### ISSUE TITLE
[Java][CI] Enable JDK 21

### ISSUE THREAD

**Issue by danepitkin** [apache/arrow#36994]
### Describe the enhancement requested

Java 21 is the next long-term support (LTS) version after Java 17 and is scheduled to be released in September 2023. 

### Component(s)

Java

**Comment by jarohen** [comment]
related for those arriving here from Google: https://github.com/apache/arrow/issues/35053 (not yet released)

**Comment by raulcd** [comment]
@davisusanibar @danepitkin @lidavidm  what is the status of this one? Is this a release blocker?

**Comment by danepitkin** [comment]
Actually, Eclipse Temurin JDK is starting to be published now. Docker images will take a little bit longer, but maybe it will be ready in time! 🤞

**Comment by Midhunpottammal** [comment]
while enabling arrow with spark in java 21 unhandled `java.lang.UnsupportedOperationException: sun.misc.Unsafe `or `java.nio.DirectByteBuffer.<init>(long, int) `not available . is this issue fixed or how to proceed

**Comment by raulcd** [comment]
@Midhunpottammal can you share more details? which version of Arrow and spark are you using and the stack trace.

**Comment by Midhunpottammal** [comment]
> @Midhunpottammal can you share more details? which version of Arrow and spark are you using and the stack trace.
 
java -version
    

> java version "21.0.2" 2024-01-16 LTS
>     Java(TM) SE Runtime Environment (build 21.0.2+13-LTS-58)
>     Java HotSpot(TM) 64-Bit Server VM (build 21.0.2+13-LTS-58, mixed mode, sharing)

Spark - Version 

> pyspark==3.5.0

pyarrow  -Version 

> pyarrow 15.0.0


Error Log 
TaskContextImpl: Error in TaskCompletionListener
java.lang.IllegalStateException: Memory was leaked by query. Memory leaked: (49152)
Allocator(toArrowBatchIterator) 0/49152/49152/9223372036854775807 (res/actual/peak/limit)

	at org.apache.arrow.memory.BaseAllocator.close(BaseAllocator.java:476)
	at org.apache.spark.sql.execution.arrow.ArrowConverters$ArrowBatchIterator.$anonfun$new$2(ArrowConverters.scala:97)
	at org.apache.spark.sql.execution.arrow.ArrowConverters$ArrowBatchIterator.$anonfun$new$2$adapted(ArrowConverters.scala:95)
	at org.apache.spark.TaskContext$$anon$1.onTaskCompletion(TaskContext.scala:132)
	at org.apache.spark.TaskContextImpl.$anonfun$invokeTaskCompletionListeners$1(TaskContextImpl.scala:144)
	at org.apache.spark.TaskContextImpl.$anonfun$invokeTaskCompletionListeners$1$adapted(TaskContextImpl.scala:144)
	at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:199)
	at org.apache.spark.TaskContextImpl.invokeTaskCompletionListeners(TaskContextImpl.scala:144)
	at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:137)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:172)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
24/03/05 14:02:59 ERROR Executor: Exception in task 11.0 in stage 0.0 (TID 11)
java.lang.UnsupportedOperationException: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available
	at org.apache.arrow.memory.util.MemoryUtil.directBuffer(MemoryUtil.java:174)
	at org.apache.arrow.memory.ArrowBuf.getDirectBuffer(ArrowBuf.java:229)


Full Stack Trace link 

[](https://drive.google.com/file/d/1eyHhJsqgCjCVnAFFR290eOMekvWC42so/view?usp=sharing)

**Comment by iskandari** [comment]
Facing the same issue:
```
pyarrow 15.0.0
pyspark 3.5.0
java = openjdk/21.0.1
```

```
java.lang.UnsupportedOperationException: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available
```

**Comment by danepitkin** [comment]
I don't think you can set `spark.conf.set("Dio.netty.tryReflectionSetAccessible", "true")` at runtime here. Try setting this configuration option before you run pyspark.

**Comment by Midhunpottammal** [comment]
@iskandari @danepitkin I managed to get Arrow working with a lower version of Java in Spark 3.5.0. Here's my stack:

> pyarrow==15.0.0
> pyspark==3.5.0
> java == Java(TM) SE Runtime Environment (build 17.0.10+11-LTS-240)

When I try to move to Java version 21, I encounter the same error
