### ISSUE TITLE
[Python][FlightRPC] arrow/python/examples/flight/client.py pyarrow.lib.ArrowKeyError: 'Flight not found.'. Detail: Python exception: KeyError

### ISSUE THREAD

**Issue by geyungjen** [apache/arrow#37140]
### Describe the usage question you have. Please include as many useful details as  possible.

I use MacOS Big Sur. I use venv with Python 3.8, PyArrow and Pandas were installed by pip only.  I did not use setup.py in arrow.

Some issue with standard arrow/python/examples/flight/client.py.

server.py works fine.

I started the server.py 

(venv) user@users-MBP python % /Users/user/Documents/ml_spark/python_test/PyArrow/venv/bin/python examples/flight/server.py --port 2000
Serving on grpc+tcp://localhost:2000

Then I started client below:

/Users/user/Documents/ml_spark/python_test/PyArrow/venv/bin/python client.py get localhost:2000 -c foo

Got error with _flight.pyx

  File "client.py", line 188, in <module>
    main()
  File "client.py", line 184, in main
    commands[args.action](args, client, connection_args)
  File "client.py", line 91, in get_flight
    info = client.get_flight_info(descriptor)
  File "pyarrow/_flight.pyx", line 1527, in pyarrow._flight.FlightClient.get_flight_info
  File "pyarrow/_flight.pyx", line 78, in pyarrow._flight.check_flight_status
  File "pyarrow/error.pxi", line 119, in pyarrow.lib.check_status
pyarrow.lib.ArrowKeyError: 'Flight not found.'. Detail: Python exception: KeyError

Added some printed lines prior to line at line 91:

info = client.get_flight_info(descriptor)

Run it again, appears command and args and descriptor are all right, get_flight_info failed.

(venv) user@users-MBP flight % /Users/user/Documents/ml_spark/python_test/PyArrow/venv/bin/python client_print.py get localhost:2000 -c foo
******args are Namespace(action='get', command='foo', host='localhost:2000', mtls=None, path=None, tls=False, tls_roots=None) detail is get
******connection_args is {}
descriptor is <pyarrow.flight.FlightDescriptor cmd=b'foo'>
Traceback (most recent call last):
  File "client_print.py", line 192, in <module>
    main()
  File "client_print.py", line 188, in main
    commands[args.action](args, client, connection_args)
  File "client_print.py", line 92, in get_flight
    info = client.get_flight_info(descriptor)
  File "pyarrow/_flight.pyx", line 1527, in pyarrow._flight.FlightClient.get_flight_info
  File "pyarrow/_flight.pyx", line 78, in pyarrow._flight.check_flight_status
  File "pyarrow/error.pxi", line 119, in pyarrow.lib.check_status
pyarrow.lib.ArrowKeyError: 'Flight not found.'. Detail: Python exception: KeyError

I use the code as is in examples.

Thanks

George

### Component(s)

Python

**Comment by geyungjen** [comment]
Never Mind.

It appears command 'foo' is not part of the stored flights, as shown in following block in server.py

    def get_flight_info(self, context, descriptor):
        key = FlightServer.descriptor_to_key(descriptor)
        if key in self.flights:
            table = self.flights[key]
            return self._make_flight_info(key, descriptor, table)
        raise KeyError('Flight not found.')

Thanks, please close this issue.
