### ISSUE TITLE
[Java][Python][FlightRPC] org.apache.arrow.flight.FlightRuntimeException: UNAVAILABLE: RST_STREAM closed stream. HTTP/2 error code: NO_ERROR

### ISSUE THREAD

**Issue by Csehpi** [apache/arrow#37172]
### Describe the bug, including details regarding any error messages, version, and platform.

Hello All,

I would like to ask your help in the following issue I am facing with.

I have a Java and a Python application in different pods running on Kubernetes. On the Python side I have a running Arrow Flight server.
The steps are the following:
- Java side writes data (in batches) to Arrow Flight (working)
- Python side read the data from Arrow Flight (working)
- Python side makes some modifications and writes the data back (in batches) to Arrow Flight (working)
- Java reads the data from Arrow Flight (issue happens here)

Data: 10 Millions of rows with 6 columns, size: 500Mb

Error message:
`org.apache.arrow.flight.FlightRuntimeException: UNAVAILABLE: RST_STREAM closed stream. HTTP/2 error code: NO_ERROR    
    at org.apache.arrow.flight.CallStatus.toRuntimeException(CallStatus.java:131)
    at org.apache.arrow.flight.grpc.StatusUtils.fromGrpcRuntimeException(StatusUtils.java:164)
    at org.apache.arrow.flight.grpc.StatusUtils.fromThrowable(StatusUtils.java:185)
    at org.apache.arrow.flight.FlightStream$Observer.onError(FlightStream.java:454)
    at org.apache.arrow.flight.FlightClient$1.onError(FlightClient.java:331)
    at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
    at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
    at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
    at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
    at org.apache.arrow.flight.grpc.ClientInterceptorAdapter$FlightClientCallListener.onClose(ClientInterceptorAdapter.java:117)
    at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
    at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)`

The interesting is that this error comes 6times from 10, 4 times everything is fine and Java is able to read the data from Arrow Flight.

Version used: 12.0.1 (both Java and Python side)

Do you have any idea?

Thanks a lot,
Peter

### Component(s)

FlightRPC, Java, Python

**Comment by Csehpi** [comment]
I added the following env variables:
```BASH
- name: GRPC_VERBOSITY
   value: debug
- name: GRPC_TRACE
   value: call_error,connectivity_state,pick_first,round_robin,glb
```

The log is:
```BASH
2023-08-16T11:53:09 INFO [PyRunner][Arrow Server]: Reading descriptor key: 64316-0-output
D0816 11:53:09.717006258     186 call.cc:793]                set_final_status SVR
D0816 11:53:09.717024287     186 call.cc:794]                OK
D0816 11:53:10.020085295     202 call.cc:793]                set_final_status SVR
D0816 11:53:10.020191967     202 call.cc:794]                UNKNOWN:Error received from peer unknown {created_time:"2023-08-16T11:53:10.020077803+00:00", grpc_status:1, grpc_message:"Received RST_STREAM with error code 8"}
```

**Comment by lidavidm** [comment]
This still isn't related to Flight. Something in the middle is disconnecting you, or one or the other side of the connection is disconnecting. 

You may also want to enable logs for gRPC and Netty on the client.

**Comment by Csehpi** [comment]
If I enable debug mode on istio side, the issue is the following:

```BASH
'grpc-status', '14'
'grpc-message', 'closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR'
```

**Comment by lidavidm** [comment]
You want the actual logs from gRPC/Netty, I believe.

**Comment by Csehpi** [comment]
In the istio-proxy container, I see the following error messages:

```BASH
2023-09-04T10:34:35.946506Z	debug	envoy http2 external/envoy/source/common/http/http2/codec_impl.cc:675	[C33] error sending data frame: Too many frames in the outbound queue	thread=47
2023-09-04T10:34:35.946534Z	debug	envoy http2 external/envoy/source/common/http/http2/codec_impl.cc:1531	[C33] error sending frames: Too many frames in the outbound queue.	thread=47
```

**Comment by lidavidm** [comment]
Ah, in that case - it sounds like an Envoy configuration issue? e.g. https://github.com/istio/istio/issues/40617

**Comment by Csehpi** [comment]
Thank you the link, but so far nothing helps.
In the meantime, I was able to generate more precise logs from istio-proxy:

```BASH
2023-09-06T08:23:09.525594Z	debug	envoy connection external/envoy/source/common/network/connection_impl.cc:548	[C93] onAboveWriteBufferHighWatermark	thread=44
2023-09-06T08:23:09.559319Z	debug	envoy http2 external/envoy/source/common/http/http2/codec_impl.cc:675	[C93] error sending data frame: Too many frames in the outbound queue	thread=44
2023-09-06T08:23:09.559340Z	debug	envoy http2 external/envoy/source/common/http/http2/codec_impl.cc:675	[C93] error sending data frame: Too many frames in the outbound queue	thread=44
2023-09-06T08:23:09.559344Z	debug	envoy http2 external/envoy/source/common/http/http2/codec_impl.cc:675	[C93] error sending data frame: Too many frames in the outbound queue	thread=44
2023-09-06T08:23:09.559352Z	debug	envoy http2 external/envoy/source/common/http/http2/codec_impl.cc:675	[C93] error sending data frame: Too many frames in the outbound queue
......
2023-09-06T08:23:09.567788Z	debug	envoy http2 external/envoy/source/common/http/http2/codec_impl.cc:675	[C93] error sending data frame: Too many frames in the outbound queue	thread=44
2023-09-06T08:23:09.567791Z	debug	envoy http2 external/envoy/source/common/http/http2/codec_impl.cc:675	[C93] error sending data frame: Too many frames in the outbound queue	thread=44
2023-09-06T08:23:09.567798Z	debug	envoy http2 external/envoy/source/common/http/http2/codec_impl.cc:615	[C93] send buffer under limit 	thread=44
2023-09-06T08:23:09.567803Z	debug	envoy http2 external/envoy/source/common/http/http2/codec_impl.cc:675	[C93] error sending data frame: Too many frames in the outbound queue	thread=44
2023-09-06T08:23:09.567806Z	debug	envoy http2 external/envoy/source/common/http/http2/codec_impl.cc:675	[C93] error sending data frame: Too many frames in the outbound queue	
......
2023-09-06T08:23:09.602083Z	debug	envoy http2 external/envoy/source/common/http/http2/codec_impl.cc:1531	[C93] error sending frames: Too many frames in the outbound queue.	thread=44
2023-09-06T08:23:09.602091Z	debug	envoy http external/envoy/source/common/http/conn_manager_impl.cc:350	[C93] dispatch error: Too many frames in the outbound queue.	thread=44
2023-09-06T08:23:09.602111Z	debug	envoy connection external/envoy/source/common/network/connection_impl.cc:139	[C93] closing data_to_write=268582912 type=2	thread=44
2023-09-06T08:23:09.602130Z	debug	envoy connection external/envoy/source/common/network/connection_impl_base.cc:47	[C93] setting delayed close timer with timeout 1000 ms	thread=44
[2023-09-06T08:23:07.617Z] "POST /arrow.flight.protocol.FlightService/DoGet HTTP/2" 200 - via_upstream - "-" 21 990314204 1442 20 "-" "grpc-java-netty/1.49.1" ...
2023-09-06T08:23:10.030352Z	debug	envoy connection external/envoy/source/common/network/connection_impl.cc:537	[C93] onBelowWriteBufferLowWatermark	thread=44
2023-09-06T08:23:10.030678Z	debug	envoy connection external/envoy/source/common/network/connection_impl.cc:720	[C93] write flush complete	thread=44
......
2023-09-06T08:23:11.032093Z	debug	envoy connection external/envoy/source/common/network/connection_impl_base.cc:69	[C93] triggered delayed close	thread=44
2023-09-06T08:23:11.032115Z	debug	envoy connection external/envoy/source/common/network/connection_impl.cc:250	[C93] closing socket: 1	thread=44
2023-09-06T08:23:11.032156Z	debug	envoy connection external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:320	[C93] SSL shutdown: rc=0	thread=44
2023-09-06T08:23:11.032193Z	debug	envoy conn_handler external/envoy/source/extensions/listener_managers/listener_manager/active_stream_listener_base.cc:120	[C93] adding to cleanup list	thread=44
```

**Comment by lidavidm** [comment]
I'm not familiar with Envoy so I can't offer any further advice.

**Comment by Csehpi** [comment]
@lidavidm thank you for your help. It seems that max_outbound_frames in an envoyfilter solved our issues. I wrote you before that it didnt help but I misconfigured sth so it is fine now. Thanks again

**Comment by lidavidm** [comment]
Ah! Good to know. Thanks for bearing with me.
