### ISSUE TITLE
Python 3.6.7 & pyarrow 0.12.0 failing with OSError: Unrecognized filesystem: <class 'str'>

### ISSUE THREAD

**Issue by REASY** [apache/arrow#3739]
I'm trying to use `pyarrow 0.12.0` to convert CSV file to parquet with python script:
```python3
import time

import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

def convert(csvPath, parquetPath, compression='NONE'):
	start_time = time.perf_counter()
	csv_stream = pd.read_csv(csvPath)
	csv_stream.info(memory_usage='deep')

	t1 = pa.Table.from_pandas(csv_stream)

	schema = t1.schema
	print(schema)

	writer = pq.ParquetWriter(parquetPath, schema, compression)
	writer.write_table(t1)
	writer.close
	elapsed_time = time.perf_counter() - start_time

	print("Converted '{0}' to '{1}' in {2} seconds".format(csvPath, parquetPath, elapsed_time))

convert('data/units.csv', 'data/units.parquet')
```
It used to work with pyarrow `0.11.1`, but failing with `0.12.0`:
```console
Traceback (most recent call last):
  File "convert_csv_to_parquet.py", line 24, in <module>
    convert('data/units.csv', 'data/units.parquet')
  File "convert_csv_to_parquet.py", line 17, in convert
    writer = pq.ParquetWriter(parquetPath, schema, compression)
  File "/mnt/c/repos/apache_arrow/py_arrow/env/lib/python3.6/site-packages/pyarrow/parquet.py", line 367, in __init__
    filesystem, path = resolve_filesystem_and_path(where, filesystem)
  File "/mnt/c/repos/apache_arrow/py_arrow/env/lib/python3.6/site-packages/pyarrow/filesystem.py", line 414, in resolve_filesystem_and_path
    return _ensure_filesystem(filesystem), path
  File "/mnt/c/repos/apache_arrow/py_arrow/env/lib/python3.6/site-packages/pyarrow/filesystem.py", line 395, in _ensure_filesystem
    raise IOError('Unrecognized filesystem: {0}'.format(fs_type))
OSError: Unrecognized filesystem: <class 'str'>
```
#### Create virtual environment
1.  `python3 -m venv env`
2. `source env/bin/activate`
`python -V` in virutal env gives me `Python 3.6.7`
#### Add dependencies 
1. `pip install numpy pandas pyarrow`
2. check the dependencies' versions `pip list`:
```
numpy (1.16.1)
pandas (0.24.1)
pip (9.0.1)
pkg-resources (0.0.0)
pyarrow (0.12.0)
python-dateutil (2.8.0)
pytz (2018.9)
setuptools (39.0.1)
six (1.12.0)
```
#### Run the script
- `python convert_csv_to_parquet.py`

**Comment by wesm** [comment]
You were relying on passing a position argument to a keyword argument in

```
writer = pq.ParquetWriter(parquetPath, schema, compression)
```

Try changing this to 

```
writer = pq.ParquetWriter(parquetPath, schema, compression=compression)
```

**Comment by REASY** [comment]
Thanks, @wesm, it fixed my issue.
