### ISSUE TITLE
[C++] Memory leak in s3 filesystem

### ISSUE THREAD

**Issue by tobim** [apache/arrow#37721]
### Describe the bug, including details regarding any error messages, version, and platform.

The AWS cpp sdk version that is used to build debian packages contains a memory leak bug that was already fixed upstream: https://github.com/aws/aws-sdk-cpp/pull/2373.

When running a simple test binary compiled with address sanitizer we get these errors:

```
Direct leak of 144 byte(s) in 1 object(s) allocated from:
    #0 0x7f735ea959cf in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7f73590df498 in CRYPTO_zalloc (/lib/x86_64-linux-gnu/libcrypto.so.3+0x231498)

Indirect leak of 512 byte(s) in 6 object(s) allocated from:
    #0 0x7f735ea959cf in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7f73590df498 in CRYPTO_zalloc (/lib/x86_64-linux-gnu/libcrypto.so.3+0x231498)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f735ea959cf in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7f735915a8b1 in OPENSSL_sk_deep_copy (/lib/x86_64-linux-gnu/libcrypto.so.3+0x2ac8b1)

Indirect leak of 27 byte(s) in 2 object(s) allocated from:
    #0 0x7f735ea959cf in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7f73590e0af5 in CRYPTO_strdup (/lib/x86_64-linux-gnu/libcrypto.so.3+0x232af5)

Indirect leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0x7f735ea959cf in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7f73590e0c5e in CRYPTO_strndup (/lib/x86_64-linux-gnu/libcrypto.so.3+0x232c5e)  
```

Can you bump the version of the sdk in https://github.com/apache/arrow/blob/main/cpp/thirdparty/versions.txt#L54C1-L54C27? It might also be good to sync it to the version used in https://github.com/apache/arrow/blob/main/ci/conda_env_cpp.txt#L18C1-L18C20.

### Component(s)

C++

**Comment by mapleFU** [comment]
I'm not familiar with s3 sdk, but seems that it release so frequently ( https://github.com/aws/aws-sdk-cpp/tags ) . Should we switch to latest or follow some standard?
