### ISSUE TITLE
[Go][Parquet] Panic reading records from Overture Parquet file

### ISSUE THREAD

**Issue by tschaub** [apache/arrow#37968]
### Describe the bug, including details regarding any error messages, version, and platform.

I'm running into an issue using a record reader to read Parquet data from https://github.com/OvertureMaps/data.

Initially, I tried reading [the full dataset](https://storage.googleapis.com/open-geodata/ch/20230725_211237_00132_5p54t_3b7d7eb3-dd9c-442a-a9b9-404dc936c5d9).  After some debugging, it looks like the problem occurs when reading from the `names` field.

Here is a stripped down version of the original dataset with a single `names` field and one row: [limited.parquet.zip](https://github.com/apache/arrow/files/12779168/limited.parquet.zip)

Here is a test that demonstrates the panic:
```go
func TestOvertureRead(t *testing.T) {
	reader, err := os.Open("testdata/limited.parquet")
	require.NoError(t, err)

	fileReader, err := file.NewParquetReader(reader)
	require.NoError(t, err)

	arrowReader, err := pqarrow.NewFileReader(fileReader, pqarrow.ArrowReadProperties{BatchSize: 1024}, memory.DefaultAllocator)
	require.NoError(t, err)

	recordReader, err := arrowReader.GetRecordReader(context.Background(), nil, nil)
	require.NoError(t, err)

	rowsRead := int64(0)
	for {
		rec, err := recordReader.Read()
		if err == io.EOF {
			break
		}
		require.NoError(t, err)
		rowsRead += rec.NumRows()
	}

	assert.Equal(t, fileReader.NumRows(), rowsRead)
}
```

Here is the output
```bash
# go test -timeout 30s -run ^TestOvertureRead$ github.com/apache/arrow/go/v14/parquet/pqarrow

panic: runtime error: slice bounds out of range [:7] with capacity 0

goroutine 15 [running]:
github.com/apache/arrow/go/v14/parquet/internal/encoding.(*PlainByteArrayDecoder).DecodeSpaced(0x0?, {0x0?, 0x14000329ce8?, 0x1027641b0?}, 0x10338c2d8?, {0x140003d8500?, 0x329c01?, 0x800?}, 0x70001000007ff?)
	/Users/tim/projects/arrow/go/parquet/internal/encoding/byte_array_decoder.go:83 +0x130
github.com/apache/arrow/go/v14/parquet/file.(*byteArrayRecordReader).ReadValuesSpaced(0x1400016f100, 0x0, 0x800?)
	/Users/tim/projects/arrow/go/parquet/file/record_reader.go:841 +0x134
github.com/apache/arrow/go/v14/parquet/file.(*recordReader).ReadRecordData(0x1400007f7a0, 0x400)
	/Users/tim/projects/arrow/go/parquet/file/record_reader.go:548 +0x288
github.com/apache/arrow/go/v14/parquet/file.(*recordReader).ReadRecords(0x1400007f7a0, 0x400)
	/Users/tim/projects/arrow/go/parquet/file/record_reader.go:632 +0x32c
github.com/apache/arrow/go/v14/parquet/pqarrow.(*leafReader).LoadBatch(0x1400007f800, 0x400)
	/Users/tim/projects/arrow/go/parquet/pqarrow/column_readers.go:104 +0xd8
github.com/apache/arrow/go/v14/parquet/pqarrow.(*structReader).LoadBatch.func1()
	/Users/tim/projects/arrow/go/parquet/pqarrow/column_readers.go:242 +0x30
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/Users/tim/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 13
	/Users/tim/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x98
FAIL	github.com/apache/arrow/go/v14/parquet/pqarrow	0.434s
FAIL
```

This is using the latest commit from this repo (a381c05d596cddd341437de6b277520345f9bb8e).

The schema for the `limited.parquet` file looks like this:
```
required group field_id=-1 duckdb_schema {
  optional group field_id=-1 names (Map) {
    repeated group field_id=-1 key_value {
      required byte_array field_id=-1 key (String);
      optional group field_id=-1 value (List) {
        repeated group field_id=-1 list {
          optional group field_id=-1 element (Map) {
            repeated group field_id=-1 key_value {
              required byte_array field_id=-1 key (String);
              optional byte_array field_id=-1 value (String);
            }
          }
        }
      }
    }
  }
}
```
(I selected a subset of the original data with duckdb).

It looks like all of the `names` values are null in the original dataset.

### Component(s)

Go, Parquet

**Comment by tschaub** [comment]
It looks like this is the same issue reported in #37712.  And I confirmed that the test above passes with the fix from @zeroshade in #37785.
