### ISSUE TITLE
Token parameter error - flight-sql-jdbc-driver-13.0.0 

### ISSUE THREAD

**Issue by jeremiahOkai** [apache/arrow#37987]
### Describe the usage question you have. Please include as many useful details as  possible.

I am trying to use flight-sql-jdbc-driver-13.0.0.jar to make a connection to the DBT Semantic layer using the following JDBC URL:
jdbc:arrow-flight-sql://semantic-layer.cloud.getdbt.com:443?environmentId=239721&token=dbtc_twHdVQMTZBAr3HXM7ZeJudRLSRiHf-rPVzOAxABwPCbfPqLYpw&disableCertificateVerification=true

I get the following error below:

LF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Traceback (most recent call last):
  File "org.jpype.JPypeContext.java", line -1, in org.jpype.JPypeContext.callMethod
cfjd.org.apache.arrow.flight.cfjd.org.apache.arrow.flight.FlightRuntimeException: cfjd.org.apache.arrow.flight.FlightRuntimeException: INVALID_ARGUMENT: token is a required connection parameter

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "org.jpype.JPypeContext.java", line -1, in org.jpype.JPypeContext.callMethod
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/Jeremiah.Okai/Documents/pyProjects/dev_shop/dev-env/dags/checkmate.py", line 83, in <module>
    conn = jaydebeapi.connect(
  File "/Users/Jeremiah.Okai/.local/share/virtualenvs/dev_shop-5Elav3LG/lib/python3.10/site-packages/jaydebeapi/__init__.py", line 412, in connect
    jconn = _jdbc_connect(jclassname, url, driver_args, jars, libs)
  File "/Users/Jeremiah.Okai/.local/share/virtualenvs/dev_shop-5Elav3LG/lib/python3.10/site-packages/jaydebeapi/__init__.py", line 230, in _jdbc_connect_jpype
    return jpype.java.sql.DriverManager.getConnection(url, *dargs)
java.sql.java.sql.SQLException: java.sql.SQLException: cfjd.org.apache.arrow.flight.FlightRuntimeException: INVALID_ARGUMENT: token is a required connection parameter

### Component(s)

Other

**Comment by aiguofer** [comment]
Hey @jeremiahOkai . This issue is because some tools try to use an empty username/password if none are provided. This was fixed in this PR https://github.com/apache/arrow/issues/37073 and should be available in version 14.
