### ISSUE TITLE
StructArray.from_arrays does not work well with FixedSizeList-typed data

### ISSUE THREAD

**Issue by spenczar** [apache/arrow#38026]
### Describe the bug, including details regarding any error messages, version, and platform.

Pyarrow's `StructArray.from_arrays` constructor will reject valid non-arrow data (for example a Python list-of-lists or Pandas Series) if the struct field specifies a fixed-length list.

Here's an example - first a bit of setup:
```py
import pyarrow as pa
import pandas as pd
dtype = pa.list_(pa.int64(), 2)
data_list = [[1, 2], [3, 4]]
data_pd_series = pd.Series(data_list)
data_array = pa.array(data_list, dtype)
```

Now, calling `pa.StructArray.from_arrays(foo, fields=[pa.field("x", dtype)])` should work regardless of whether `foo` is `data_list`, or `data_pd_series`, or `data_array`. But no:

```py
>>> sa = pa.StructArray.from_arrays([data_list], fields=[pa.field("x", dtype)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/array.pxi", line 2886, in pyarrow.lib.StructArray.from_arrays
  File "pyarrow/array.pxi", line 1596, in pyarrow.lib.Array.validate
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Struct child array #0 does not match type field: list<item: int64> vs fixed_size_list<item: int64>[2]
>>> sa = pa.StructArray.from_arrays([data_pd_series], fields=[pa.field("x", dtype)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/array.pxi", line 2886, in pyarrow.lib.StructArray.from_arrays
  File "pyarrow/array.pxi", line 1596, in pyarrow.lib.Array.validate
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Struct child array #0 does not match type field: list<item: int64> vs fixed_size_list<item: int64>[2]
>>>
>>> sa = pa.StructArray.from_arrays([data_array], fields=[pa.field("x", dtype)])
```

It appears that `pa.StructArray.from_arrays` casts non-pyarrow types, and _then_ validates against the schema without attempting another cast, while `pa.array` works differently somehow.

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
@spenczar thanks for the report!

Indeed, we currently just convert the input to an array, regardless of the field information the user provides:

https://github.com/apache/arrow/blob/334c93726f3c9d9e69eb51136c7f354974c739fd/python/pyarrow/array.pxi#L3128C9-L3128C46

This should probably have an if/else separate blocks depending on whether names or fields was specified, something like:

```
if names is not None:
    arrays = [asarray(x) for x in arrays]
else:
    arrays = [asarray(arr, field.type) for arr, field in zip(arrays, fields)]
```

(assuming that at that point we already validated `fields` to be actual Field objects, which is now a bit more down, but that can be moved up)

PRs to fix this are certainly welcome!

**Comment by spenczar** [comment]
That looks right. In further testing, I found many more types that have this issue (string vs large_string, etc). I'll work on a PR.
