### ISSUE TITLE
libgrpc problem in new pyarrow version (between 12.0.1 to 13.0.0)

### ISSUE THREAD

**Issue by Shamir-S** [apache/arrow#38280]
### Describe the bug, including details regarding any error messages, version, and platform.

Hi,

Recently when creating conda env with new pyarrow, I get the following error when trying to connect to a grpc server (using native grpc or using arrowflight which uses grpc under the hood)

DNS resolution failed for server-address:8815: C-ares status is not ARES_SUCCESS qtype=A name=server-address is_balancer=0: Could not contact DNS servers. gRPC client debug context: UNKNOWN:DNS resolution failed for server-address.us-east-1.elb.amazonaws.com:8815: C-ares status is not ARES_SUCCESS qtype=A name=server-address is_balancer=0: Could not contact DNS servers {grpc_status:14, created_time:"2023-10-16T15:42:25.182012209+03:00"}. Client context: IOError: Server never sent a data message. Detail: Internal

This does not occur when I install any pyarrow version <= 12.0.0
I think the problem might be introduced with libgrpc=1.58.1, but I'm not sure. 

Would appreciate help
Thanks

### Component(s)

Python

**Comment by kou** [comment]
@h-vetinari Have you heard this problem for conda packages?

**Comment by h-vetinari** [comment]
Thanks for the ping. We continuously rebuild arrow (and many other packages) for new versions of underlying packages, including grpc & protobuf, most recently for grpc 1.58.1 & protobuf 4.24.3. This happened across all maintenance branches (v10-v13), so if the problem/bug is related to grpc 1.58, you'll get it on arrow 12 as well.

Though, to be honest, "Could not contact DNS servers" sounds like a connectivity issue; I'm not sure if the URL `server-address.us-east-1.elb.amazonaws.com:8815` has been obfuscated for privacy (it's not reachable for me, also without the port number), but given the AWS-context, it sounds quite plausible to me that there could be an issue around accessing a private resource in the cloud, e.g. because the environment where arrow is running does not have the right credentials / tokens or is not in the right VPN.

In any case, short of a more concrete bug report (e.g. a reproducer or better: a test case; alternatively some issue reference in grpc, or other affected third-party software) there's not much we in conda-forge can do. We run the full pyarrow test suite before publishing packages, so from that POV, the packages are fully functional (as much as we can reasonably assure).

**Comment by xshirax** [comment]
Hi @h-vetinari 

I wrote a minimal code example to demonstrate the bug, you can see it and run here:

https://github.com/xshirax/arrowflight_demo

Currently in the dockerfile I installed pyarrow 13.0.0 with grpclib 1.58 which is the one that installed by default. if you will change in both client and server dockerfiles to -

RUN micromamba install pyarrow=13.0.0 **libgrpc=1.57** -c conda-forge

It will work! 

This has nothing to do with aws...

Thanks

**Comment by h-vetinari** [comment]
Thanks for the minimal example! I opened two PRs to check this on the grpc feedstock:
https://github.com/conda-forge/grpc-cpp-feedstock/pull/336
https://github.com/conda-forge/grpc-cpp-feedstock/pull/337

**Comment by h-vetinari** [comment]
You example fails with both grpc 1.57 & 1.58 in the following way (added linebreaks to `FlightUnavailableError` message for legibility)
```
Starting server...
Flight server listening on grpc://0.0.0.0:8815
Running client...
Traceback (most recent call last):
  File "test_arrowflight.py", line 19, in <module>
    response = client.do_get(flight.Ticket(ticket_name)).read_all()
  File "pyarrow/_flight.pyx", line 1560, in pyarrow._flight.FlightClient.do_get
  File "pyarrow/_flight.pyx", line 68, in pyarrow._flight.check_flight_status
pyarrow._flight.FlightUnavailableError: Flight returned unavailable error, with message:
    DNS resolution failed for arrowflight-server:8815:
    C-ares status is not ARES_SUCCESS qtype=A name=arrowflight-server is_balancer=0:
    Domain name not found. gRPC client debug context:
    UNKNOWN:DNS resolution failed for arrowflight-server:8815:
    C-ares status is not ARES_SUCCESS qtype=A name=arrowflight-server is_balancer=0:
    Domain name not found {created_time:"2023-10-20T08:17:40.66240294+00:00", grpc_status:14}. Client context:
    IOError: Server never sent a data message. Detail: Internal
```

It's possible that I didn't translate your example correctly, you're welcome to double-check and suggest adaptations.

**Comment by xshirax** [comment]
Hi

After further investigation I found this issue on the c-ares repository: https://github.com/c-ares/c-ares/issues/571
There seems to be a regression added to this module, which was recently fixed (last week) by this commit https://github.com/c-ares/c-ares/commit/a070d7835d667b2fae5266fe1b790677dae47d25

Do you think this fix will be available in the next version of grpc? Do you need rebuild the package with this fix? (I haven't tested this fix yet)

Meanwhile, I also found a workaround, if anyone is bumping into this issue in the future: avoid using c-ares as the dns resolver, and instead use "native" dns resolution via the environment variable `GRPC_DNS_RESOLVER=native`. 

To set the environment variable I had to use the `os` package:


```
os.environ["GRPC_DNS_RESOLVER"] = "native"
```

Passing it using the `generic_options` argument in the `flight.connect()` function did not work for some reason.
