### ISSUE TITLE
Can't get column from ParquetFile schema using PyArrow

### ISSUE THREAD

**Issue by JonathanDCohen** [apache/arrow#38476]
### Describe the bug, including details regarding any error messages, version, and platform.

Consider this code

```python
import pandas as pd
from pyarrow.parquet import ParquetFile

df = pd.DataFrame({"a": [1], "b": [2]})
df.to_parquet('/tmp/test.parquet')
f = ParquetFile('/tmp/test.parquet')
f.schema.column('a')
```

Using pyarrow 11.0.0 and pandas 1.5.3, I get the following error from the last line:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/_parquet.pyx", line 907, in pyarrow._parquet.ParquetSchema.column
TypeError: '<' not supported between instances of 'str' and 'int'
```

### Component(s)

Python

**Comment by amoeba** [comment]
Hi @JonathanDCohen, thanks for the bug report. `f.schema.column` takes a column index ([docs](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.ParquetSchema.html#pyarrow.parquet.ParquetSchema.column)) rather than a name so you should use it like,

```python
>>> f.schema.column(0)
<ParquetColumnSchema>
  name: a
  path: a
  max_definition_level: 1
  max_repetition_level: 0
  physical_type: INT64
  logical_type: None
  converted_type (legacy): NONE
```

It would be good to add a check for the type that argument or maybe even allow the user to pass a column name in addition to an index. Would you be interested in contributing a change?
