### ISSUE TITLE
[Python] Can't read a partitioned dataset using directory partitioning with file paths

### ISSUE THREAD

**Issue by davlee1972** [apache/arrow#38485]
### Describe the bug, including details regarding any error messages, version, and platform.

**Directory partitioning breaks pyarrow.dataset.dataset when a list of files are passed in instead of a base dir**

This is a problem on both linux and window platforms.

My current use case is that we have a lot of legacy files sitting in yyyymmdd named directories.
Unfortunately there is a mix of files in different formats in each yyyymmdd directory so I'm trying to intialize a pyarrow.dataset using a list of file paths.

Working example without directory partitioning:
```
import pyarrow as pa
import pyarrow.dataset as ds
from pyarrow.fs import LocalFileSystem

d = ds.dataset("c:/temp/ic/20230926/IndexConstituents20230926.csv", format="csv")
d.files

>>> d.files
['c:/temp/ic/20230926/IndexConstituents20230926.csv']
```

Broken example with directory partitioning when using file paths:
```
import pyarrow as pa
import pyarrow.dataset as ds

part = ds.partitioning(pa.schema([("yyyymmdd", pa.int32())]))
d = ds.dataset("c:/temp/ic/20230926/IndexConstituents20230926.csv", format="csv", partitioning=part

>>> d = ds.dataset(["c:/temp/ic/20230926/IndexConstituents20230926.csv"], format="csv", partitioning=part)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\pyarrow\dataset.py", line 785, in dataset
    return _filesystem_dataset(source, **kwargs)
  File "C:\Anaconda3\lib\site-packages\pyarrow\dataset.py", line 475, in _filesystem_dataset
    return factory.finish(schema)
  File "pyarrow\_dataset.pyx", line 3016, in pyarrow._dataset.DatasetFactory.finish
  File "pyarrow\error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: error parsing 'c:' as scalar of type int32

```

Working example with hive partitioning when using file paths:

```
import pyarrow as pa
import pyarrow.dataset as ds

part = ds.partitioning(pa.schema([("yyyymmdd", pa.int32())]), flavor="hive")
d = ds.dataset("c:/temp/ic/yyyymmdd=20230926/IndexConstituents20230926.csv", format="csv", partitioning=part)
d.files

>>> d.files
['c:/temp/ic/yyyymmdd=20230926/IndexConstituents20230926.csv']
```

I believe the fix is to parse the directories in REVERSE order.
If the directory partitioning columns are: yyyymmdd and currency.

When parsing: 'c:/temp/ic/20230926/USD/IndexConstituents20230926.csv'
The directories in reverse order are USD, 20230926, ic, temp and c:

The partitioning directories in reverse order are:
currency first as USD
yyyymmdd second as 20230926

**Comment by davlee1972** [comment]
Seems like there should some sort of reverse_path() function to capture partitioned directory values..

**Comment by davlee1972** [comment]
One more oddity..

To use directory partitioning you have to omit @flavor or pass in @flavor=None.

Passing in @flavor = "directory" produces an error..

```
>>> part = ds.partitioning(pa.schema([("yyyymmdd", pa.int32())]), flavor="directory")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\leed\Anaconda3\lib\site-packages\pyarrow\dataset.py", line 277, in partitioning
    raise ValueError("Unsupported flavor")
ValueError: Unsupported flavor
```

```
>>> part = ds.partitioning(pa.schema([("yyyymmdd", pa.int32())]), flavor=None)
>>> part
<pyarrow._dataset.DirectoryPartitioning object at 0x000001FCFA0054E0>
```

**Comment by soxofaan** [comment]
> ```
> d = ds.dataset("c:/temp/ic/20230926/IndexConstituents20230926.csv", format="csv", partitioning=part)
> ```

If you use partitioning, don't you have to start reading from the root of that structure? So in your case something like

```
d = ds.dataset("c:/temp/ic/", format="csv", partitioning=part)
```

**Comment by davlee1972** [comment]
I'm trying to initialize a dataset using a list of files..

Using a root folder won't work because I have a mix of legacy files in the same folder.

Prices.parquet
Trades.parquet
Accounts.parquet

All in the same subdirectory.

**Comment by davlee1972** [comment]
Ok I found a workaround, but it would be better if this was automatically handled by pyarrow.dataset.dataset()..

https://arrow.apache.org/docs/python/generated/pyarrow.dataset.dataset.html#pyarrow.dataset.dataset
dataset() has a partition_base_dir parameter now..
```
partition_base_dir: str
For the purposes of applying the partitioning, paths will be stripped of the partition_base_dir. Files not matching the partition_base_dir prefix will be skipped for partitioning discovery. The ignored files will still be part of the Dataset, but will not have partition information.
```
Can we automatically determine partition_base_dir if dataset() is called with a list of files and partitioning?

```
import pyarrow.dataset as ds
import pyarrow as pa

my_dataset = ds.dataset([
    "c:/temp/abc/xyz/usa/20230926/IndexConstituents20230926.csv",
    "c:/temp/abc/xyz/france/20230927/IndexConstituents20230927.csv",
    "c:/temp/abc/xyz/germany/20230928/IndexConstituents20230928.csv",
    ],
    partitioning= ds.partitioning(pa.schema([("country", pa.string()),("date_as_int", pa.int32())]))
    partition_base_dir ="c:/temp/abc/xyz"
)
```
A dataset() call like above should automatically figure out and pass partition_base_dir.

You can count the number of partitioning columns and walk back file name directories.
c:/temp/abc/xyz/usa/20230926 with 2 partitioning columns becomes c:/temp/abc/xyz
