### ISSUE TITLE
[C++] Consider adding Memory Sanitizer build

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#39025]
### Describe the enhancement requested

Valgrind already tries to detect uninitialized reads, but it would be worth checking whether MSan can be easily enabled for further checks:
https://clang.llvm.org/docs/MemorySanitizer.html

### Component(s)

C++

**Comment by pitrou** [comment]
cc @felipecrv @benibus

**Comment by pitrou** [comment]
I gave this a try, but I get a lot of runtime errors and the ignorelist doesn't seem to work for some reason.

I originally got errors with OpenSSL and protobuf, but even after disabling those, I get other errors such as:
```
Uninitialized bytes in __interceptor_strlen at offset 0 inside [0x7ffceb395310, 1)
==81632==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f7913e7a265 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string<std::allocator<char> >(char const*, std::allocator<char> const&) (.constprop.0) gtest-all.cc.o
    #1 0x7f79137ffc96 in _GLOBAL__sub_I_gtest_all.cc gtest-all.cc.o
    #0 0x7f791782f47d in
    #1 0x7f791782f567 in
    #2 0x7f79178492c9 in
```

This is with clang 14.0 as in the ASAN CI build.

**Comment by thisisnic** [comment]
This issue has been marked as stale because it has had no activity in the past 2 years. Please remove the stale label or comment below, or this issue will be closed in 14 days.

**Comment by thisisnic** [comment]
This issue has been closed because there has been no activity for the 14 days since the stale warning. Feel free to reopen if this has been closed in error.
