### ISSUE TITLE
[Java] Improve error message when Flight Core TestTls fails

### ISSUE THREAD

**Issue by jbonofre** [apache/arrow#39170]
### Describe the enhancement requested

As discussed on the mailing list, when we forgot `git submodule update --init --recursive`, `cert0.pem` and other files are not present in `testing/data` folder.
It means `TestTls` fails, but it's not obvious to find why related to https://arrow.apache.org/docs/dev/developers/java/building.html#building.

I propose to display a "dev friendly" message ;)

### Component(s)

Java

**Comment by raulcd** [comment]
Just as a note, this seems to be the same issue I am facing on some of the verification tasks on the 14.0.2 RC2 PR: https://github.com/apache/arrow/pull/39155
I've commented on Zulip but I can see some failures like:
```
 E           RuntimeError: Test resource /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/arrow-14.0.2.XXXXX.6zoUTjWt/apache-arrow-14.0.2/testing/data/flight/root-ca.pem not found; did you initialize the test resource submodule?
E           Traceback (most recent call last):
E             File "/private/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/arrow-14.0.2.XXXXX.6zoUTjWt/venv-wheel-3.10-macosx_10_14_x86_64/lib/python3.10/site-packages/pyarrow/tests/test_flight.py", line 78, in read_flight_resource
E               with (root / path).open("rb") as f:
E             File "/usr/local/Cellar/python@3.10/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 1119, in open
E               return self._accessor.open(self, mode, buffering, encoding, errors,
E           FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/arrow-14.0.2.XXXXX.6zoUTjWt/apache-arrow-14.0.2/testing/data/flight/root-ca.pem'
```
or:
```
E1209 11:27:03.689191000 4697794048 ssl_security_connector.cc:273]     Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E1209 11:27:03.689258000 4697794048 chttp2_server.cc:1053]             UNKNOWN:Unable to create secure server with credentials of type Ssl {created_time:"2023-12-09T11:27:03.689234+00:00"}
/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/arrow-14.0.2.XXXXX.zxdYorT4/apache-arrow-14.0.2/cpp/src/arrow/flight/flight_test.cc:465: Failure
Failed
'ExampleTlsCertificates(&options.tls_certificates)' failed with IOError: Could not open certificate: /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/arrow-14.0.2.XXXXX.zxdYorT4/apache-arrow-14.0.2/testing/data/flight/cert0.pem
[  FAILED  ] TestTls.DoAction (2 ms)
```
I might revert the following commit: https://github.com/apache/arrow/commit/bc1ea6f004ac6fb0bca271600ad3b9f36edb4c92 on the RC2 branch to see if those failures for the Release are solved.
