### ISSUE TITLE
[GLib] How to build c_glib?

### ISSUE THREAD

**Issue by llama90** [apache/arrow#39400]
### Describe the usage question you have. Please include as many useful details as  possible.

I need to build GLib to resolve the following issue.

* #39225 

Based on the GLib README.md file, it seems that building GLib will base the build on the version of Arrow installed via Homebrew. However, when attempting to build, the following error occurs.

```
$ meson compile -C c_glib.build
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /opt/homebrew/bin/ninja -C /Users/lama/workspace/arrow-latest/c_glib.build
ninja: Entering directory `/Users/lama/workspace/arrow-latest/c_glib.build'
[1/27] Linking target arrow-glib/libarrow-glib.1500.dylib
ld: warning: dylib (/opt/homebrew/Cellar/apache-arrow/14.0.1_2/lib/libarrow.dylib) was built for newer macOS version (14.0) than being linked (13.3)
ld: warning: dylib (/opt/homebrew/Cellar/apache-arrow/14.0.1_2/lib/libarrow_acero.dylib) was built for newer macOS version (14.0) than being linked (13.3)
[2/27] Compiling C++ object gandiva-glib/libgandiva-glib.1500.dylib.p/function-registry.cpp.o
FAILED: gandiva-glib/libgandiva-glib.1500.dylib.p/function-registry.cpp.o
ccache c++ -Igandiva-glib/libgandiva-glib.1500.dylib.p -I. -I../c_glib -I/opt/homebrew/Cellar/apache-arrow/14.0.1_2/include -I/opt/homebrew/Cellar/glib/2.78.3/include -I/opt/homebrew/Cellar/glib/2.78.3/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.78.3/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/Cellar/pcre2/10.42/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/ffi -fdiagnostics-color=always -Wall -Winvalid-pch -std=c++17 -O3 -Wmissing-declarations -MD -MQ gandiva-glib/libgandiva-glib.1500.dylib.p/function-registry.cpp.o -MF gandiva-glib/libgandiva-glib.1500.dylib.p/function-registry.cpp.o.d -o gandiva-glib/libgandiva-glib.1500.dylib.p/function-registry.cpp.o -c ../c_glib/gandiva-glib/function-registry.cpp
../c_glib/gandiva-glib/function-registry.cpp:115:45: error: no member named 'default_function_registry' in namespace 'gandiva'
  auto gandiva_function_registry = gandiva::default_function_registry();
                                   ~~~~~~~~~^
1 error generated.
[4/27] Generating arrow-glib/Arrow-1.0.gir with a custom command (wrapped by meson to set env)
ld: warning: dylib (/opt/homebrew/Cellar/apache-arrow/14.0.1_2/lib/libarrow_acero.dylib) was built for newer macOS version (14.0) than being linked (13.3)
ld: warning: dylib (/opt/homebrew/Cellar/apache-arrow/14.0.1_2/lib/libarrow.dylib) was built for newer macOS version (14.0) than being linked (13.3)
ninja: build stopped: subcommand failed.
```

Is there a way to avoid such errors by building GLib with a reference to local Arrow C++ build?

### Component(s)

GLib

**Comment by kou** [comment]
Could you use https://github.com/apache/arrow/tree/main/c_glib#how-to-build-by-developers not https://github.com/apache/arrow/tree/main/c_glib#how-to-build-by-users ?

If you don't use Apache Arrow C++ installed via Homebrew, could you remove it?

**Comment by llama90** [comment]
Thank you for your response.

Umm... When I removed the Arrow package from Homebrew, I encountered the following error message.

```
Run-time dependency arrow found: NO (tried pkgconfig, framework and cmake)

c_glib/meson.build:80:10: ERROR: Dependency "arrow" not found, tried pkgconfig, framework and cmake
```

BTW, I am currently looking for a way to directly reference the Arrow library when executing the `meson.build` script.

**Comment by llama90** [comment]
Oh... I've confirmed from the `meson.build` script that the `-Darrow_cpp_build_dir` and `-Darrow_cpp_build_type` options allow me to specify the build path. And I've successfully compiled it.

@kou Thank you for giving me the hints to move forward.

**Comment by llama90** [comment]
Do you know how to solve the following problem?

There is an error when executing the test script. The following error messages were observed for each execution:

https://github.com/apache/arrow/blob/4543f5d8394e221681c362f4e7c8a7268823b2cd/c_glib/README.md?plain=1#L233-L234

Path where c_glib was built:

```
Could not locate Gemfile or .bundle/ directory
```

Path of c_glib:

```
bundle exec ../c_glib/test/run-test.sh
(null)-WARNING **: Failed to load shared library 'libarrow-glib.1500.dylib' referenced by the typelib: dlopen(libarrow-glib.1500.dylib, 0x0009): tried: 'libarrow-glib.1500.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibarrow-glib.1500.dylib' (no such file), '/usr/lib/libarrow-glib.1500.dylib' (no such file, not in dyld cache), 'libarrow-glib.1500.dylib' (no such file), '/usr/local/lib/libarrow-glib.1500.dylib' (no such file), '/usr/lib/libarrow-glib.1500.dylib' (no such file, not in dyld cache)
	from /Users/lama/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:606:in `load_interface_info'
	from /Users/lama/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:75:in `load_info'
	from /Users/lama/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:44:in `block (2 levels) in load'
	from /Users/lama/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/repository.rb:34:in `block (2 levels) in each'
	from <internal:numeric>:237:in `times'
	from /Users/lama/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/repository.rb:33:in `block in each'
	from /Users/lama/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/repository.rb:32:in `each'
	from /Users/lama/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/repository.rb:32:in `each'
	from /Users/lama/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:43:in `block in load'
	from /Users/lama/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:636:in `prepare_class'
	from /Users/lama/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:41:in `load'
	from /Users/lama/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection.rb:44:in `load'
	from /Users/lama/workspace/arrow-latest/c_glib/test/run-test.rb:33:in `<main>'
/Users/lama/workspace/arrow-latest/c_glib/test/run-test.rb:44:in `alias_method': undefined method `value?' for class `Arrow::BooleanScalar' (NameError)

    alias_method :value, :value?
    ^^^^^^^^^^^^
	from /Users/lama/workspace/arrow-latest/c_glib/test/run-test.rb:44:in `<class:BooleanScalar>'
	from /Users/lama/workspace/arrow-latest/c_glib/test/run-test.rb:43:in `<module:Arrow>'
	from /Users/lama/workspace/arrow-latest/c_glib/test/run-test.rb:34:in `<main>'
```

**Comment by kou** [comment]
Could you use `meson setup --cmake-prefix-path=${CMAKE_INSTALL_PREFIX_FOR_ARROW_CPP} ...` instead of `-Darrow_cpp_build_dir` and `-Darrow_cpp_build_type`? They are for non installed Apache Arrow C++. (They are needed for building `.deb`/`.rpm`.)
In general, we should use installed Apache Arrow C++.

**Comment by kou** [comment]
Ah, sorry. The command line is wrong:

```console
$ BUNDLE_GEMFILE=../c_glib/Gemfile bundle exec ../c_glib/test/run-test.sh
```

We may need to improve `test/run-test.sh` for macOS and rbenv:

```diff
diff --git a/c_glib/test/run-test.sh b/c_glib/test/run-test.sh
index 33e9fbf85d..afa8aed4ed 100755
--- a/c_glib/test/run-test.sh
+++ b/c_glib/test/run-test.sh
@@ -34,14 +34,14 @@ for module in "${modules[@]}"; do
   module_build_dir="${build_dir}/${module}"
   if [ -d "${module_build_dir}" ]; then
     LD_LIBRARY_PATH="${module_build_dir}:${LD_LIBRARY_PATH}"
+    DYLD_LIBRARY_PATH="${module_build_dir}:${DYLD_LIBRARY_PATH}"
   fi
 done
 export LD_LIBRARY_PATH
+export DYLD_LIBRARY_PATH
 
 if [ "${BUILD}" != "no" ]; then
-  if [ -f "Makefile" ]; then
-    make -j8 > /dev/null || exit $?
-  elif [ -f "build.ninja" ]; then
+  if [ -f "build.ninja" ]; then
     ninja || exit $?
   fi
 fi
@@ -59,4 +59,9 @@ for module in "${modules[@]}"; do
 done
 export GI_TYPELIB_PATH
 
-${GDB} ruby ${test_dir}/run-test.rb "$@"
+if type rbenv > /dev/null 2>&1; then
+  RUBY="$(rbenv which ruby)"
+else
+  RUBY=ruby
+fi
+${GDB} "${RUBY}" ${test_dir}/run-test.rb "$@"
```

**Comment by llama90** [comment]
@kou Thank you for your response! 

I was able to proceed with the test execution thanks to your help.

Would it be appropriate to update the documentation and script, and then submit a PR for consideration?

**Comment by kou** [comment]
Yes, please!
