### ISSUE TITLE
[CI][JS] TypeScript: Compilation failed on yarn build for several CI jobs

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#39423]
### Describe the bug, including details regarding any error messages, version, and platform.

The following jobs:
* [verify-rc-source-js-linux-almalinux-8-amd64](https://github.com/ursacomputing/crossbow/actions/runs/7377424133/job/20071384184)
* [verify-rc-source-js-linux-conda-latest-amd64](https://github.com/ursacomputing/crossbow/actions/runs/7377424230/job/20071384702)
* [verify-rc-source-js-linux-ubuntu-20.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/7377424415/job/20071385323)
* [verify-rc-source-js-linux-ubuntu-22.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/7377424247/job/20071384573)
* [verify-rc-source-js-macos-amd64](https://github.com/ursacomputing/crossbow/actions/runs/7377424527/job/20071385858)
* [verify-rc-source-js-macos-arm64](https://github.com/ursacomputing/crossbow/actions/runs/7377424438/job/20071385745)
* [test-ubuntu-22.04-docs](https://github.com/ursacomputing/crossbow/actions/runs/7380935480/job/20078894421)

have been failing with the following error:
```
 [01:05:51] Error: Error: TypeScript: Compilation failed
    at Output.mightFinish (/arrow/js/node_modules/gulp-typescript/release/output.js:130:43)
    at Output.finish (/arrow/js/node_modules/gulp-typescript/release/output.js:122:14)
    at ProjectCompiler.inputDone (/arrow/js/node_modules/gulp-typescript/release/compiler.js:95:29)
    at CompileStream.end (/arrow/js/node_modules/gulp-typescript/release/project.js:122:31)
    at DestroyableTransform.endFn (node:internal/streams/pipeline:430:11)
    at Object.onceWrapper (node:events:631:28)
    at DestroyableTransform.emit (node:events:529:35)
    at DestroyableTransform.emit (node:domain:552:15)
    at endReadableNT (/arrow/js/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

    at formatError (/arrow/js/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:21:10)
    at Gulp.<anonymous> (/arrow/js/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:33:15)
    at Gulp.emit (node:events:529:35)
    at Gulp.emit (node:domain:489:12)
    at Object.error (/arrow/js/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/arrow/js/node_modules/now-and-later/lib/mapSeries.js:47:14)
    at f (/arrow/js/node_modules/once/once.js:25:25)
    at f (/arrow/js/node_modules/once/once.js:25:25)
    at tryCatch (/arrow/js/node_modules/bach/node_modules/async-done/index.js:24:15)
    at done (/arrow/js/node_modules/bach/node_modules/async-done/index.js:40:12)
[01:05:51] 'build:es2015:cls' errored after 28 s
[01:05:51] 'build:es2015:umd' errored after 28 s
[01:05:51] 'build:apache-arrow' errored after 28 s
[01:05:51] 'build' errored after 28 s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
It has been failing for some days and it seems it might be related to: https://github.com/apache/arrow/issues/39251

### Component(s)

Continuous Integration, JavaScript

**Comment by raulcd** [comment]
cc @domoritz

**Comment by domoritz** [comment]
Fixed with https://github.com/apache/arrow/pull/39256/commits/9885d72eb3e676b1d87b1896db3c907b6d955305
