### ISSUE TITLE
[Ruby] ChunkedArray raises an error in Ractor block

### ISSUE THREAD

**Issue by KitaitiMakoto** [apache/arrow#39488]
### Describe the bug, including details regarding any error messages, version, and platform.

From https://github.com/red-data-tools/red_amber/issues/289

When you access `ChunkedArray`'s elements in Ractor block, it raises an error:

```ruby
array = Arrow::Array.new([1, 2, 3])
chunked_array = Arrow::ChunkedArray.new([array])
Ractor.make_shareable(chunked_array)
ractor = Ractor.new {
  ca = Ractor.receive
  ca[0]
}
ractor.send(chunked_array)
ractor.take
```

```
#<Thread:0x0000000127354008 run> terminated with exception (report_on_exception is true):
~/src/github.com/apache/arrow/ruby/red-arrow/lib/arrow/chunked-array.rb:50:in `chunks': can't modify frozen Arrow::ChunkedArray: #<Arrow::ChunkedArray:0x1273546e8ptr=0x60000377f2a0 [ (FrozenError)
  [
    1,
    2,
    3
  ]
]>
        from ~/src/github.com/apache/arrow/ruby/red-arrow/lib/arrow/chunked-array.rb:80:in `[]'
```

I think most of

```ruby
def iv
  @iv ||= init_instance_variable
end
```

pattern occur the same problem.

### Component(s)

Ruby

**Comment by KitaitiMakoto** [comment]
Thanks!
