### ISSUE TITLE
[Ruby][CUDA] red-arrow-cuda doesn't work on windows

### ISSUE THREAD

**Issue by dsisnero** [apache/arrow#39553]
### Describe the bug, including details regarding any error messages, version, and platform.

when trying the example in the README.md file - it doesn't work because ArrowCUDA Typelib is not found.  I couldn't find a pacman package when searching pacman.

Here's the error I get

```
e:\programming\source\repos\ruby\try_arrow>more arrow_cuda_test.rb
require "arrow-cuda"

manager = ArrowCUDA::DeviceManager.new
if manager.n_devices.zero?
  raise "No GPU is found"
end

context = manager[0]
buffer = ArrowCUDA::Buffer.new(context, 128)
ArrowCUDA::BufferOutputStream.open(buffer) do |stream|
  stream.write("Hello World")
end
puts buffer.copy_to_host(0, 11) # => "Hello World"

e:\programming\source\repos\ruby\try_arrow>ruby arrow_cuda_test.rb
E:/windows/tools/ruby/Ruby33-x64/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:40:in `require': Typelib file for namespace 'ArrowCUDA' (any version) not found (GObjectIntrospection::RepositoryError::T
ypelibNotFound)
        from E:/windows/tools/ruby/Ruby33-x64/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:40:in `load'
        from E:/windows/tools/ruby/Ruby33-x64/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:25:in `load'
        from E:/windows/tools/ruby/Ruby33-x64/lib/ruby/gems/3.3.0/gems/red-arrow-cuda-14.0.2/lib/arrow-cuda/loader.rb:22:in `load'
        from E:/windows/tools/ruby/Ruby33-x64/lib/ruby/gems/3.3.0/gems/red-arrow-cuda-14.0.2/lib/arrow-cuda.rb:28:in `<module:ArrowCUDA>'
        from E:/windows/tools/ruby/Ruby33-x64/lib/ruby/gems/3.3.0/gems/red-arrow-cuda-14.0.2/lib/arrow-cuda.rb:24:in `<top (required)>'
        from <internal:E:/windows/tools/ruby/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:132:in `require'
        from <internal:E:/windows/tools/ruby/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:132:in `rescue in require'


        from <internal:E:/windows/tools/ruby/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:126:in `require'
        from arrow_cuda_test.rb:1:in `<main>'
<internal:E:/windows/tools/ruby/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require': cannot load such file -- arrow-cuda (LoadError)
        from <internal:E:/windows/tools/ruby/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
        from arrow_cuda_test.rb:1:in `<main>'
```

### Component(s)

Ruby

**Comment by kou** [comment]
RubyInstaller for Windows is based on MinGW but CUDA doesn't support MinGW.
So we can't use red-arrow-cuda on Windows.
