### ISSUE TITLE
string created by strftime can't be parsed by strptime

### ISSUE THREAD

**Issue by rohanjain101** [apache/arrow#40170]
### Describe the bug, including details regarding any error messages, version, and platform.

>>> pa.compute.strftime(pd.Timestamp.utcnow(), "%Y-%m-%d %z")
<pyarrow.StringScalar: '2024-02-21 +0000'>
>>> pa.compute.strptime('2024-02-21 +0000', "%Y-%m-%d %z", "ns")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\pd_dev_1208\Lib\site-packages\pyarrow\compute.py", line 263, in wrapper
    return func.call(args, options, memory_pool)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow\_compute.pyx", line 385, in pyarrow._compute.Function.call
  File "pyarrow\error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Failed to parse string: '2024-02-21 +0000' as a scalar of type timestamp[ns]
>>>

### Component(s)

C++, Python

**Comment by jorisvandenbossche** [comment]
Which version of pyarrow are you using? For me, using the latest dev version, this seems to work fine:

```
In [8]: pa.compute.strftime(pd.Timestamp.utcnow(), "%Y-%m-%d %z")
Out[8]: <pyarrow.StringScalar: '2024-02-27 +0000'>

In [9]: pa.compute.strptime('2024-02-21 +0000', "%Y-%m-%d %z", "ns")
Out[9]: <pyarrow.TimestampScalar: '2024-02-21T00:00:00.000000000+0000'>
```

**Comment by jorisvandenbossche** [comment]
Ah, and potentially the platform is more relevant information. I suppose you are using Windows (from the file paths)?

For Windows, we have a vendored implementation for strptime, while for unix we use the system's one, I think

**Comment by rohanjain101** [comment]
Yes windows.
