### ISSUE TITLE
[Java] JDBC driver throws error based on SqlInfo values

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow#40249]
### Describe the bug, including details regarding any error messages, version, and platform.

```
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "sqlInfoList" is null
	at org.apache.arrow.driver.jdbc.ArrowDatabaseMetadata.convertListSqlInfoToString(ArrowDatabaseMetadata.java:757)
	at org.apache.arrow.driver.jdbc.ArrowDatabaseMetadata.getSQLKeywords(ArrowDatabaseMetadata.java:199)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getSQLKeywords(JDBCDatabaseMetaDataImpl.java:452)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCSQLDialect.loadDriverKeywords(JDBCSQLDialect.java:384)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCSQLDialect.initDriverSettings(JDBCSQLDialect.java:223)
	at org.jkiss.dbeaver.ext.generic.model.GenericSQLDialect.initDriverSettings(GenericSQLDialect.java:72)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initialize(JDBCDataSource.java:484)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.initialize(GenericDataSource.java:468)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1322)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect0(DataSourceDescriptor.java:1163)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:960)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:77)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

This was with DBeaver. I'm guessing that this SqlInfo value isn't provided and the driver isn't checking for null before manipulating the value

### Component(s)

FlightRPC, Java

**Comment by normanj-bitquill** [comment]
@lidavidm Which database server was this tested against?

**Comment by lidavidm** [comment]
Ah, sorry - this was something proprietary I was giving a shot so I don't think there's a public download I can point to.

**Comment by lidavidm** [comment]
Issue resolved by pull request 40988
https://github.com/apache/arrow/pull/40988
