### ISSUE TITLE
Creating an array from a null list scalar fails

### ISSUE THREAD

**Issue by vyasr** [apache/arrow#40319]
### Describe the bug, including details regarding any error messages, version, and platform.

Currently pyarrow fails to construct an array from a null list scalar:
```
>>> import pyarrow as pa
>>> pa.__version__
'15.0.0'
>>> pa.array([pa.scalar(None, pa.list_(pa.int64()))])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/array.pxi", line 344, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 42, in pyarrow.lib._sequence_to_array
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/types.pxi", line 88, in pyarrow.lib._datatype_to_pep3118
  File "pyarrow/scalar.pxi", line 685, in pyarrow.lib.ListScalar.__len__
TypeError: object of type 'NoneType' has no len()
```

This may be worked around by directly constructing the array and specifying the type when this case is detected:
```
>>> pa.array([None], type=pa.list_(pa.int64()))
<pyarrow.lib.ListArray object at 0x7f1d8e37f160>
[
  null
]
```

### Component(s)

Python

**Comment by AlenkaF** [comment]
Thanks for reporting @vyasr!

I am actually getting a segfault when running the code locally. Unfortunately lldb is not giving me much extra information than this:

```python
```

```
/Users/alenkafrim/repos/arrow/python/pyarrow/src/arrow/python/python_to_arrow.cc:532:  Check failed: (size) >= (offset) 
```

https://github.com/apache/arrow/blob/ee1a8c39a55f3543a82fed900dadca791f6e9f88/python/pyarrow/src/arrow/python/python_to_arrow.cc#L532
