### ISSUE TITLE
[Java] jdbc driver forcing connection to /0.0.0.0:32010

### ISSUE THREAD

**Issue by sammehdevel** [apache/arrow#40369]
### Describe the bug, including details regarding any error messages, version, and platform.

flight-sql-jdbc-driver: 15.0.0
spring-boot: 3.2.3
java: 17
kotlin: 1.9.22

I'm using spring boot as the application layer connecting to dremio that is running on kubernetes, which is exposing port 32120 for flight. However when I try to connect it returns an exception saying Connection refused: /0.0.0.0:32010. If I change the port to localhost:12345, for example, it tries to connect to localhost:12345 (fails because nothing is running there), but the error message is `Connection refused: localhost/127.0.0.1:12345`.

If I forward the kubernetes port to 32010 everything works fine (I can query the databases and get data back). But if I forward to any other port, or try to connect to the NodePort, the driver looks like it's trying to connect to 0.0.0.0:32010 based on the error message  `Connection refused: /0.0.0.0:32010`. 

This is my spring boot configuration 
```
spring:
  datasource:
    url: jdbc:arrow-flight-sql://kw-01:32120/?useEncryption=false
    username: ***
    password: ***
    driver-class-name: org.apache.arrow.driver.jdbc.ArrowFlightJdbcDriver
```

And a stacktrace
```
Caused by: java.sql.SQLException: exception while executing query: cfjd.org.apache.arrow.flight.FlightRuntimeException: UNAVAILABLE: io exception
	at cfjd.org.apache.calcite.avatica.Helper.createException(Helper.java:56) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.org.apache.calcite.avatica.Helper.createException(Helper.java:41) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.org.apache.calcite.avatica.AvaticaConnection.executeQueryInternal(AvaticaConnection.java:579) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.org.apache.calcite.avatica.AvaticaPreparedStatement.execute(AvaticaPreparedStatement.java:239) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-5.0.1.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-5.0.1.jar:na]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219) ~[jooq-3.19.5.jar:na]
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4883) ~[jooq-3.19.5.jar:na]
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:236) ~[jooq-3.19.5.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:348) ~[jooq-3.19.5.jar:na]
	... 42 common frames omitted
Caused by: java.lang.RuntimeException: cfjd.org.apache.arrow.flight.FlightRuntimeException: UNAVAILABLE: io exception
	at cfjd.org.apache.calcite.avatica.Helper.wrap(Helper.java:37) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at org.apache.arrow.driver.jdbc.utils.FlightEndpointDataQueue.next(FlightEndpointDataQueue.java:112) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at org.apache.arrow.driver.jdbc.utils.FlightEndpointDataQueue.next(FlightEndpointDataQueue.java:148) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at org.apache.arrow.driver.jdbc.ArrowFlightJdbcFlightStreamResultSet.getNextEndpointStream(ArrowFlightJdbcFlightStreamResultSet.java:260) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at org.apache.arrow.driver.jdbc.ArrowFlightJdbcFlightStreamResultSet.loadNewFlightStream(ArrowFlightJdbcFlightStreamResultSet.java:131) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at org.apache.arrow.driver.jdbc.ArrowFlightJdbcFlightStreamResultSet.populateData(ArrowFlightJdbcFlightStreamResultSet.java:146) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at org.apache.arrow.driver.jdbc.ArrowFlightJdbcFlightStreamResultSet.execute(ArrowFlightJdbcFlightStreamResultSet.java:138) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.org.apache.calcite.avatica.AvaticaConnection.executeQueryInternal(AvaticaConnection.java:575) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	... 49 common frames omitted
Caused by: java.util.concurrent.ExecutionException: cfjd.org.apache.arrow.flight.FlightRuntimeException: UNAVAILABLE: io exception
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[na:na]
	at org.apache.arrow.driver.jdbc.utils.FlightEndpointDataQueue.next(FlightEndpointDataQueue.java:106) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	... 55 common frames omitted
Caused by: cfjd.org.apache.arrow.flight.FlightRuntimeException: io exception
	at cfjd.org.apache.arrow.flight.CallStatus.toRuntimeException(CallStatus.java:131) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.org.apache.arrow.flight.grpc.StatusUtils.fromGrpcRuntimeException(StatusUtils.java:164) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.org.apache.arrow.flight.grpc.StatusUtils.fromThrowable(StatusUtils.java:185) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.org.apache.arrow.flight.FlightStream$Observer.onError(FlightStream.java:456) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.org.apache.arrow.flight.FlightClient$1.onError(FlightClient.java:350) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.org.apache.arrow.flight.grpc.ClientInterceptorAdapter$FlightClientCallListener.onClose(ClientInterceptorAdapter.java:117) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
Caused by: cfjd.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /0.0.0.0:32010
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946) ~[na:na]
	at cfjd.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at cfjd.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[flight-sql-jdbc-driver-15.0.0.jar:15.0.0]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]```

### Component(s)

Java

**Comment by lidavidm** [comment]
Possibly related to #40336?

**Comment by lidavidm** [comment]
Actually. This is a Dremio problem, and should apparently be fixed in their next release: https://github.com/apache/arrow-adbc/issues/1559#issuecomment-1957606475

**Comment by sammehdevel** [comment]
Awesome! Good find, thank you!

**Comment by lidavidm** [comment]
I'm going to close this given it's likely a Dremio problem, but feel free to reopen if the issue persists.
