### ISSUE TITLE
Can't convert object-dtyped NumPy arrays containing np.datetime64 objects to Arrow

### ISSUE THREAD

**Issue by Wainberg** [apache/arrow#40580]
### Describe the bug, including details regarding any error messages, version, and platform.

```python
>>> pa.array(np.array([np.datetime64('2024-01-01')]))  # works
<pyarrow.lib.Date32Array object at 0x7f60596d2140>
[
  2024-01-01
]
>>> pa.array(np.array([np.timedelta64(1, 'ns')], dtype=object))  # works
<pyarrow.lib.DurationArray object at 0x7f60596d2500>
[
  1
]
>>> pa.array(np.array([np.datetime64('2024-01-01')], dtype=object))  # fails
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/array.pxi", line 340, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 86, in pyarrow.lib._ndarray_to_array
  File "pyarrow/types.pxi", line 88, in pyarrow.lib._datatype_to_pep3118
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'datetime.date'
```

### Component(s)

Python

**Comment by rchowell** [comment]
Hello 👋  are there any suggested workarounds here?

```python
import numpy as np
import pyarrow as pa

data = [np.datetime64(datetime.now(), "D") for _ in range(10)]
pa.array(data) # cannot create a pyarrow array
```

```text
Traceback (most recent call last):
  File "/Users/rch/Projects/Punq/scripts/test_numpy_datetime64.py", line 16, in <module>
    pa.array(data)
  File "pyarrow/array.pxi", line 355, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 42, in pyarrow.lib._sequence_to_array
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 88, in pyarrow.lib.check_status
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'datetime.date' 
```
