### ISSUE TITLE
[Release][Packaging] Updating homebrew formula for Arrow 15.0.2 fails

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#40663]
### Describe the bug, including details regarding any error messages, version, and platform.

I have been trying to update the homebrew-core Formula for Arrow 15.0.2 both with linxubrew and macOS brew using:
```
dev/release/post-13-homebrew.sh 15.0.2 raulcd
```
both OS fail with the following error:
```
Your branch is behind 'origin/master' by 3 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
error: branch 'apache-arrow-15.0.2' not found
Switched to a new branch 'apache-arrow-15.0.2'
Updating apache-arrow formulae
Warning: bump-formula-pr is a developer command, so Homebrew's
developer mode has been automatically turned on.
To turn developer mode off, run:
  brew developer off

Error: Parameter 'version': Expected type T.nilable(String), got type Version with value #<Version:0x0000000107fe472...0.2", @detected_from_url=true>
Caller: /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/call_validation.rb:133
Definition: /opt/homebrew/Library/Homebrew/utils/github.rb:523
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/configuration.rb:296:in `call_validation_error_handler_default'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/configuration.rb:303:in `call_validation_error_handler'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/call_validation.rb:300:in `report_error'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/call_validation.rb:136:in `block in validate_call_skip_block_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/signature.rb:234:in `block in each_args_value_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/signature.rb:228:in `each'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/signature.rb:228:in `each_args_value_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/call_validation.rb:133:in `validate_call_skip_block_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11294/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
/opt/homebrew/Library/Homebrew/utils/github.rb:628:in `check_for_duplicate_pull_requests'
/opt/homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:474:in `check_closed_pull_requests'
/opt/homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:459:in `check_new_version'
/opt/homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:164:in `bump_formula_pr'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

### Component(s)

Packaging, Release

**Comment by kou** [comment]
This was happen by https://github.com/apache/arrow/blob/ed47ad22c8537b32abf27580e75fcf514be11f7e/dev/release/post-13-homebrew.sh#L50-L57
right?

It seems that this is a bug of https://github.com/Homebrew/brew .
Could you report this to the upstream?

I think that this is needed:

```diff
diff --git a/Library/Homebrew/dev-cmd/bump-formula-pr.rb b/Library/Homebrew/dev-cmd/bump-formula-pr.rb
index 4ed5dbb345..e3c853eb1b 100644
--- a/Library/Homebrew/dev-cmd/bump-formula-pr.rb
+++ b/Library/Homebrew/dev-cmd/bump-formula-pr.rb
@@ -464,6 +464,7 @@ module Homebrew
       specs[:tag] = tag if tag.present?
       version = Version.detect(url, **specs)
       return if version.null?
+      version = version.to_s
     end
 
     check_throttle(formula, version)
```

**Comment by raulcd** [comment]
> It seems that this is a bug of https://github.com/Homebrew/brew . Could you report this to the upstream?

Thanks @kou ! Reported to brew.

**Comment by kou** [comment]
This has been fixed in upstream: https://github.com/Homebrew/brew/pull/16920

I think that we can close this.

**Comment by raulcd** [comment]
Indeed we can. Thanks!
