### ISSUE TITLE
[Python] bool followed by float disallowed, but float followed by bool allowed

### ISSUE THREAD

**Issue by Wainberg** [apache/arrow#40909]
### Describe the bug, including details regarding any error messages, version, and platform.

```python
>>> pa.array([True, 1.0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/array.pxi", line 344, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 42, in pyarrow.lib._sequence_to_array
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not convert 1.0 with type float: tried to convert to boolean
>>> pa.array([1.0, True])
<pyarrow.lib.DoubleArray object at 0x7f1d84b3c220>
[
  1,
  1
]
```

### Component(s)

Python

**Comment by Wainberg** [comment]
Another example, with `datetime.time` and `int`:

```python
>>> import datetime, pyarrow as pa
>>> pa.array([1, datetime.time(1, 2, 3)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/array.pxi", line 344, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 42, in pyarrow.lib._sequence_to_array
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not convert datetime.time(1, 2, 3) with type datetime.time: tried to convert to int64
>>> pa.array([datetime.time(1, 2, 3), 1])
<pyarrow.lib.Time64Array object at 0x7fba60c40040>
[
  01:02:03.000000,
  00:00:00.000001
]
```

**Comment by Wainberg** [comment]
A third example with `datetime.timedelta` and `int`, similar to the second:

```python
>>> pa.array([1, datetime.timedelta(1)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/array.pxi", line 344, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 42, in pyarrow.lib._sequence_to_array
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not convert datetime.timedelta(days=1) with type datetime.timedelta: tried to convert to int64
>>> pa.array([datetime.timedelta(1), 1])
<pyarrow.lib.DurationArray object at 0x7fb5dd50c0a0>
[
  86400000000,
  1
]
```

**Comment by Wainberg** [comment]
A fourth example with `pd.Timestamp` and `int`:

```python
>>> pa.array([1, pd.Timestamp('2024-01-01')])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/array.pxi", line 344, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 42, in pyarrow.lib._sequence_to_array
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not convert Timestamp('2024-01-01 00:00:00') with type Timestamp: tried to convert to int64
>>> pa.array([pd.Timestamp('2024-01-01'), 1])
<pyarrow.lib.TimestampArray object at 0x7f0ad675c220>
[
  2024-01-01 00:00:00.000000,
  1970-01-01 00:00:00.000001
]
```

**Comment by Wainberg** [comment]
A fifth example with `datetime.date` and `int`:

```python
>>> pa.array(np.array([datetime.date(2021, 2, 3), 1], dtype=object))
<pyarrow.lib.Date32Array object at 0x7f18ca307e20>
[
  2021-02-03,
  1970-01-02
]
>>> pa.array(np.array([1, datetime.date(2021, 2, 3)], dtype=object))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/array.pxi", line 340, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 86, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not convert datetime.date(2021, 2, 3) with type datetime.date: tried to convert to int64
```
