### ISSUE TITLE
[C++][Acero] arrow-acero-hash-join-benchmark failed as `Invalid: Could not parse min_length =  as int32`

### ISSUE THREAD

**Issue by ZhangHuiGui** [apache/arrow#41192]
### Describe the bug, including details regarding any error messages, version, and platform.
Commit: `2979d69a05cb16012da06baaa801a1849e9110ce`

Compile commands:
```shell
cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DARROW_DATASET=ON -DARROW_COMPUTE=ON -DARROW_FILESYSTEM=ON -DARROW_JEMALLOC=OFF -DARROW_ORC=OFF -DARROW_PARQUET=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DARROW_BUILD_EXAMPLES=ON -DARROW_TESTING=ON -DARROW_BUILD_TESTS=ON -DARROW_CSV=ON -DARROW_BUILD_BENCHMARKS=ON -DARROW_FLIGHT=ON -DARROW_WITH_RE2=OFF -DARROW_WITH_SNAPPY=ON -DARROW_WITH_ZLIB=ON -DARROW_WITH_BROTLI=ON -DARROW_WITH_LZ4=ON -DARROW_WITH_ZSTD=ON -DARROW_WITH_BZ2=ON -DARROW_BUILD_OPENMP_BENCHMARKS=ON -DARROW_BUILD_DETAILED_BENCHMARKS=ON -DARROW_USE_ASAN=OFF -DARROW_RUNTIME_SIMD_LEVEL=SSE4_2 -DARROW_GANDIVA=OFF -DARROW_LLVM_USE_SHARED=OFF -DARROW_TEST_LINKAGE=shared -DARROW_BUILD_SHARED=ON -DARROW_S3=OFF ..
```

Running:
```shell
Running ./arrow-acero-hash-join-benchmark
Run on (16 X 3800 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x8)
  L1 Instruction 32 KiB (x8)
  L2 Unified 512 KiB (x8)
  L3 Unified 16384 KiB (x1)
Load Average: 7.65, 4.20, 3.09
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
***WARNING*** Library was built as DEBUG. Timings may be affected.
------------------------------------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                                            Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------------------------------------------------------------------------
BM_HashJoinBasic_KeyTypes/"{int32}"/Hashtable krows:1                                           741319 ns       740551 ns          926 rows/sec=1.38275M/s
BM_HashJoinBasic_KeyTypes/"{int32}"/Hashtable krows:8                                          4053200 ns      4051357 ns          171 rows/sec=2.02204M/s
BM_HashJoinBasic_KeyTypes/"{int32}"/Hashtable krows:64                                        33427451 ns     33415561 ns           21 rows/sec=1.96124M/s
BM_HashJoinBasic_KeyTypes/"{int32}"/Hashtable krows:512                                      304921057 ns    304822896 ns            2 rows/sec=1.71998M/s
BM_HashJoinBasic_KeyTypes/"{int32}"/Hashtable krows:4096                                    4471338567 ns   4469941888 ns            1 rows/sec=938.335k/s
BM_HashJoinBasic_KeyTypes/"{int64}"/Hashtable krows:1                                           742460 ns       741613 ns          943 rows/sec=1.38077M/s
BM_HashJoinBasic_KeyTypes/"{int64}"/Hashtable krows:8                                          4081464 ns      4079319 ns          171 rows/sec=2.00818M/s
BM_HashJoinBasic_KeyTypes/"{int64}"/Hashtable krows:64                                        33114487 ns     33103380 ns           21 rows/sec=1.97974M/s
BM_HashJoinBasic_KeyTypes/"{int64}"/Hashtable krows:512                                      309871525 ns    309769316 ns            2 rows/sec=1.69251M/s
BM_HashJoinBasic_KeyTypes/"{int64}"/Hashtable krows:4096                                    4481584541 ns   4480181500 ns            1 rows/sec=936.191k/s
BM_HashJoinBasic_KeyTypes/"{int64,int64}"/Hashtable krows:1                                     880640 ns       879821 ns          795 rows/sec=1.16387M/s
BM_HashJoinBasic_KeyTypes/"{int64,int64}"/Hashtable krows:8                                    5331551 ns      5328812 ns          132 rows/sec=1.5373M/s
BM_HashJoinBasic_KeyTypes/"{int64,int64}"/Hashtable krows:64                                  42990125 ns     42977066 ns           16 rows/sec=1.52491M/s
BM_HashJoinBasic_KeyTypes/"{int64,int64}"/Hashtable krows:512                                400343994 ns    400216210 ns            2 rows/sec=1.31001M/s
BM_HashJoinBasic_KeyTypes/"{int64,int64}"/Hashtable krows:4096                              6265385854 ns   6263386372 ns            1 rows/sec=669.654k/s
BM_HashJoinBasic_KeyTypes/"{int64,int64,int64}"/Hashtable krows:1                              1017818 ns      1016935 ns          670 rows/sec=1.00695M/s
BM_HashJoinBasic_KeyTypes/"{int64,int64,int64}"/Hashtable krows:8                              6278081 ns      6275648 ns          112 rows/sec=1.30536M/s
BM_HashJoinBasic_KeyTypes/"{int64,int64,int64}"/Hashtable krows:64                            50684575 ns     50667780 ns           14 rows/sec=1.29345M/s
BM_HashJoinBasic_KeyTypes/"{int64,int64,int64}"/Hashtable krows:512                          484605371 ns    484463627 ns            2 rows/sec=1.0822M/s
BM_HashJoinBasic_KeyTypes/"{int64,int64,int64}"/Hashtable krows:4096                        8015027843 ns   8012462282 ns            1 rows/sec=523.473k/s
BM_HashJoinBasic_KeyTypes/"{int64,int64,int64,int64}"/Hashtable krows:1                        1152636 ns      1151683 ns          611 rows/sec=889.133k/s
BM_HashJoinBasic_KeyTypes/"{int64,int64,int64,int64}"/Hashtable krows:8                        7197834 ns      7195007 ns           98 rows/sec=1.13857M/s
BM_HashJoinBasic_KeyTypes/"{int64,int64,int64,int64}"/Hashtable krows:64                      58147903 ns     58126441 ns           12 rows/sec=1.12747M/s
BM_HashJoinBasic_KeyTypes/"{int64,int64,int64,int64}"/Hashtable krows:512                    559542032 ns    559376903 ns            1 rows/sec=937.271k/s
BM_HashJoinBasic_KeyTypes/"{int64,int64,int64,int64}"/Hashtable krows:4096                  9729219964 ns   9726215230 ns            1 rows/sec=431.237k/s
-- Arrow Fatal Error --
Invalid: Could not parse min_length =  as int32
[1]    394552 abort (core dumped)  ./arrow-acero-hash-join-benchmark
```

Crashed stack:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fd354181859 in __GI_abort () at abort.c:79
#2  0x00007fd35602a13f in arrow::Status::Abort (this=0x7ffd45788bf8, message="") at /home/gpadmin/pie-db/arrow/cpp/src/arrow/status.cc:149
#3  0x00007fd35602a05f in arrow::Status::Abort (this=0x7ffd45788bf8) at /home/gpadmin/pie-db/arrow/cpp/src/arrow/status.cc:141
#4  0x00007fd358916d01 in arrow::random::(anonymous namespace)::GetMetadata<int> (metadata=0x557884974460, key="min_length", default_value=0) at /home/gpadmin/pie-db/arrow/cpp/src/arrow/testing/random.cc:625
#5  0x00007fd358907f8a in arrow::random::RandomArrayGenerator::ArrayOf (this=0x7ffd45789060, field=..., length=1024, alignment=64, memory_pool=0x0)
    at /home/gpadmin/pie-db/arrow/cpp/src/arrow/testing/random.cc:1048
#6  0x00007fd35890e80c in arrow::random::RandomArrayGenerator::BatchOf (this=0x7ffd45789060, fields=std::vector of length 1, capacity 1 = {...}, length=1024, alignment=64, memory_pool=0x0)
    at /home/gpadmin/pie-db/arrow/cpp/src/arrow/testing/random.cc:1300
#7  0x000055788211cf43 in arrow::acero::MakeRandomBatches (schema=std::shared_ptr<class arrow::Schema> (use count 1, weak count 0) = {...}, num_batches=1, batch_size=1024, alignment=64, memory_pool=0x0)
    at /home/gpadmin/pie-db/arrow/cpp/src/arrow/acero/test_util_internal.cc:372
#8  0x0000557882161993 in arrow::acero::JoinBenchmark::JoinBenchmark (this=0x7ffd45789420, settings=...) at /home/gpadmin/pie-db/arrow/cpp/src/arrow/acero/hash_join_benchmark.cc:123
#9  0x0000557882155492 in arrow::acero::HashJoinBasicBenchmarkImpl (st=..., settings=...) at /home/gpadmin/pie-db/arrow/cpp/src/arrow/acero/hash_join_benchmark.cc:217
#10 0x0000557882158b55 in arrow::acero::BM_HashJoinBasic_KeyTypes<>(benchmark::State &, std::vector<std::shared_ptr<arrow::DataType>, std::allocator<std::shared_ptr<arrow::DataType> > >) (st=...,
    key_types=std::vector of length 0, capacity 0) at /home/gpadmin/pie-db/arrow/cpp/src/arrow/acero/hash_join_benchmark.cc:237
#11 0x00005578821567fc in arrow::acero::<lambda(benchmark::State&)>::operator()(benchmark::State &) const (__closure=0x0, st=...) at /home/gpadmin/pie-db/arrow/cpp/src/arrow/acero/hash_join_benchmark.cc:391
#12 0x00005578821568c9 in arrow::acero::<lambda(benchmark::State&)>::_FUN(benchmark::State &) () at /home/gpadmin/pie-db/arrow/cpp/src/arrow/acero/hash_join_benchmark.cc:391
#13 0x0000557882300398 in benchmark::internal::FunctionBenchmark::Run (this=0x5578825dad00, st=...) at /home/gpadmin/pie-db/benchmark/src/benchmark_register.cc:497
#14 0x000055788235530b in benchmark::internal::BenchmarkInstance::Run (this=0x7fd353ea8978, iters=1, thread_id=0, timer=0x7ffd45789890, manager=0x557882609f50, perf_counters_measurement=0x7ffd4578a020)
    at /home/gpadmin/pie-db/benchmark/src/benchmark_api_internal.cc:98
#15 0x0000557882332cae in benchmark::internal::(anonymous namespace)::RunInThread (b=0x7fd353ea8978, iters=1, thread_id=0, manager=0x557882609f50, perf_counters_measurement=0x7ffd4578a020)
    at /home/gpadmin/pie-db/benchmark/src/benchmark_runner.cc:132
#16 0x0000557882333a12 in benchmark::internal::BenchmarkRunner::DoNIterations (this=0x557882612cc8) at /home/gpadmin/pie-db/benchmark/src/benchmark_runner.cc:273
#17 0x0000557882334352 in benchmark::internal::BenchmarkRunner::DoOneRepetition (this=0x557882612cc8) at /home/gpadmin/pie-db/benchmark/src/benchmark_runner.cc:424
#18 0x00005578822ecdf8 in benchmark::internal::(anonymous namespace)::RunBenchmarks (benchmarks=std::vector of length 881, capacity 881 = {...}, display_reporter=0x5578825db070, file_reporter=0x0)
    at /home/gpadmin/pie-db/benchmark/src/benchmark.cc:438
#19 0x00005578822edce1 in benchmark::RunSpecifiedBenchmarks (display_reporter=0x5578825db070, file_reporter=0x0, spec=".") at /home/gpadmin/pie-db/benchmark/src/benchmark.cc:611
#20 0x00005578822ed5a4 in benchmark::RunSpecifiedBenchmarks () at /home/gpadmin/pie-db/benchmark/src/benchmark.cc:535
#21 0x000055788216f3c2 in main (argc=1, argv=0x7ffd4578ce48) at /home/gpadmin/pie-db/benchmark/src/benchmark_main.cc:18
```

### Component(s)

C++

**Comment by mapleFU** [comment]
Issue resolved by pull request 41195
https://github.com/apache/arrow/pull/41195
