### ISSUE TITLE
[CI][Release] "archery docker push" is failed in verify-rc-source-*-conda-* jobs

### ISSUE THREAD

**Issue by kou** [apache/arrow#41467]
### Describe the bug, including details regarding any error messages, version, and platform.

For example: verify-rc-source-cpp-linux-conda-latest-amd64

https://github.com/ursacomputing/crossbow/actions/runs/8878831811/job/24375255016#step:8:47

```text
DEBUG:archery:Executing `['docker', 'push', 'ubuntu:20.04']`
The push refers to repository [docker.io/library/ubuntu]
e915d510ff2b: Preparing
e915d510ff2b: Layer already exists
errors:
denied: requested access to the resource is denied
unauthorized: authentication required

Traceback (most recent call last):
  File "/home/runner/work/crossbow/crossbow/arrow/dev/archery/archery/docker/core.py", line 224, in _execute_docker
    result = Docker().run(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/crossbow/crossbow/arrow/dev/archery/archery/utils/command.py", line 78, in run
    return subprocess.run(invocation, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'push', 'ubuntu:20.04']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.3/x64/bin/archery", line 8, in <module>
    sys.exit(archery())
             ^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/crossbow/crossbow/arrow/dev/archery/archery/docker/cli.py", line 259, in docker_compose_push
    compose.push(image, user=user, ***
  File "/home/runner/work/crossbow/crossbow/arrow/dev/archery/archery/docker/core.py", line 440, in push
    _push(service)
  File "/home/runner/work/crossbow/crossbow/arrow/dev/archery/archery/docker/core.py", line 423, in _push
    return self._execute_docker('push', service['image'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/crossbow/crossbow/arrow/dev/archery/archery/docker/core.py", line 227, in _execute_docker
    raise RuntimeError(
RuntimeError: docker push ubuntu:20.04 exited with non-zero exit code 1
```

### Component(s)

Continuous Integration, Release

**Comment by kou** [comment]
Issue resolved by pull request 41468
https://github.com/apache/arrow/pull/41468
