### ISSUE TITLE
[CI] Installing the newer version of Azurite is failing

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#41505]
### Describe the bug, including details regarding any error messages, version, and platform.

Related to #41462 

While investigating I found that the failure on the arrow-azurefs-test was due to failing connecting to Azurite
```
[ RUN      ] TestAzuriteGeneric.Empty
/usr/local/lib/node_modules/azurite/dist/src/common/persistence/MemoryExtentStore.js:53
        return this._chunks.get(categoryName)?.chunks.get(id);
                                              ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/azurite/dist/src/common/ConfigurationBase.js:7:29)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
unknown file: Failure
C++ exception with description "Fail to get a new connection for: http://127.0.0.1:10000. Couldn't connect to server" thrown in SetUp().
unknown file: Failure
C++ exception with description "Fail to get a new connection for: http://127.0.0.1:10000. Couldn't connect to server" thrown in TearDown().
[  FAILED  ] TestAzuriteGeneric.Empty (12243 ms)
[ RUN      ] TestAzuriteGeneric.NormalizePath
unknown file: Failure
C++ exception with description "Fail to get a new connection for: http://127.0.0.1:10000. Couldn't connect to server" thrown in SetUp().
unknown file: Failure
C++ exception with description "Fail to get a new connection for: http://127.0.0.1:10000. Couldn't connect to server" thrown in TearDown().
[  FAILED  ] TestAzuriteGeneric.NormalizePath (11768 ms)
```
This is because the newer azurite 3.30.0 is failing to get installed:
```
#19 [13/15] RUN /arrow/ci/scripts/install_azurite.sh
... (a bunch of NPM warnings)
#19 9.320 added 307 packages, and audited 308 packages in 9s
#19 9.320 
#19 9.320 65 packages are looking for funding
#19 9.320   run `npm fund` for details
#19 9.324 
#19 9.324 4 moderate severity vulnerabilities
#19 9.324 
#19 9.324 To address all issues (including breaking changes), run:
#19 9.324   npm audit fix --force
#19 9.324 
#19 9.324 Run `npm audit` for details.
#19 9.348 /usr/local/bin/azurite
#19 9.364 node version = v12.22.9
#19 9.476 /usr/local/lib/node_modules/azurite/dist/src/common/persistence/MemoryExtentStore.js:53
#19 9.476         return this._chunks.get(categoryName)?.chunks.get(id);
#19 9.476                                               ^
#19 9.476 
#19 9.476 SyntaxError: Unexpected token '.'
#19 9.476     at wrapSafe (internal/modules/cjs/loader.js:915:16)
#19 9.476     at Module._compile (internal/modules/cjs/loader.js:963:27)
#19 9.476     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
#19 9.476     at Module.load (internal/modules/cjs/loader.js:863:32)
#19 9.476     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
#19 9.476     at Module.require (internal/modules/cjs/loader.js:887:19)
#19 9.476     at require (internal/modules/cjs/helpers.js:74:18)
#19 9.476     at Object.<anonymous> (/usr/local/lib/node_modules/azurite/dist/src/common/ConfigurationBase.js:7:29)
#19 9.476     at Module._compile (internal/modules/cjs/loader.js:999:30)
#19 9.476     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
#19 9.479 azurite version = 
#19 DONE 9.7s
```
This started failing when Azurite v3.30.0 was released: https://github.com/Azure/Azurite/releases/tag/v3.30.0

Two things have to be done here.

- Being able to use the latest version of azurite
- The job should fail if it fails to install instead of continuing and just timing out on tests

### Component(s)

Continuous Integration

**Comment by kou** [comment]
Ah, `#19 9.364 node version = v12.22.9` may be related.
How about enabling AzureFileSystem only on Ubuntu 24.04 that ships [Node.js 18.19](https://packages.ubuntu.com/search?keywords=nodejs)?

```diff
diff --git a/ci/docker/ubuntu-22.04-cpp.dockerfile b/ci/docker/ubuntu-22.04-cpp.dockerfile
index eb189841cd..0101f84881 100644
--- a/ci/docker/ubuntu-22.04-cpp.dockerfile
+++ b/ci/docker/ubuntu-22.04-cpp.dockerfile
@@ -184,7 +184,7 @@ RUN /arrow/ci/scripts/install_sccache.sh unknown-linux-musl /usr/local/bin
 # - libc-ares-dev does not install CMake config files
 ENV absl_SOURCE=BUNDLED \
     ARROW_ACERO=ON \
-    ARROW_AZURE=ON \
+    ARROW_AZURE=OFF \
     ARROW_BUILD_STATIC=ON \
     ARROW_BUILD_TESTS=ON \
     ARROW_DEPENDENCY_SOURCE=SYSTEM \
```

**Comment by kou** [comment]
Ah, we also need to remove `install_azurite.sh`:

```diff
diff --git a/ci/docker/ubuntu-20.04-cpp.dockerfile b/ci/docker/ubuntu-20.04-cpp.dockerfile
index 124256378b..135f67dbc5 100644
--- a/ci/docker/ubuntu-20.04-cpp.dockerfile
+++ b/ci/docker/ubuntu-20.04-cpp.dockerfile
@@ -126,9 +126,6 @@ RUN /arrow/ci/scripts/install_minio.sh latest /usr/local
 COPY ci/scripts/install_gcs_testbench.sh /arrow/ci/scripts/
 RUN /arrow/ci/scripts/install_gcs_testbench.sh default
 
-COPY ci/scripts/install_azurite.sh /arrow/ci/scripts/
-RUN /arrow/ci/scripts/install_azurite.sh
-
 COPY ci/scripts/install_ceph.sh /arrow/ci/scripts/
 RUN /arrow/ci/scripts/install_ceph.sh
 
diff --git a/ci/docker/ubuntu-22.04-cpp.dockerfile b/ci/docker/ubuntu-22.04-cpp.dockerfile
index eb189841cd..008455f083 100644
--- a/ci/docker/ubuntu-22.04-cpp.dockerfile
+++ b/ci/docker/ubuntu-22.04-cpp.dockerfile
@@ -171,9 +171,6 @@ RUN /arrow/ci/scripts/install_minio.sh latest /usr/local
 COPY ci/scripts/install_gcs_testbench.sh /arrow/ci/scripts/
 RUN /arrow/ci/scripts/install_gcs_testbench.sh default
 
-COPY ci/scripts/install_azurite.sh /arrow/ci/scripts/
-RUN /arrow/ci/scripts/install_azurite.sh
-
 COPY ci/scripts/install_sccache.sh /arrow/ci/scripts/
 RUN /arrow/ci/scripts/install_sccache.sh unknown-linux-musl /usr/local/bin
 
@@ -184,7 +181,7 @@ RUN /arrow/ci/scripts/install_sccache.sh unknown-linux-musl /usr/local/bin
 # - libc-ares-dev does not install CMake config files
 ENV absl_SOURCE=BUNDLED \
     ARROW_ACERO=ON \
-    ARROW_AZURE=ON \
+    ARROW_AZURE=OFF \
     ARROW_BUILD_STATIC=ON \
     ARROW_BUILD_TESTS=ON \
     ARROW_DEPENDENCY_SOURCE=SYSTEM \
```

**Comment by raulcd** [comment]
We could also add an argument to install_azurite.sh to use a pinned version on non Ubuntu 22.04

**Comment by kou** [comment]
Ah, yes. It'll work too!
