### ISSUE TITLE
Unable to import apache-arrow npm package

### ISSUE THREAD

**Issue by jbthummar** [apache/arrow#4154]
When I do in app.ts file in my project `const arrow =  require("apache-arrow"); `, it throws an error saying:

```text
`node_modules/apache-arrow/io/adapters.js:87
async function* fromAsyncIterable(source) {
              ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Object.obj.(anonymous function) [as runInThisContext] (/home/jignesh/work/projects/learning/million-grid/million-grid-1-be/node_modules/ts-node-dev/lib/hook.js:30:19)
    at Module._compile (module.js:616:28)
    at Module._extensions..js (module.js:663:10)
    at Object.nodeDevHook [as .js] (/home/jignesh/work/projects/learning/million-grid/million-grid-1-be/node_modules/ts-node-dev/lib/hook.js:61:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
[ERROR] 14:16:09 SyntaxError: Unexpected token *
```

Node version :v8.10.0

Package.json
```json
{
  "name": "million-grid-1-be",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "tsc": "tsc",
    "dev": "ts-node-dev --respawn --transpileOnly ./app.ts",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@jpmorganchase/perspective": "^0.2.22",
    "@types/express": "^4.16.1",
    "apache-arrow": "^0.13.0",
    "core-js": "^2.6.5",
    "express": "^4.16.4",
    "ts-node-dev": "^1.0.0-pre.32",
    "typescript": "^3.4.3"
  }
}
```

tsConfig.json
```json
{
  "compilerOptions": {
    
    "target": "ES6",
    "module": "commonjs",
    "lib": ["ES6"],
    "outDir": "./build",

    
    "strict": true,

    "types": ["node"],
    "esModuleInterop": true

  }
}
```

**Comment by jbthummar** [comment]
I am running this using below command:
`ts-node-dev --respawn --transpileOnly ./app.ts`

**Comment by fsaintjacques** [comment]
Hello,

Apache Arrow uses [JIRA](https://issues.apache.org/jira/projects/ARROW/issues) to track issues. Could you open a ticket?

Thank you

**Comment by kou** [comment]
You can't use apache-arrow npm package with Node.js 8.10.0.
apache-arrow npm package requires Node.js 11.12 or later: https://github.com/apache/arrow/blob/master/js/package.json#L114
