### ISSUE TITLE
[PYARROW]Add pyarrow to PYTHON_PATH won't work, how can make it work?

### ISSUE THREAD

**Issue by AngersZhuuuu** [apache/arrow#41568]
### Describe the usage question you have. Please include as many useful details as  possible.

Hi arrow team, 

In our internal spark, we want to add pyarrow to spark's default python env. But we didn't want to add it to cluster's each machine's python default python env. So we follow the py4j's method.
1. Add a py4j zip file to project
<img width="426" alt="截屏2024-05-07 19 02 30" src="https://github.com/apache/arrow/assets/46485123/ce953893-f48e-4d18-9a10-e9e786fb3ce9">

2. Add this py4j zip file path to python path.
<img width="822" alt="截屏2024-05-07 19 03 59" src="https://github.com/apache/arrow/assets/46485123/bcce44fc-247c-401f-a683-de60c7edb6af">
The it can work, to do the same thing, I download 6.0.1 version pyarrow whl file and do the same thing, but it throw exception like

```
>>> import pyarrow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ldap_home/yi.zhu/spark-3.2.1-sdi-082-bin-3.3.sdi-107/python/lib/pyarrow-6.0.1-src.zip/pyarrow/__init__.py", line 63, in <module>
ModuleNotFoundError: No module named 'pyarrow.lib'
```

Seems I miss something, hope arrow team can help.

### Component(s)

Python

**Comment by thisisnic** [comment]
This issue has been marked as stale because it has had no activity in the past 365 days. Please remove the stale label or comment below, or this issue will be closed in 14 days. If this usage question has evolved into a feature request or docs update, please remove the 'Type: usage' label and add the 'Type: enhancement' label instead.
