### ISSUE TITLE
[CI][GLib] Suppress "`unlink': Permission denied" warnings in tests on Windows

### ISSUE THREAD

**Issue by kou** [apache/arrow#41770]
### Describe the enhancement requested

https://github.com/apache/arrow/actions/runs/9183539981/job/25254413025#step:12:83

```text
test/run-test.rb: warning: Exception in finalizer #<Tempfile::Remover:0x000001c1b01cf9f8 @pid=5072, @tmpfile=#<File:D:/a/_temp/data20240522-5072-8gmqb9.parquet (closed)>>
C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `unlink': Permission denied @ apply2files - D:/a/_temp/data20240522-5072-8gmqb9.parquet (Errno::EACCES)
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `call'
test/run-test.rb: warning: Exception in finalizer #<Tempfile::Remover:0x000001c1b01de598 @pid=5072, @tmpfile=#<File:D:/a/_temp/data20240522-5072-jhtj66.parquet (closed)>>
C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `unlink': Permission denied @ apply2files - D:/a/_temp/data20240522-5072-jhtj66.parquet (Errno::EACCES)
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `call'
test/run-test.rb: warning: Exception in finalizer #<Tempfile::Remover:0x000001c1b01f6d28 @pid=5072, @tmpfile=#<File:D:/a/_temp/data20240522-5072-cm213m.parquet (closed)>>
C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `unlink': Permission denied @ apply2files - D:/a/_temp/data20240522-5072-cm213m.parquet (Errno::EACCES)
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `call'
test/run-test.rb: warning: Exception in finalizer #<Tempfile::Remover:0x000001c1b022e818 @pid=5072, @tmpfile=#<File:D:/a/_temp/data20240522-5072-9f22cw.parquet (closed)>>
C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `unlink': Permission denied @ apply2files - D:/a/_temp/data20240522-5072-9f22cw.parquet (Errno::EACCES)
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `call'
test/run-test.rb: warning: Exception in finalizer #<Tempfile::Remover:0x000001c1b02b43c8 @pid=5072, @tmpfile=#<File:D:/a/_temp/data20240522-5072-l8mur.parquet (closed)>>
C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `unlink': Permission denied @ apply2files - D:/a/_temp/data20240522-5072-l8mur.parquet (Errno::EACCES)
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `call'
test/run-test.rb: warning: Exception in finalizer #<Tempfile::Remover:0x000001c1b038f6a8 @pid=5072, @tmpfile=#<File:D:/a/_temp/data20240522-5072-h2rr21.parquet (closed)>>
C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `unlink': Permission denied @ apply2files - D:/a/_temp/data20240522-5072-h2rr21.parquet (Errno::EACCES)
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `call'
test/run-test.rb: warning: Exception in finalizer #<Tempfile::Remover:0x000001c1b03ec7e0 @pid=5072, @tmpfile=#<File:D:/a/_temp/data20240522-5072-8wxgv6.parquet (closed)>>
C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `unlink': Permission denied @ apply2files - D:/a/_temp/data20240522-5072-8wxgv6.parquet (Errno::EACCES)
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `call'
test/run-test.rb: warning: Exception in finalizer #<Tempfile::Remover:0x000001c1b040ef48 @pid=5072, @tmpfile=#<File:D:/a/_temp/data20240522-5072-n5khu0.parquet (closed)>>
C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `unlink': Permission denied @ apply2files - D:/a/_temp/data20240522-5072-n5khu0.parquet (Errno::EACCES)
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `call'
test/run-test.rb: warning: Exception in finalizer #<Tempfile::Remover:0x000001c1ace305c0 @pid=5072, @tmpfile=#<File:D:/a/_temp/data20240522-5072-whjqi1.parquet (closed)>>
C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `unlink': Permission denied @ apply2files - D:/a/_temp/data20240522-5072-whjqi1.parquet (Errno::EACCES)
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `call'
test/run-test.rb: warning: Exception in finalizer #<Tempfile::Remover:0x000001c1aee7c360 @pid=5072, @tmpfile=#<File:D:/a/_temp/data20240522-5072-nigllm.parquet (closed)>>
C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `unlink': Permission denied @ apply2files - D:/a/_temp/data20240522-5072-nigllm.parquet (Errno::EACCES)
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `call'
test/run-test.rb: warning: Exception in finalizer #<Tempfile::Remover:0x000001c1afd42b38 @pid=5072, @tmpfile=#<File:D:/a/_temp/data20240522-5072-5d2aoc.parquet (closed)>>
C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `unlink': Permission denied @ apply2files - D:/a/_temp/data20240522-5072-5d2aoc.parquet (Errno::EACCES)
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `call'
test/run-test.rb: warning: Exception in finalizer #<Tempfile::Remover:0x000001c1afd74f98 @pid=5072, @tmpfile=#<File:D:/a/_temp/data20240522-5072-moorbx.parquet (closed)>>
C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `unlink': Permission denied @ apply2files - D:/a/_temp/data20240522-5072-moorbx.parquet (Errno::EACCES)
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `call'
test/run-test.rb: warning: Exception in finalizer #<Tempfile::Remover:0x000001c1afdc10a0 @pid=5072, @tmpfile=#<File:D:/a/_temp/data20240522-5072-vq6f58.parquet (closed)>>
C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `unlink': Permission denied @ apply2files - D:/a/_temp/data20240522-5072-vq6f58.parquet (Errno::EACCES)
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `call'
test/run-test.rb: warning: Exception in finalizer #<Tempfile::Remover:0x000001c1afdd83b8 @pid=5072, @tmpfile=#<File:D:/a/_temp/data20240522-5072-giv9k1.parquet (closed)>>
C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `unlink': Permission denied @ apply2files - D:/a/_temp/data20240522-5072-giv9k1.parquet (Errno::EACCES)
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `call'
test/run-test.rb: warning: Exception in finalizer #<Tempfile::Remover:0x000001c1afdebf58 @pid=5072, @tmpfile=#<File:D:/a/_temp/data20240522-5072-967stm.parquet (closed)>>
C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `unlink': Permission denied @ apply2files - D:/a/_temp/data20240522-5072-967stm.parquet (Errno::EACCES)
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/tempfile.rb:265:in `call'
```

### Component(s)

Continuous Integration, GLib

**Comment by kou** [comment]
Issue resolved by pull request 41807
https://github.com/apache/arrow/pull/41807
