### ISSUE TITLE
[Python][Dev] Source install yields unexpected keyword argument: 'version_file'

### ISSUE THREAD

**Issue by WillAyd** [apache/arrow#41992]
### Describe the bug, including details regarding any error messages, version, and platform.

Seems to have started with https://github.com/apache/arrow/pull/41041 

```sh
$ python setup.py build_ext --inplace -j14
/home/willayd/clones/arrow/python/setup.py:34: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Traceback (most recent call last):
  File "/home/willayd/clones/arrow/python/setup.py", line 372, in <module>
    setup(
  File "/home/willayd/mambaforge/envs/arrow-dev/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willayd/mambaforge/envs/arrow-dev/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 147, in setup
    _setup_distribution = dist = klass(attrs)
                                 ^^^^^^^^^^^^
  File "/home/willayd/mambaforge/envs/arrow-dev/lib/python3.12/site-packages/setuptools/dist.py", line 303, in __init__
    _Distribution.__init__(self, dist_attrs)
  File "/home/willayd/mambaforge/envs/arrow-dev/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
    self.finalize_options()
  File "/home/willayd/mambaforge/envs/arrow-dev/lib/python3.12/site-packages/setuptools/dist.py", line 654, in finalize_options
    ep(self)
  File "/home/willayd/mambaforge/envs/arrow-dev/lib/python3.12/site-packages/setuptools_scm/integration.py", line 123, in infer_version
    config = Configuration.from_file(dist_name=dist_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/willayd/mambaforge/envs/arrow-dev/lib/python3.12/site-packages/setuptools_scm/config.py", line 216, in from_file
    return cls(relative_to=name, **args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Configuration.__init__() got an unexpected keyword argument 'version_file'
```

### Component(s)

Python

**Comment by assignUser** [comment]
Thanks for the report! 
Directly calling setup.py is deprecated  and apparently no longer compatible with the recent changes, could you try `python -m pip install .`? (we probably need to update some docs too)

**Comment by WillAyd** [comment]
Ah simple enough - makes sense

**Comment by jorisvandenbossche** [comment]
And to be clear, you can continue to use calling built_ext inplace directly (I also still do that, until we move away from setuptools, that is fine), you just need to ran the `pip install -e .` once before that works again.

**Comment by jorisvandenbossche** [comment]
It's also quite likely that you see that error just because of having a too old setuptools_scm in your environment (that's the error I got in another env where I tried to build inplace with `--no-build-isolation`)
