### ISSUE TITLE
[Java][Integration][CI] Integration tests are failing due to missing `/java/pom.xml`

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#42005]
### Describe the bug, including details regarding any error messages, version, and platform.

The following verify integration jobs:
[verify-rc-source-integration-linux-almalinux-8-amd64](https://github.com/ursacomputing/crossbow/actions/runs/9384406401/job/25840130262)
[verify-rc-source-integration-linux-conda-latest-amd64](https://github.com/ursacomputing/crossbow/actions/runs/9384406115/job/25840128650)
[verify-rc-source-integration-linux-ubuntu-20.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/9384406961/job/25840135695)
[verify-rc-source-integration-linux-ubuntu-22.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/9384406435/job/25840130834)
[verify-rc-source-integration-macos-amd64](https://github.com/ursacomputing/crossbow/actions/runs/9384406212/job/25840129118)
[verify-rc-source-integration-macos-arm64](https://github.com/ursacomputing/crossbow/actions/runs/9384406959/job/25840134370)
[verify-rc-source-integration-macos-conda-amd64](https://github.com/ursacomputing/crossbow/actions/runs/9384406131/job/25840128413)

Have been failing for some time with the following error:
```
Successfully installed archery-0.1.0 jpype1-1.5.0 packaging-24.0
Traceback (most recent call last):
  File "/tmp/arrow-HEAD.1gfi5/venv-source/bin/archery", line 8, in <module>
    sys.exit(archery())
  File "/tmp/arrow-HEAD.1gfi5/venv-source/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/arrow-HEAD.1gfi5/venv-source/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/tmp/arrow-HEAD.1gfi5/venv-source/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/arrow-HEAD.1gfi5/venv-source/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/arrow-HEAD.1gfi5/venv-source/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/arrow/dev/archery/archery/cli.py", line 771, in integration
    from .integration.runner import write_js_test_json, run_all_tests
  File "/arrow/dev/archery/archery/integration/runner.py", line 36, in <module>
    from .tester_java import JavaTester
  File "/arrow/dev/archery/archery/integration/tester_java.py", line 53, in <module>
    _arrow_version = load_version_from_pom()
  File "/arrow/dev/archery/archery/integration/tester_java.py", line 37, in load_version_from_pom
    tree = ET.parse(os.path.join(ARROW_BUILD_ROOT, 'java', 'pom.xml'))
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 584, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/java/pom.xml'
```

This has been failing since this https://github.com/apache/arrow/commit/46e78160933d039991cedfabb9216dc4c861fb4b was merged which did modify some of the integration run scripts.

### Component(s)

Continuous Integration, Integration, Java

**Comment by raulcd** [comment]
This https://github.com/apache/arrow/issues/41430 seems to be the culprit when these failures started.

**Comment by raulcd** [comment]
I can reproduce locally with:
```
archery docker run -e VERIFY_VERSION="" -e VERIFY_RC="" -e TEST_DEFAULT=0 -e TEST_INTEGRATION=1 ubuntu-verify-rc
```

**Comment by llama90** [comment]
If my understanding is correct, the path seems to be wrong about `ARROW_BUILD_ROOT`. If I submit a pull request, can it be tested?

**Comment by raulcd** [comment]
yes, of course, we can run the tests with our bot commenting with `@github-actions crossbow submit verify-rc-source-integration-*` on the PR

**Comment by kou** [comment]
Oh, sorry... I should have checked integration tests too when I worked on #41430 and I should have checked the current integration tests failures...

**Comment by kou** [comment]
Issue resolved by pull request 42008
https://github.com/apache/arrow/pull/42008
