### ISSUE TITLE
[Java] Intermittent Test Failure in flight-sql-jdbc-driver Module

### ISSUE THREAD

**Issue by llama90** [apache/arrow#42208]
### Describe the bug, including details regarding any error messages, version, and platform.

The build _intermittently_ fails for the `flight-sql-jdbc-driver` module. The `ITDriverJarValidation.validateShadedJar` test fails, expecting `"<Driver jar was not detected in the classpath>" but received "<jar>"`. The exact conditions causing this issue are unknown.

I have attached the error message.

<details>

```
[INFO] 
[INFO] --------------< org.apache.arrow:flight-sql-jdbc-driver >---------------
[INFO] Building Arrow Flight SQL JDBC Driver 17.0.0-SNAPSHOT            [19/23]
[INFO]   from flight/flight-sql-jdbc-driver/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- clean:3.3.2:clean (default-clean) @ flight-sql-jdbc-driver ---
[INFO] Deleting /Users/lama/workspace/arrow-new/java/flight/flight-sql-jdbc-driver/target
[INFO] 
[INFO] --- apache-rat:0.16.1:check (rat-checks) @ flight-sql-jdbc-driver ---
[INFO] Rat check: Summary over all files. Unapproved: 0, unknown: 0, generated: 0, approved: 2 licenses.
[INFO] 
[INFO] --- enforcer:3.4.1:enforce (enforce-maven-version) @ flight-sql-jdbc-driver ---
[INFO] 
[INFO] --- enforcer:3.4.1:enforce (enforce-java-version) @ flight-sql-jdbc-driver ---
[INFO] 
[INFO] --- checkstyle:3.3.1:check (validate) @ flight-sql-jdbc-driver ---
[INFO] Loaded from the build cache, saving 0.011s
[INFO] 
[INFO] --- git-commit-id:4.9.10:revision (for-jars) @ flight-sql-jdbc-driver ---
[INFO] 
[INFO] --- remote-resources:3.1.0:process (process-resource-bundles) @ flight-sql-jdbc-driver ---
[INFO] Preparing remote bundle org.apache.apache.resources:apache-jar-resource-bundle:1.5
[INFO] Copying 3 resources from 1 bundle.
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ flight-sql-jdbc-driver ---
[INFO] skip non existing resourceDirectory /Users/lama/workspace/arrow-new/java/flight/flight-sql-jdbc-driver/src/main/resources
[INFO] Copying 3 resources from target/maven-shared-archive-resources to target/classes
[INFO] 
[INFO] --- compiler:3.12.1:compile (default-compile) @ flight-sql-jdbc-driver ---
[INFO] Loaded from the build cache
[INFO] 
[INFO] --- module-info-compiler:17.0.0-SNAPSHOT:compile (default-compile) @ flight-sql-jdbc-driver ---
[INFO] No module-info.java file found. module-info.class file was not generated.
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ flight-sql-jdbc-driver ---
[INFO] skip non existing resourceDirectory /Users/lama/workspace/arrow-new/java/flight/flight-sql-jdbc-driver/src/test/resources
[INFO] Copying 3 resources from target/maven-shared-archive-resources to target/test-classes
[INFO] 
[INFO] --- compiler:3.12.1:testCompile (default-testCompile) @ flight-sql-jdbc-driver ---
[INFO] Recompiling the module because of changed dependency.
[INFO] Compiling 1 source file with javac [forked debug target 1.8] to target/test-classes
[WARNING] [options] bootstrap class path is not set in conjunction with -source 8
[INFO] 
[INFO] --- module-info-compiler:17.0.0-SNAPSHOT:testCompile (default-testCompile) @ flight-sql-jdbc-driver ---
[INFO] No module-info.java file found. module-info.class file was not generated.
[INFO] 
[INFO] --- surefire:3.2.5:test (default-test) @ flight-sql-jdbc-driver ---
[WARNING] Could not extract goal execution properties.
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] --- jar:3.2.2:jar (default-jar) @ flight-sql-jdbc-driver ---
[INFO] Building jar: /Users/lama/workspace/arrow-new/java/flight/flight-sql-jdbc-driver/target/flight-sql-jdbc-driver-17.0.0-SNAPSHOT.jar
[INFO] 
[INFO] --- jar:3.2.2:test-jar (default) @ flight-sql-jdbc-driver ---
[INFO] Building jar: /Users/lama/workspace/arrow-new/java/flight/flight-sql-jdbc-driver/target/flight-sql-jdbc-driver-17.0.0-SNAPSHOT-tests.jar
[INFO] 
[INFO] --- cyclonedx:2.7.11:makeBom (default) @ flight-sql-jdbc-driver ---
[INFO] CycloneDX: Resolving Dependencies
[INFO] CycloneDX: Creating BOM version 1.4 with 61 component(s)
[INFO] CycloneDX: Writing and validating BOM (XML): /Users/lama/workspace/arrow-new/java/flight/flight-sql-jdbc-driver/target/bom.xml
[INFO]            attaching as flight-sql-jdbc-driver-17.0.0-SNAPSHOT-cyclonedx.xml
[INFO] CycloneDX: Writing and validating BOM (JSON): /Users/lama/workspace/arrow-new/java/flight/flight-sql-jdbc-driver/target/bom.json
[INFO]            attaching as flight-sql-jdbc-driver-17.0.0-SNAPSHOT-cyclonedx.json
[INFO] 
[INFO] --- site:3.12.1:attach-descriptor (attach-descriptor) @ flight-sql-jdbc-driver ---
[INFO] Skipping because packaging 'jar' is not pom.
[INFO] 
[INFO] --- shade:3.5.1:shade (default) @ flight-sql-jdbc-driver ---
[INFO] Including org.apache.arrow:flight-sql-jdbc-core:jar:17.0.0-SNAPSHOT in the shaded jar.
[INFO] Including org.apache.arrow:flight-core:jar:17.0.0-SNAPSHOT in the shaded jar.
[INFO] Including org.apache.arrow:arrow-format:jar:17.0.0-SNAPSHOT in the shaded jar.
[INFO] Including io.grpc:grpc-netty:jar:1.63.0 in the shaded jar.
[INFO] Including io.netty:netty-codec-http2:jar:4.1.110.Final in the shaded jar.
[INFO] Including io.netty:netty-codec-http:jar:4.1.110.Final in the shaded jar.
[INFO] Including io.netty:netty-handler-proxy:jar:4.1.110.Final in the shaded jar.
[INFO] Including io.netty:netty-codec-socks:jar:4.1.110.Final in the shaded jar.
[INFO] Including io.perfmark:perfmark-api:jar:0.26.0 in the shaded jar.
[INFO] Including io.netty:netty-transport-native-unix-common:jar:4.1.110.Final in the shaded jar.
[INFO] Including io.grpc:grpc-util:jar:1.63.0 in the shaded jar.
[INFO] Including io.grpc:grpc-core:jar:1.63.0 in the shaded jar.
[INFO] Including com.google.code.gson:gson:jar:2.10.1 in the shaded jar.
[INFO] Including io.grpc:grpc-context:jar:1.63.0 in the shaded jar.
[INFO] Including io.grpc:grpc-protobuf:jar:1.63.0 in the shaded jar.
[INFO] Including com.google.api.grpc:proto-google-common-protos:jar:2.29.0 in the shaded jar.
[INFO] Including io.grpc:grpc-protobuf-lite:jar:1.63.0 in the shaded jar.
[INFO] Including io.netty:netty-tcnative-boringssl-static:jar:2.0.65.Final in the shaded jar.
[INFO] Including io.netty:netty-tcnative-classes:jar:2.0.65.Final in the shaded jar.
[INFO] Including io.netty:netty-tcnative-boringssl-static:jar:linux-x86_64:2.0.65.Final in the shaded jar.
[INFO] Including io.netty:netty-tcnative-boringssl-static:jar:linux-aarch_64:2.0.65.Final in the shaded jar.
[INFO] Including io.netty:netty-tcnative-boringssl-static:jar:osx-x86_64:2.0.65.Final in the shaded jar.
[INFO] Including io.netty:netty-tcnative-boringssl-static:jar:osx-aarch_64:2.0.65.Final in the shaded jar.
[INFO] Including io.netty:netty-tcnative-boringssl-static:jar:windows-x86_64:2.0.65.Final in the shaded jar.
[INFO] Including io.netty:netty-buffer:jar:4.1.110.Final in the shaded jar.
[INFO] Including io.netty:netty-handler:jar:4.1.110.Final in the shaded jar.
[INFO] Including io.netty:netty-resolver:jar:4.1.110.Final in the shaded jar.
[INFO] Including io.netty:netty-codec:jar:4.1.110.Final in the shaded jar.
[INFO] Including io.netty:netty-transport:jar:4.1.110.Final in the shaded jar.
[INFO] Including io.grpc:grpc-stub:jar:1.63.0 in the shaded jar.
[INFO] Including com.google.protobuf:protobuf-java-util:jar:3.25.1 in the shaded jar.
[INFO] Including io.grpc:grpc-api:jar:1.63.0 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-databind:jar:2.17.1 in the shaded jar.
[INFO] Including org.apache.arrow:arrow-memory-core:jar:17.0.0-SNAPSHOT in the shaded jar.
[INFO] Including org.apache.arrow:arrow-memory-netty:jar:17.0.0-SNAPSHOT in the shaded jar.
[INFO] Including org.apache.arrow:arrow-memory-netty-buffer-patch:jar:17.0.0-SNAPSHOT in the shaded jar.
[INFO] Including org.apache.arrow:arrow-vector:jar:17.0.0-SNAPSHOT in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-core:jar:2.17.1 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-annotations:jar:2.17.1 in the shaded jar.
[INFO] Including com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.17.1 in the shaded jar.
[INFO] Including commons-codec:commons-codec:jar:1.17.0 in the shaded jar.
[INFO] Including com.google.flatbuffers:flatbuffers-java:jar:23.5.26 in the shaded jar.
[INFO] Including org.slf4j:slf4j-api:jar:2.0.13 in the shaded jar.
[INFO] Including com.google.protobuf:protobuf-java:jar:3.25.1 in the shaded jar.
[INFO] Including io.netty:netty-common:jar:4.1.110.Final in the shaded jar.
[INFO] Including org.apache.arrow:flight-sql:jar:17.0.0-SNAPSHOT in the shaded jar.
[INFO] Including org.apache.calcite.avatica:avatica:jar:1.25.0 in the shaded jar.
[INFO] Including org.bouncycastle:bcpkix-jdk18on:jar:1.78.1 in the shaded jar.
[INFO] Including org.bouncycastle:bcprov-jdk18on:jar:1.78.1 in the shaded jar.
[INFO] Including org.bouncycastle:bcutil-jdk18on:jar:1.78.1 in the shaded jar.
[INFO] Including org.slf4j:slf4j-jdk14:jar:2.0.13 in the shaded jar.
[INFO] Including com.google.guava:guava:jar:33.2.1-jre in the shaded jar.
[INFO] Including com.google.guava:failureaccess:jar:1.0.2 in the shaded jar.
[INFO] Including com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava in the shaded jar.
[INFO] Excluding com.google.android:annotations:jar:4.1.1.4 from the shaded jar.
[INFO] Excluding org.codehaus.mojo:animal-sniffer-annotations:jar:1.23 from the shaded jar.
[INFO] Excluding javax.annotation:javax.annotation-api:jar:1.3.2 from the shaded jar.
[INFO] Excluding com.google.code.findbugs:jsr305:jar:3.0.2 from the shaded jar.
[INFO] Excluding com.google.errorprone:error_prone_annotations:jar:2.26.1 from the shaded jar.
[INFO] Excluding com.google.j2objc:j2objc-annotations:jar:3.0.0 from the shaded jar.
[INFO] Dependency-reduced POM written at: /Users/lama/workspace/arrow-new/java/flight/flight-sql-jdbc-driver/dependency-reduced-pom.xml
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] avatica-1.25.0.jar, slf4j-api-2.0.13.jar define 33 overlapping classes: 
[WARNING]   - org.slf4j.ILoggerFactory
[WARNING]   - org.slf4j.IMarkerFactory
[WARNING]   - org.slf4j.Logger
[WARNING]   - org.slf4j.LoggerFactory
[WARNING]   - org.slf4j.MDC
[WARNING]   - org.slf4j.MDC$1
[WARNING]   - org.slf4j.MDC$MDCCloseable
[WARNING]   - org.slf4j.Marker
[WARNING]   - org.slf4j.MarkerFactory
[WARNING]   - org.slf4j.event.EventConstants
[WARNING]   - 23 more...
[WARNING] commons-codec-1.17.0.jar, netty-tcnative-boringssl-static-2.0.65.Final-linux-aarch_64.jar, netty-tcnative-boringssl-static-2.0.65.Final-linux-x86_64.jar, netty-tcnative-boringssl-static-2.0.65.Final-osx-aarch_64.jar, netty-tcnative-boringssl-static-2.0.65.Final-osx-x86_64.jar, netty-tcnative-boringssl-static-2.0.65.Final-windows-x86_64.jar define 1 overlapping resource: 
[WARNING]   - META-INF/NOTICE.txt
[WARNING] avatica-1.25.0.jar, jackson-core-2.17.1.jar define 2 overlapping resources: 
[WARNING]   - META-INF/FastDoubleParser-LICENSE
[WARNING]   - META-INF/FastDoubleParser-NOTICE
[WARNING] arrow-format-17.0.0-SNAPSHOT.jar, arrow-memory-core-17.0.0-SNAPSHOT.jar, arrow-memory-netty-17.0.0-SNAPSHOT.jar, arrow-memory-netty-buffer-patch-17.0.0-SNAPSHOT.jar, arrow-vector-17.0.0-SNAPSHOT.jar, avatica-1.25.0.jar, bcpkix-jdk18on-1.78.1.jar, bcprov-jdk18on-1.78.1.jar, bcutil-jdk18on-1.78.1.jar, commons-codec-1.17.0.jar, failureaccess-1.0.2.jar, flatbuffers-java-23.5.26.jar, flight-core-17.0.0-SNAPSHOT.jar, flight-sql-17.0.0-SNAPSHOT.jar, flight-sql-jdbc-core-17.0.0-SNAPSHOT.jar, flight-sql-jdbc-driver-17.0.0-SNAPSHOT.jar, grpc-api-1.63.0.jar, grpc-context-1.63.0.jar, grpc-core-1.63.0.jar, grpc-netty-1.63.0.jar, grpc-protobuf-1.63.0.jar, grpc-protobuf-lite-1.63.0.jar, grpc-stub-1.63.0.jar, grpc-util-1.63.0.jar, gson-2.10.1.jar, guava-33.2.1-jre.jar, jackson-annotations-2.17.1.jar, jackson-core-2.17.1.jar, jackson-databind-2.17.1.jar, jackson-datatype-jsr310-2.17.1.jar, listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar, netty-buffer-4.1.110.Final.jar, netty-codec-4.1.110.Final.jar, netty-codec-http-4.1.110.Final.jar, netty-codec-http2-4.1.110.Final.jar, netty-codec-socks-4.1.110.Final.jar, netty-common-4.1.110.Final.jar, netty-handler-4.1.110.Final.jar, netty-handler-proxy-4.1.110.Final.jar, netty-resolver-4.1.110.Final.jar, netty-tcnative-boringssl-static-2.0.65.Final-linux-aarch_64.jar, netty-tcnative-boringssl-static-2.0.65.Final-linux-x86_64.jar, netty-tcnative-boringssl-static-2.0.65.Final-osx-aarch_64.jar, netty-tcnative-boringssl-static-2.0.65.Final-osx-x86_64.jar, netty-tcnative-boringssl-static-2.0.65.Final-windows-x86_64.jar, netty-tcnative-boringssl-static-2.0.65.Final.jar, netty-tcnative-classes-2.0.65.Final.jar, netty-transport-4.1.110.Final.jar, netty-transport-native-unix-common-4.1.110.Final.jar, perfmark-api-0.26.0.jar, proto-google-common-protos-2.29.0.jar, protobuf-java-3.25.1.jar, protobuf-java-util-3.25.1.jar, slf4j-api-2.0.13.jar, slf4j-jdk14-2.0.13.jar define 1 overlapping resource: 
[WARNING]   - META-INF/MANIFEST.MF
[WARNING] netty-buffer-4.1.110.Final.jar, netty-codec-4.1.110.Final.jar, netty-codec-http-4.1.110.Final.jar, netty-codec-http2-4.1.110.Final.jar, netty-codec-socks-4.1.110.Final.jar, netty-common-4.1.110.Final.jar, netty-handler-4.1.110.Final.jar, netty-handler-proxy-4.1.110.Final.jar, netty-resolver-4.1.110.Final.jar, netty-transport-4.1.110.Final.jar, netty-transport-native-unix-common-4.1.110.Final.jar define 1 overlapping resource: 
[WARNING]   - META-INF/io.netty.versions.properties
[WARNING] avatica-1.25.0.jar, bcpkix-jdk18on-1.78.1.jar, bcprov-jdk18on-1.78.1.jar, bcutil-jdk18on-1.78.1.jar, commons-codec-1.17.0.jar, gson-2.10.1.jar, jackson-core-2.17.1.jar, jackson-databind-2.17.1.jar, jackson-datatype-jsr310-2.17.1.jar, slf4j-api-2.0.13.jar, slf4j-jdk14-2.0.13.jar define 1 overlapping classes: 
[WARNING]   - META-INF.versions.9.module-info
[WARNING] arrow-format-17.0.0-SNAPSHOT.jar, arrow-memory-core-17.0.0-SNAPSHOT.jar, arrow-memory-netty-17.0.0-SNAPSHOT.jar, arrow-memory-netty-buffer-patch-17.0.0-SNAPSHOT.jar, arrow-vector-17.0.0-SNAPSHOT.jar, avatica-1.25.0.jar, flight-core-17.0.0-SNAPSHOT.jar, flight-sql-17.0.0-SNAPSHOT.jar, flight-sql-jdbc-core-17.0.0-SNAPSHOT.jar, flight-sql-jdbc-driver-17.0.0-SNAPSHOT.jar, jackson-annotations-2.17.1.jar, jackson-core-2.17.1.jar, jackson-databind-2.17.1.jar, jackson-datatype-jsr310-2.17.1.jar define 1 overlapping resource: 
[WARNING]   - META-INF/NOTICE
[WARNING] netty-tcnative-boringssl-static-2.0.65.Final-linux-aarch_64.jar, netty-tcnative-boringssl-static-2.0.65.Final-linux-x86_64.jar, netty-tcnative-boringssl-static-2.0.65.Final-osx-aarch_64.jar, netty-tcnative-boringssl-static-2.0.65.Final-osx-x86_64.jar, netty-tcnative-boringssl-static-2.0.65.Final-windows-x86_64.jar define 4 overlapping resources: 
[WARNING]   - META-INF/license/LICENSE.aix-netbsd.txt
[WARNING]   - META-INF/license/LICENSE.boringssl.txt
[WARNING]   - META-INF/license/LICENSE.mvn-wrapper.txt
[WARNING]   - META-INF/license/LICENSE.tomcat-native.txt
[WARNING] commons-codec-1.17.0.jar, netty-tcnative-boringssl-static-2.0.65.Final-linux-aarch_64.jar, netty-tcnative-boringssl-static-2.0.65.Final-linux-x86_64.jar, netty-tcnative-boringssl-static-2.0.65.Final-osx-aarch_64.jar, netty-tcnative-boringssl-static-2.0.65.Final-osx-x86_64.jar, netty-tcnative-boringssl-static-2.0.65.Final-windows-x86_64.jar, slf4j-api-2.0.13.jar, slf4j-jdk14-2.0.13.jar define 1 overlapping resource: 
[WARNING]   - META-INF/LICENSE.txt
[WARNING] arrow-format-17.0.0-SNAPSHOT.jar, arrow-memory-core-17.0.0-SNAPSHOT.jar, arrow-memory-netty-17.0.0-SNAPSHOT.jar, arrow-memory-netty-buffer-patch-17.0.0-SNAPSHOT.jar, arrow-vector-17.0.0-SNAPSHOT.jar, avatica-1.25.0.jar, flight-core-17.0.0-SNAPSHOT.jar, flight-sql-17.0.0-SNAPSHOT.jar, flight-sql-jdbc-core-17.0.0-SNAPSHOT.jar, flight-sql-jdbc-driver-17.0.0-SNAPSHOT.jar, guava-33.2.1-jre.jar, jackson-annotations-2.17.1.jar, jackson-core-2.17.1.jar, jackson-databind-2.17.1.jar, jackson-datatype-jsr310-2.17.1.jar define 1 overlapping resource: 
[WARNING]   - META-INF/LICENSE
[WARNING] bcpkix-jdk18on-1.78.1.jar, bcprov-jdk18on-1.78.1.jar, bcutil-jdk18on-1.78.1.jar define 1 overlapping resource: 
[WARNING]   - META-INF/versions/9/OSGI-INF/MANIFEST.MF
[WARNING] netty-tcnative-boringssl-static-2.0.65.Final-linux-aarch_64.jar, netty-tcnative-boringssl-static-2.0.65.Final-linux-x86_64.jar, netty-tcnative-boringssl-static-2.0.65.Final-osx-aarch_64.jar, netty-tcnative-boringssl-static-2.0.65.Final-osx-x86_64.jar, netty-tcnative-boringssl-static-2.0.65.Final-windows-x86_64.jar, netty-tcnative-boringssl-static-2.0.65.Final.jar define 2 overlapping resources: 
[WARNING]   - META-INF/maven/io.netty/netty-tcnative-boringssl-static/pom.properties
[WARNING]   - META-INF/maven/io.netty/netty-tcnative-boringssl-static/pom.xml
[WARNING] arrow-format-17.0.0-SNAPSHOT.jar, arrow-memory-core-17.0.0-SNAPSHOT.jar, arrow-memory-netty-17.0.0-SNAPSHOT.jar, arrow-memory-netty-buffer-patch-17.0.0-SNAPSHOT.jar, arrow-vector-17.0.0-SNAPSHOT.jar, flight-core-17.0.0-SNAPSHOT.jar, flight-sql-17.0.0-SNAPSHOT.jar, flight-sql-jdbc-core-17.0.0-SNAPSHOT.jar, flight-sql-jdbc-driver-17.0.0-SNAPSHOT.jar define 1 overlapping resource: 
[WARNING]   - arrow-git.properties
[WARNING] arrow-format-17.0.0-SNAPSHOT.jar, arrow-memory-core-17.0.0-SNAPSHOT.jar, arrow-memory-netty-17.0.0-SNAPSHOT.jar, arrow-memory-netty-buffer-patch-17.0.0-SNAPSHOT.jar, arrow-vector-17.0.0-SNAPSHOT.jar, avatica-1.25.0.jar, flight-core-17.0.0-SNAPSHOT.jar, flight-sql-17.0.0-SNAPSHOT.jar, flight-sql-jdbc-core-17.0.0-SNAPSHOT.jar, flight-sql-jdbc-driver-17.0.0-SNAPSHOT.jar define 1 overlapping resource: 
[WARNING]   - META-INF/DEPENDENCIES
[WARNING] maven-shade-plugin has detected that some files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the file is copied to the uber jar.
[WARNING] Usually this is not harmful and you can skip these warnings,
[WARNING] otherwise try to manually exclude artifacts based on
[WARNING] mvn dependency:tree -Ddetail=true and the above output.
[WARNING] See https://maven.apache.org/plugins/maven-shade-plugin/
[INFO] Replacing original artifact with shaded artifact.
[INFO] Replacing /Users/lama/workspace/arrow-new/java/flight/flight-sql-jdbc-driver/target/flight-sql-jdbc-driver-17.0.0-SNAPSHOT.jar with /Users/lama/workspace/arrow-new/java/flight/flight-sql-jdbc-driver/target/flight-sql-jdbc-driver-17.0.0-SNAPSHOT-shaded.jar
[INFO] 
[INFO] --- failsafe:3.2.5:integration-test (default) @ flight-sql-jdbc-driver ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
WARNING: Unknown module: org.apache.arrow.memory.core specified to --add-opens
[INFO] Running org.apache.arrow.driver.jdbc.ITDriverJarValidation
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.032 s <<< FAILURE! -- in org.apache.arrow.driver.jdbc.ITDriverJarValidation
[ERROR] org.apache.arrow.driver.jdbc.ITDriverJarValidation.validateShadedJar -- Time elapsed: 0.011 s <<< FAILURE!
org.opentest4j.AssertionFailedError: jar ==> expected: <Driver jar was not detected in the classpath> but was: <jar>
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1156)
        at org.apache.arrow.driver.jdbc.ITDriverJarValidation.getJdbcJarFile(ITDriverJarValidation.java:72)
        at org.apache.arrow.driver.jdbc.ITDriverJarValidation.validateShadedJar(ITDriverJarValidation.java:84)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ITDriverJarValidation.validateShadedJar:84->getJdbcJarFile:72 jar ==> expected: <Driver jar was not detected in the classpath> but was: <jar>
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- enforcer:3.4.1:enforce (avoid_bad_dependencies) @ flight-sql-jdbc-driver ---
[INFO] Rule 0: org.apache.maven.enforcer.rules.dependency.BannedDependencies passed
[INFO] 
[INFO] --- dependency:3.6.1:analyze-only (analyze) @ flight-sql-jdbc-driver ---
[INFO] No dependency problems found
[INFO] 
[INFO] --- spotless:2.30.0:check (spotless-check) @ flight-sql-jdbc-driver ---
[INFO] Sorting file /var/folders/t6/smbzw2hd4h141dhb0c_npdlj8v6jgz/T/pom2613582584532760383.xml
[INFO] Pom file is already sorted, exiting
[INFO] 
[INFO] --- failsafe:3.2.5:verify (default) @ flight-sql-jdbc-driver ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache Arrow Java Root POM 17.0.0-SNAPSHOT:
[INFO] 
[INFO] Arrow Maven Plugins ................................ SUCCESS [  5.161 s]
[INFO] Module Info Compiler Maven Plugin .................. SUCCESS [  2.910 s]
[INFO] Arrow Bill of Materials ............................ SUCCESS [  0.027 s]
[INFO] Apache Arrow Java Root POM ......................... SUCCESS [  5.749 s]
[INFO] Arrow Format ....................................... SUCCESS [  2.051 s]
[INFO] Arrow Memory ....................................... SUCCESS [  1.934 s]
[INFO] Arrow Memory - Core ................................ SUCCESS [  4.025 s]
[INFO] Arrow Memory - Unsafe .............................. SUCCESS [  2.501 s]
[INFO] Arrow Memory - Netty Buffer ........................ SUCCESS [  2.122 s]
[INFO] Arrow Memory - Netty ............................... SUCCESS [  2.224 s]
[INFO] Arrow Vectors ...................................... SUCCESS [ 20.668 s]
[INFO] Arrow Compression .................................. SUCCESS [  5.470 s]
[INFO] Arrow Tools ........................................ SUCCESS [  5.300 s]
[INFO] Arrow JDBC Adapter ................................. SUCCESS [  8.380 s]
[INFO] Arrow Flight ....................................... SUCCESS [  2.199 s]
[INFO] Arrow Flight Core .................................. SUCCESS [ 23.773 s]
[INFO] Arrow Flight SQL ................................... SUCCESS [  7.109 s]
[INFO] Arrow Flight SQL JDBC Driver Core .................. SUCCESS [01:48 min]
[INFO] Arrow Flight SQL JDBC Driver ....................... FAILURE [ 30.058 s]
[INFO] Arrow Flight Integration Tests ..................... SKIPPED
[INFO] Arrow AVRO Adapter ................................. SKIPPED
[INFO] Arrow Algorithms ................................... SKIPPED
[INFO] Arrow Performance Benchmarks ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:00 min
[INFO] Finished at: 2024-06-19T16:41:47+09:00
[INFO] ------------------------------------------------------------------------
[INFO] 395 goals, 360 executed, 35 from cache, saving at least 1m 20s
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.2.5:verify (default) on project flight-sql-jdbc-driver: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/lama/workspace/arrow-new/java/flight/flight-sql-jdbc-driver/target/failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :flight-sql-jdbc-driver
```

</details>

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 42217
https://github.com/apache/arrow/pull/42217
