### ISSUE TITLE
[C++][Parquet] Fix for PARQUET-890 introduces undefined symbol in libparquet_arrow.so

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#42639]
After commit `c41a718dae9c60465ea0d8c99d6e3bdca11f802f` (the most recent commit for parquet-cpp which fixed PARQUET-890, the following error occurs when pyarrow tries to load libparquet_arrow.so:

```Java
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow.parquet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyarrow-0.2.1.dev17+ngb109a24-py2.7-linux-x86_64.egg/pyarrow/parquet.py", line 20, in <module>
    from pyarrow._parquet import (ParquetReader, FileMetaData,  # noqa
ImportError: /usr/local/lib/libparquet_arrow.so: undefined symbol: _ZN7parquet19LogicalTypeToStringB5cxx11ENS_11LogicalType4typeE
```

Building the library using the previous commit doesn't exhibit this problem.

**Reporter**: [Jeff Knupp](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jeffknupp) / @jeffknupp
**Assignee**: Wes McKinney](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wesm) / @wesm

<sub>**Note**: *This issue was originally created as [PARQUET-908](https://issues.apache.org/jira/browse/PARQUET-908). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Wes McKinney](https://issues.apache.org/jira/browse/PARQUET-908?#comment-15901409) / @wesm:
thanks @jeffknupp. Here's a PR: https://github.com/apache/parquet-cpp/pull/267

**Comment by asfimport** [comment]
[Wes McKinney](https://issues.apache.org/jira/browse/PARQUET-908?#comment-15902200) / @wesm:
Issue resolved by pull request 267
<https://github.com/apache/parquet-cpp/pull/267>
