### ISSUE TITLE
[C++][Parquet] Coverage upload is broken

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#42737]
```Java
++which gcov-4.9
+coveralls --gcov /usr/bin/gcov-4.9 --gcov-options '\-l' --root '' --include /home/travis/build/apache/parquet-cpp --exclude /home/travis/build/apache/parquet-cpp/parquet-build/thirdparty --exclude /home/travis/build/apache/parquet-cpp/parquet-build/arrow_ep --exclude /home/travis/build/apache/parquet-cpp/parquet-build/brotli_ep --exclude /home/travis/build/apache/parquet-cpp/parquet-build/brotli_ep-prefix --exclude /home/travis/build/apache/parquet-cpp/parquet-build/gbenchmark_ep --exclude /home/travis/build/apache/parquet-cpp/parquet-build/googletest_ep-prefix --exclude /home/travis/build/apache/parquet-cpp/parquet-build/snappy_ep --exclude /home/travis/build/apache/parquet-cpp/parquet-build/snappy_ep-prefix --exclude /home/travis/build/apache/parquet-cpp/parquet-build/zlib_ep --exclude /home/travis/build/apache/parquet-cpp/parquet-build/zlib_ep-prefix --exclude /home/travis/build/apache/parquet-cpp/build --exclude /home/travis/build/apache/parquet-cpp/src/parquet/thrift --exclude /usr
Traceback (most recent call last):
  File "/usr/local/bin/coveralls", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3037, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3021, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3050, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 969, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 863, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2577, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: urllib3 1.7.1 has no such extra feature 'secure'
```

**Reporter**: [Uwe Korn](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=uwe) / @xhochy
**Assignee**: Deepak Majeti](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdeepak) / @majetideepak

<sub>**Note**: *This issue was originally created as [PARQUET-1075](https://issues.apache.org/jira/browse/PARQUET-1075). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Deepak Majeti](https://issues.apache.org/jira/browse/PARQUET-1075?#comment-16118643) / @majetideepak:
PR: https://github.com/apache/parquet-cpp/pull/382

**Comment by asfimport** [comment]
[Wes McKinney](https://issues.apache.org/jira/browse/PARQUET-1075?#comment-16121991) / @wesm:
Issue resolved by pull request 382
<https://github.com/apache/parquet-cpp/pull/382>
