### ISSUE TITLE
[C++][Parquet] Support 2-level list encoding in Arrow decoding

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#42763]
While trying to read a parquetfile (written by nifi) I am getting an error.

code:

import pyarrow.parquet as pq
t = pq.read_table('test.parq')

error:
Traceback (most recent call last):
  File "parquet_reader.py", line 2, in <module>
    t = pq.read_table('test.parq')
  File "/opt/anaconda3/lib/python3.6/site-packages/pyarrow/parquet.py", line 823, in read_table
    use_pandas_metadata=use_pandas_metadata)
  File "/opt/anaconda3/lib/python3.6/site-packages/pyarrow/parquet.py", line 119, in read
    nthreads=nthreads)
  File "pyarrow/_parquet.pyx", line 466, in pyarrow._parquet.ParquetReader.read_all (/arrow/python/build/temp.linux-x86_64-3.6/_parquet.cxx:9181)
  File "pyarrow/error.pxi", line 85, in pyarrow.lib.check_status (/arrow/python/build/temp.linux-x86_64-3.6/lib.cxx:8115)
pyarrow.lib.ArrowNotImplementedError: No support for reading columns of type list<array: string not null>

**Environment**: centos 7.3, Anaconda 4.4.0 python 3.6.1
**Reporter**: [Luke Higgins](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=virtualluke)

<sub>**Note**: *This issue was originally created as [PARQUET-1122](https://issues.apache.org/jira/browse/PARQUET-1122). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Wes McKinney](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-16193017) / @wesm:
Hm, I believe this should work in 0.7.1. Can you provide any way to reproduce the error?

**Comment by asfimport** [comment]
[Luke Higgins](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-16193050):
I am using pyarrow 0.7.1.  I can't post the file, but,  FYI it does work with fastparquet.ParquetFile('test.parq').   Is there something else I can show to help that isn't actually posting the file? Thanks!

**Comment by asfimport** [comment]
[Wes McKinney](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-16193053) / @wesm:
Can you write a file with the same characteristics but non-sensitive data?

**Comment by asfimport** [comment]
[Luke Higgins](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-16193298):
sorry, not easily. Here is the schema of the file erroring out (seen from fastparquet):
>>> t = fastparquet.ParquetFile('test.parq')
>>> type(t)
<class 'fastparquet.api.ParquetFile'>
>>> print(t.schema)
```java
-avro.mylog:
| - field0: BYTE_ARRAY, UTF8, REQUIRED
| - field1: BYTE_ARRAY, UTF8, REQUIRED
| - field2: INT64, REQUIRED
| - field3: BYTE_ARRAY, UTF8, REQUIRED
| - field4: BYTE_ARRAY, UTF8, REQUIRED
| - field5: INT64, REQUIRED
| - field6: BYTE_ARRAY, UTF8, REQUIRED
| - field7: INT64, REQUIRED
| - field8: BOOLEAN, OPTIONAL
| - field9: BOOLEAN, OPTIONAL
| - field10: INT64, REQUIRED
| - field11: BYTE_ARRAY, UTF8, OPTIONAL
| - field12: BYTE_ARRAY, UTF8, OPTIONAL
| - field13: BYTE_ARRAY, UTF8, OPTIONAL
| - field14: BYTE_ARRAY, UTF8, OPTIONAL
| - field15: BYTE_ARRAY, UTF8, OPTIONAL
| - field16: BYTE_ARRAY, UTF8, OPTIONAL
| - field17: INT64, OPTIONAL
| - field18: INT64, OPTIONAL
| - field19: INT64, OPTIONAL
| - field20: BYTE_ARRAY, UTF8, OPTIONAL
| - field21: INT64, OPTIONAL
| - field22: BYTE_ARRAY, UTF8, OPTIONAL
| - field23: LIST, REQUIRED
|   - array: BYTE_ARRAY, UTF8, REPEATED
| - field24: BYTE_ARRAY, UTF8, OPTIONAL
| - field25: BYTE_ARRAY, UTF8, OPTIONAL
| - field26: BOOLEAN, OPTIONAL
| - field27: LIST, OPTIONAL
|   - array: BYTE_ARRAY, UTF8, REPEATED
| - field28: BOOLEAN, OPTIONAL
| - field29: LIST, OPTIONAL
|   - array: BYTE_ARRAY, UTF8, REPEATED
| - field30: LIST, OPTIONAL
|   - array: BYTE_ARRAY, UTF8, REPEATED
| - field31: LIST, OPTIONAL
|   - array: BYTE_ARRAY, UTF8, REPEATED
| - field32: LIST, OPTIONAL
|   - array: BYTE_ARRAY, UTF8, REPEATED
| - field33: LIST, OPTIONAL
|   - array: BYTE_ARRAY, UTF8, REPEATED
| - field34: LIST, OPTIONAL
|   - array: BYTE_ARRAY, UTF8, REPEATED
| - field35: BYTE_ARRAY, UTF8, OPTIONAL
| - field36: INT64, OPTIONAL
| - field37: INT64, OPTIONAL
| - field38: LIST, OPTIONAL
|   - array: BYTE_ARRAY, UTF8, REPEATED
| - field39: LIST, OPTIONAL
|   - array: BYTE_ARRAY, UTF8, REPEATED
| - field40: BOOLEAN, OPTIONAL
| - field41: BYTE_ARRAY, UTF8, OPTIONAL
| - field42: LIST, OPTIONAL
|   - array: BYTE_ARRAY, UTF8, REPEATED
  - field43: LIST, OPTIONAL
    - array: BYTE_ARRAY, UTF8, REPEATED
```

**Comment by asfimport** [comment]
[Wes McKinney](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-16193520) / @wesm:
What can you tell me about the Parquet implementation that produced this file (I see you said nifi, but can you show me the written-by version string to see if it's parquet-mr and if so what version)? I believe that whoever wrote the file is using a deprecated list encoding. 

See https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#lists

The schema shown here is not using the 3-level list encoding structure, instead the 2-level structure. We will need to implement support for this in parquet-cpp; I don't think it should be too hard but I haven't seen a file like this in the wild in a while

**Comment by asfimport** [comment]
[Luke Higgins](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-16193715):
nifi's parquet code (I believe this is the relevant piece, if not nearby)

https://github.com/apache/nifi/blob/master/nifi-nar-bundles/nifi-parquet-bundle/nifi-parquet-processors/src/main/java/org/apache/nifi/processors/parquet/PutParquet.java

**Comment by asfimport** [comment]
[Luke Higgins](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-16193782):
looking in the pom.xml in the nifi tree looks like parquet-mr 1.8.2

**Comment by asfimport** [comment]
[Wes McKinney](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-16193834) / @wesm:
@julienledem @rdblue is there a chance that there's a bug in parquet-avro that would lead to creating 2-level (instead of 3-level) list encoding? Let me know any other insights

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-16193876) / @rdblue:
Using the 3-level structure breaks old readers, so we can't enable it by default until a major release because we guarantee forward-compatibility in the format. If you want to use 3-level lists, you should opt in using this config:

```Java
conf.set("parquet.avro.write-old-list-structure", "false");
```

Does the arrow reader not implement the backward-compat rules for 2-level lists?

**Comment by asfimport** [comment]
[Wes McKinney](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-16193890) / @wesm:
It seems not. This feels rather serious so I'm going to move this over to the Parquet project JIRA so we can try to sort out a fix for 1.3.1

**Comment by asfimport** [comment]
[Ben Weidig](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-16293024):
FWIW I get this error using the users.parquet file in the examples directory for the spark 2.3.0-snapshot release.

**Comment by asfimport** [comment]
[Wes McKinney](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-16293959) / @wesm:
Moving to 1.4.0 milestone. Could someone take a look?

**Comment by asfimport** [comment]
[Luke Higgins](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-16357526):
Anything new with this?

 

I am posting the pyarrow.parquet.ParquetFile schema also as it looks different than the one coming from fastparquet.  Using pyarrow 0.8, python 3.6.3 (anaconda).  The parquet file was generated using nifi "created_by: parquet-mr version 1.8.2 (build c6522788629e590a53eb79874b95f6c3ff11f16c)".  The original schema is coming from an avro schema for this data and nifi is converting from avro to parquet using the above library.

import pyarrow.parquet as pq

>>> pf = pq.ParquetFile('7759605316780069')
>>> pf.schema
<pyarrow._parquet.ParquetSchema object at 0x7efd6e41ed08>
field1: BYTE_ARRAY UTF8
field2: BYTE_ARRAY UTF8
datetime: INT64
uid: BYTE_ARRAY UTF8
field3: BYTE_ARRAY UTF8
field4: INT64
field5: BYTE_ARRAY UTF8
field6: INT64
field7: BOOLEAN
field8: BOOLEAN
field9: INT64
field10: BYTE_ARRAY UTF8
field11: BYTE_ARRAY UTF8
field12: BYTE_ARRAY UTF8
field13: BYTE_ARRAY UTF8
field14: BYTE_ARRAY UTF8
field15: BYTE_ARRAY UTF8
field16: INT64
field17: INT64
field18: INT64
field19: BYTE_ARRAY UTF8
field20: INT64
field21: BYTE_ARRAY UTF8
field22: BYTE_ARRAY UTF8
field23: BYTE_ARRAY UTF8
field24: BYTE_ARRAY UTF8
field25: BOOLEAN
field26: BYTE_ARRAY UTF8
field27: BOOLEAN
field28: BYTE_ARRAY UTF8
field29: BYTE_ARRAY UTF8
field30: BYTE_ARRAY UTF8
field31: BYTE_ARRAY UTF8
field32: BYTE_ARRAY UTF8
field33: BYTE_ARRAY UTF8
field34: BYTE_ARRAY UTF8
field35: INT64
field36: INT64
field37: BYTE_ARRAY UTF8
field38: BYTE_ARRAY UTF8
field39: BOOLEAN
field40: BYTE_ARRAY UTF8
field41: BYTE_ARRAY UTF8
field42: BYTE_ARRAY UTF8
field43: BYTE_ARRAY UTF8

>>> pf.metadata
<pyarrow._parquet.FileMetaData object at 0x7efd6e41d098>
 created_by: parquet-mr version 1.8.2 (build c6522788629e590a53eb79874b95f6c3ff11f16c)
 num_columns: 45
 num_rows: 221552
 num_row_groups: 1
 format_version: 1.0
 serialized_size: 8288

>>> pq.read_table('7759605316780069')
Traceback (most recent call last):(
 File "<stdin>", line 1, in <module>
 File "/opt/anaconda3/lib/python3.6/site-packages/pyarrow/parquet.py", line 892, in read_table
 use_pandas_metadata=use_pandas_metadata)
 File "/opt/anaconda3/lib/python3.6/site-packages/pyarrow/parquet.py", line 142, in read
 nthreads=nthreads)
 File "pyarrow/_parquet.pyx", line 709, in pyarrow._parquet.ParquetReader.read_all (/arrow/python/build/temp.linux-x86_64-3.6/_parquet.cxx:12865)
 File "pyarrow/error.pxi", line 85, in pyarrow.lib.check_status (/arrow/python/build/temp.linux-x86_64-3.6/lib.cxx:8570)
pyarrow.lib.ArrowNotImplementedError: No support for reading columns of type list<array: string not null>

**Comment by asfimport** [comment]
[Wes McKinney](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-16357530) / @wesm:
Any chance of uploading a Parquet file or a reproducible example?

**Comment by asfimport** [comment]
[ben w](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-16357541):
here you go: https://github.com/apache/spark/blob/master/examples/src/main/resources/users.parquet

**Comment by asfimport** [comment]
[Luke Higgins](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-16358362):
I will see what I can do to make a toy example of data that exhibits this error if another example is needed.

**Comment by asfimport** [comment]
[Luke Higgins](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-16358776):
In our nifi config we were able to find how to set parquet.avro.write-old-list-structure to false (suggested by Ryan Blue above but I didn't think we had that as an option).  I now can get a little further.
> >>>import pyarrow.parquet as pq
> 
> >>>pf = pq.ParquetFile(filename)
> 
> >>> pf.metadata
> <pyarrow._parquet.FileMetaData object at 0x7f6bf3588f98>
> created_by: parquet-mr version 1.8.2 (build c6522788629e590a53eb79874b95f6c3ff11f16c)
> num_columns: 45
> num_rows: 223240
> num_row_groups: 1
> format_version: 1.0
> serialized_size: 8483
> 
> >>table = pq.read_table(filename)
> 
> >>> table.to_pandas()
> Empty DataFrame
> Columns: [field1, ...field45]]  #fields are listed in output, just suppressing here
> Index: []
> 
> [0 rows x 45 columns]
 So I don't get the error on read_table but the converted df is empty (even though the ParquetFile.metadata has rows).

Any other thoughts on config changes?

**Comment by asfimport** [comment]
[Luke Higgins](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-16366947):
similarly, I get that scan_contents returns 0 as number of rows (which differs from the num_rows in metadata):

>>> import pyarrow.parquet as pq
>>> pf = pq.ParquetFile('test.parq')
>>> pf.metadata
<pyarrow._parquet.FileMetaData object at 0x7f74025a6868>
 created_by: parquet-mr version 1.8.2 (build c6522788629e590a53eb79874b95f6c3ff11f16c)
 num_columns: 45
 num_rows: 223240
 num_row_groups: 1
 format_version: 1.0
 serialized_size: 8483
>>> pf.scan_contents()
0

 

from the command line to test I do get the file to be read by parquet-tools correctly from:

<https://github.com/apache/parquet-mr/tree/master/parquet-tools>

**Comment by asfimport** [comment]
[Luke Higgins](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-16366951):
Is there any other setting I can give our team that uses the parquet-mr libraries that would allow the resultant parquet files to be able to be read by pyarrow.parquet ?

**Comment by asfimport** [comment]
[Wes McKinney](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-16367763) / @wesm:
I am unable to investigate in detail right now, someone will need to dig into the implementation to see what's wrong

**Comment by asfimport** [comment]
[Luke Higgins](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-16871847):
Just curious if this is being tracked here or elsewhere? 

Still see this in the latest version of pyarrow. 

I appreciate the work being done, not trying to nag, just curious if this is on a list to be worked eventually or has dropped off.  Thanks for all that all of you are doing!

**Comment by asfimport** [comment]
[Wes McKinney](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-16871855) / @wesm:
I haven't had the time to work on it. Having complete nested data support for Parquet is something that I would like to see happen eventually but I'm not sure when it will get done

**Comment by asfimport** [comment]
[Antoine Pitrou](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-17307912) / @pitrou:
@emkornfield This is outdated, right?

**Comment by asfimport** [comment]
[Micah Kornfield](https://issues.apache.org/jira/browse/PARQUET-1122?#comment-17314180) / @emkornfield:
Yes, all common types should not be readable (some caveats around FixedSizeList and i might be forgetting something else).  I'm going to close this.  `[~virtualluke]` please reopen if you are still seeing issues on pyarrow 3.0.
