### ISSUE TITLE
[C++][Parquet] Scanning fails with list columns

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#42811]
```python

>>> list_arr = pa.array([[1, 2], [3, 4, 5]])
>>> int_arr = pa.array([10, 11])
>>> table = pa.Table.from_arrays([int_arr, list_arr], ['ints', 'lists'])
>>> bio = io.BytesIO()
>>> pq.write_table(table, bio)
>>> bio.seek(0)
0
>>> reader = pq.ParquetReader()
>>> reader.open(bio)
>>> reader.scan_contents()
Traceback (most recent call last):
  File "<ipython-input-23-58e977f6d60b>", line 1, in <module>
    reader.scan_contents()
  File "_parquet.pyx", line 753, in pyarrow._parquet.ParquetReader.scan_contents
  File "error.pxi", line 79, in pyarrow.lib.check_status
ArrowIOError: Parquet error: Total rows among columns do not match
```

ScanFileContents() claims it returns the "number of semantic rows" but apparently it actually counts the number of physical elements?

**Reporter**: [Antoine Pitrou](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apitrou) / @pitrou

<sub>**Note**: *This issue was originally created as [PARQUET-1269](https://issues.apache.org/jira/browse/PARQUET-1269). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Deepak Majeti](https://issues.apache.org/jira/browse/PARQUET-1269?#comment-16448261) / @majetideepak:
Resolved in PARQUET-1272
