### ISSUE TITLE
[Packaging][GLib] How to install arrow-glib on alpine linux

### ISSUE THREAD

**Issue by NivathaSV8** [apache/arrow#43038]
### Describe the usage question you have. Please include as many useful details as  possible.

Hello I m trying to use `red-arrow` ruby gem on Alpine linux platform, which requires Apache Arrow Glib.
In the following document, package for debian is available. [libarrow-glib-dev]
https://arrow.apache.org/install/
Equivalent package for alpine couldn't be found.

Dockerfile
```
FROM ruby:3.2-alpine3.20

RUN apk --update add build-base tzdata

RUN apk add --no-cache --virtual=.build-dependencies \
  git \
  build-base \
  glib-dev \
  gobject-introspection-dev \
  apache-arrow-dev \
  libarrow

RUN mkdir /test
WORKDIR /test

COPY Gemfile /test/Gemfile
COPY Gemfile.lock /test/Gemfile.lock

RUN gem install bundler:2.5.10 && \
  bundle install --jobs=4

COPY . /test
```

Gemfile
```
source 'https://rubygems.org'

gem 'gobject-introspection', '~> 4.2', '>= 4.2.2'
gem 'glib2', '~> 4.2', '>= 4.2.2'
gem 'red-arrow'
```

Build Error
```
[+] Building 26.9s (12/13)                                                                                                               docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                     0.0s
 => => transferring dockerfile: 431B                                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/ruby:3.2-alpine3.20                                                                                   0.7s
 => [internal] load .dockerignore                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                          0.0s
 => [1/9] FROM docker.io/library/ruby:3.2-alpine3.20@sha256:50633162903fbf8fca9b97c4992fc304ab463afd941146b7df4b0250ed468708                             0.0s
 => [internal] load build context                                                                                                                        0.0s
 => => transferring context: 292B                                                                                                                        0.0s
 => CACHED [2/9] RUN apk --update add build-base tzdata                                                                                                  0.0s
 => CACHED [3/9] RUN apk add --no-cache --virtual=.build-dependencies   git   build-base   glib-dev   gobject-introspection-dev   apache-arrow-dev   li  0.0s
 => CACHED [4/9] RUN mkdir /test                                                                                                                         0.0s
 => CACHED [5/9] WORKDIR /test                                                                                                                           0.0s
 => [6/9] COPY Gemfile /test/Gemfile                                                                                                                     0.0s
 => [7/9] COPY Gemfile.lock /test/Gemfile.lock                                                                                                           0.0s
 => ERROR [8/9] RUN gem install bundler:2.5.10 &&   bundle install --jobs=4                                                                             26.1s
------
 > [8/9] RUN gem install bundler:2.5.10 &&   bundle install --jobs=4:
0.582 Successfully installed bundler-2.5.10
0.582 1 gem installed
1.589 Fetching gem metadata from https://rubygems.org/......
1.974 Resolving dependencies...
1.998 Fetching csv 3.3.0
2.005 Fetching extpp 0.1.1
2.006 Fetching fiddle 1.1.2
2.006 Fetching bigdecimal 3.1.8
2.082 Installing extpp 0.1.1
2.086 Installing fiddle 1.1.2 with native extensions
2.087 Installing csv 3.3.0
2.099 Installing bigdecimal 3.1.8 with native extensions
2.104 Fetching native-package-installer 1.1.9
2.122 Fetching pkg-config 1.5.6
2.151 Installing native-package-installer 1.1.9
2.172 Installing pkg-config 1.5.6
2.175 Fetching glib2 4.2.2
2.248 Installing glib2 4.2.2 with native extensions
16.66 Fetching gobject-introspection 4.2.2
16.73 Installing gobject-introspection 4.2.2 with native extensions
23.26 Fetching gio2 4.2.2
23.32 Installing gio2 4.2.2 with native extensions
24.91 Fetching red-arrow 16.1.0
24.98 Installing red-arrow 16.1.0 with native extensions
26.05 Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
26.05
26.05     current directory: /usr/local/bundle/gems/red-arrow-16.1.0/ext/arrow
26.05 /usr/local/bin/ruby extconf.rb
26.05 checking --enable-debug-build option... no
26.05 checking C++ compiler... g++
26.05 checking g++ version... 13.2 (gnu++17)
26.05 checking for --enable-debug-build option... no
26.05 checking for -Wall option to compiler... yes
26.05 checking for -Wcast-align option to compiler... yes
26.05 checking for -Wextra option to compiler... yes
26.05 checking for -Wformat=2 option to compiler... yes
26.05 checking for -Winit-self option to compiler... yes
26.05 checking for -Wlarger-than-65500 option to compiler... yes
26.05 checking for -Wmissing-declarations option to compiler... yes
26.05 checking for -Wmissing-format-attribute option to compiler... yes
26.05 checking for -Wmissing-include-dirs option to compiler... yes
26.05 checking for -Wmissing-noreturn option to compiler... yes
26.05 checking for -Wmissing-prototypes option to compiler... yes
26.05 checking for -Wnested-externs option to compiler... yes
26.05 checking for -Wold-style-definition option to compiler... yes
26.05 checking for -Wpacked option to compiler... yes
26.05 checking for -Wp,-D_FORTIFY_SOURCE=2 option to compiler... yes
26.05 checking for -Wpointer-arith option to compiler... yes
26.05 checking for -Wundef option to compiler... yes
26.05 checking for -Wout-of-line-declaration option to compiler... no
26.05 checking for -Wunsafe-loop-optimizations option to compiler... yes
26.05 checking for -Wwrite-strings option to compiler... yes
26.05 checking for Homebrew... no
26.05 checking for Homebrew... no
26.05 checking for arrow version (>= 16.0.0)... yes (16.1.0)
26.05 checking for arrow-glib version (>= 16.1.0)... no (nonexistent)
26.05 *** extconf.rb failed ***
26.05 Could not create Makefile due to some reason, probably lack of necessary
26.05 libraries and/or headers.  Check the mkmf.log file for more details.  You may
26.05 need configuration options.
26.05
26.05 Provided configuration options:
26.05   --with-opt-dir
26.05   --without-opt-dir
26.05   --with-opt-include
26.05   --without-opt-include=${opt-dir}/include
26.05   --with-opt-lib
26.05   --without-opt-lib=${opt-dir}/lib
26.05   --with-make-prog
26.05   --without-make-prog
26.05   --srcdir=.
26.05   --curdir
26.05   --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
26.05   --enable-debug-build
26.05   --disable-debug-build
26.05   --enable-debug-build
26.05   --disable-debug-build
26.05   --with-pkg-config
26.05   --without-pkg-config
26.05   --with-override-variables
26.05   --without-override-variables
26.05
26.05 To see why this extension failed to compile, please check the mkmf.log which can
26.05 be found here:
26.05
26.05 /usr/local/bundle/extensions/aarch64-linux-musl/3.2.0/red-arrow-16.1.0/mkmf.log
26.05
26.05 extconf failed, exit code 1
26.05
26.05 Gem files will remain installed in /usr/local/bundle/gems/red-arrow-16.1.0 for
26.05 inspection.
26.05 Results logged to
26.05 /usr/local/bundle/extensions/aarch64-linux-musl/3.2.0/red-arrow-16.1.0/gem_make.out
26.05
26.05   /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:119:in `run'
26.05   /usr/local/lib/ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:28:in `build'
26.05   /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:187:in `build_extension'
26.05 /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:221:in `block in
26.05 build_extensions'
26.05   /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in `each'
26.05   /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in `build_extensions'
26.05   /usr/local/lib/ruby/3.2.0/rubygems/installer.rb:846:in `build_extensions'
26.05 /usr/local/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:72:in
26.05 `build_extensions'
26.05   /usr/local/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:28:in `install'
26.05   /usr/local/lib/ruby/3.2.0/bundler/source/rubygems.rb:202:in `install'
26.05   /usr/local/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:54:in `install'
26.05 /usr/local/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:16:in
26.05 `install_from_spec'
26.05 /usr/local/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:156:in
26.05 `do_install'
26.05 /usr/local/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:147:in
26.05 `block in worker_pool'
26.05   /usr/local/lib/ruby/3.2.0/bundler/worker.rb:62:in `apply_func'
26.05   /usr/local/lib/ruby/3.2.0/bundler/worker.rb:57:in `block in process_queue'
26.05   /usr/local/lib/ruby/3.2.0/bundler/worker.rb:54:in `loop'
26.05   /usr/local/lib/ruby/3.2.0/bundler/worker.rb:54:in `process_queue'
26.05 /usr/local/lib/ruby/3.2.0/bundler/worker.rb:90:in `block (2 levels) in
26.05 create_threads'
26.05
26.05 An error occurred while installing red-arrow (16.1.0), and Bundler cannot
26.05 continue.
26.05
26.05 In Gemfile:
26.05   red-arrow
------
Dockerfile:19
--------------------
  18 |
  19 | >>> RUN gem install bundler:2.5.10 && \
  20 | >>>   bundle install --jobs=4
  21 |
--------------------
ERROR: failed to solve: process "/bin/sh -c gem install bundler:2.5.10 &&   bundle install --jobs=4" did not complete successfully: exit code: 5

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/gp4ry1mh52vzwwsb6fyx9aynr
```

Kindly let me know if Apache Arrow Glib package for Alpine is available. Or kindly let me know how to install without using package to solve the above error.

### Component(s)

GLib

**Comment by kou** [comment]
> Kindly let me know if Apache Arrow Glib package for Alpine is available.

It doesn't exist: https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/apache-arrow/APKBUILD?ref_type=heads

Could you send a feature request to Alpine Linux? Or could you send a merge request to build Apache Arrow GLib?

FYI: How to build Apache Arrow GLib in .deb: https://github.com/apache/arrow/blob/b0d8d82de65c55a2ec975ed39f01e3f0d5f9e7ec/dev/tasks/linux-packages/apache-arrow/debian/rules#L61-L75

> Or kindly let me know how to install without using package to solve the above error.

```dockerfile
FROM ruby:3.2-alpine3.20

RUN mkdir /test
WORKDIR /test

COPY Gemfile /test/Gemfile
COPY Gemfile.lock /test/Gemfile.lock

RUN apk add --no-cache \
  glib \
  gobject-introspection \
  libarrow \
  libarrow_acero && \
  apk add --no-cache --virtual=.build-dependencies\
  apache-arrow-dev \
  build-base \
  glib-dev \
  gobject-introspection-dev \
  meson \
  pkgconf \
  samurai && \
  wget "https://www.apache.org/dyn/closer.lua?action=download&filename=arrow/arrow-16.1.0/apache-arrow-16.1.0.tar.gz" && \
  tar xf apache-arrow-16.1.0.tar.gz && \
  meson setup \
    apache-arrow-16.1.0/c_glib.build \
    apache-arrow-16.1.0/c_glib \
    --prefix=/usr \
    --buildtype=minsize && \
  meson install -C apache-arrow-16.1.0/c_glib.build && \
  rm -rf apache-arrow-16.1.0 && \
  gem install bundler:2.5.10 && \
  MAKEFLAGS=-j4 bundle install --jobs=4 && \
  apk del .build-dependencies

COPY . /test
```

**Comment by NivathaSV8** [comment]
@kou Thank you for the comment.
With the above code, for now I was able to install 'red-arrow' gem.

I will create PR for Apache Arrow GLib.

**Comment by kou** [comment]
Thanks.
I close this.
