### ISSUE TITLE
[CI][C++] test-ubuntu-22.04-cpp-emscripten fails with `memory access out of bounds` on arrow-acero-hash-join-node-test

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#43056]
### Describe the bug, including details regarding any error messages, version, and platform.

[test-ubuntu-22.04-cpp-emscripten](https://github.com/ursacomputing/crossbow/actions/runs/9671504883/job/26682244262) fails with:

```
[       OK ] HashJoin.ChainedIntegerHashJoins (211 ms)
[ RUN      ] HashJoin.ManyJoins
/build/cpp/debug/arrow-acero-hash-join-node-test.js:138
      throw ex;
      ^
RuntimeError: memory access out of bounds
    at arrow-acero-hash-join-node-test.wasm.dlmalloc (wasm://wasm/arrow-acero-hash-join-node-test.wasm-0c5ecc4a:wasm-function[31169]:0x2023c95)
    at arrow-acero-hash-join-node-test.wasm.operator new(unsigned long) (wasm://wasm/arrow-acero-hash-join-node-test.wasm-0c5ecc4a:wasm-function[33617]:0x206b5c0)
    at arrow-acero-hash-join-node-test.wasm.std::__2::vector<arrow::compute::ResizableArrayData, std::__2::allocator<arrow::compute::ResizableArrayData>>::__append(unsigned long) (wasm://wasm/arrow-acero-hash-join-node-test.wasm-0c5ecc4a:wasm-function[12664]:0x9e131f)
    at arrow-acero-hash-join-node-test.wasm.std::__2::vector<arrow::compute::ResizableArrayData, std::__2::allocator<arrow::compute::ResizableArrayData>>::resize(unsigned long) (wasm://wasm/arrow-acero-hash-join-node-test.wasm-0c5ecc4a:wasm-function[12663]:0x9e1173)
    at arrow-acero-hash-join-node-test.wasm.arrow::compute::ExecBatchBuilder::AppendSelected(arrow::MemoryPool*, arrow::compute::ExecBatch const&, int, unsigned short const*, int, int const*) (wasm://wasm/arrow-acero-hash-join-node-test.wasm-0c5ecc4a:wasm-function[12662]:0x9e0dda)
    at arrow-acero-hash-join-node-test.wasm.arrow::acero::JoinResultMaterialize::Append(arrow::compute::ExecBatch const&, int, unsigned short const*, unsigned int const*, unsigned int const*, int*) (wasm://wasm/arrow-acero-hash-join-node-test.wasm-0c5ecc4a:wasm-function[3665]:0x2952d8)
    at invoke_viiiiiiii (/build/cpp/debug/arrow-acero-hash-join-node-test.js:6049:29)
    at arrow-acero-hash-join-node-test.wasm.arrow::acero::JoinProbeProcessor::OnNextBatch(long long, arrow::compute::ExecBatch const&, arrow::util::TempVectorStack*, std::__2::vector<arrow::compute::KeyColumnArray, std::__2::allocator<arrow::compute::KeyColumnArray>>*) (wasm://wasm/arrow-acero-hash-join-node-test.wasm-0c5ecc4a:wasm-function[3686]:0x29f96b)
    at invoke_viijiii (/build/cpp/debug/arrow-acero-hash-join-node-test.js:6680:29)
    at arrow-acero-hash-join-node-test.wasm.arrow::acero::SwissJoin::ProbeSingleBatch(unsigned long, arrow::compute::ExecBatch) (wasm://wasm/arrow-acero-hash-join-node-test.wasm-0c5ecc4a:wasm-function[3716]:0x2a7bcc)
Node.js v18.20.3
```

### Component(s)

C++, Continuous Integration

**Comment by raulcd** [comment]
it seems there was an issue already for this: https://github.com/apache/arrow/issues/43040
Closing as duplicate.
