### ISSUE TITLE
[Archery][Dev] Update archery to support same setuptools-scm version than pyarrow

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#43114]
### Describe the enhancement requested

Trying to use archery with the latest `setuptools-scm` which is required for pyarrow fails.
For the release I tried to submit some jobs with:
```
archery crossbow submit --job-prefix maint-17.0.0-nightly-tests --group nightly-tests --arrow-branch maint-17.0.0 --no-fetch
```
and I got the following failure
```
DEBUG:archery:Executing `['git', '-C', '/home/raulcd/code/arrow', 'rev-parse', '--show-toplevel']`
Traceback (most recent call last):
  File "/home/raulcd/code/pyarrow-dev/bin/archery", line 33, in <module>
    sys.exit(load_entry_point('archery', 'console_scripts', 'archery')())
  File "/home/raulcd/code/pyarrow-dev/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/raulcd/code/pyarrow-dev/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/raulcd/code/pyarrow-dev/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/raulcd/code/pyarrow-dev/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/raulcd/code/pyarrow-dev/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/raulcd/code/pyarrow-dev/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/raulcd/code/pyarrow-dev/lib/python3.10/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/raulcd/code/arrow/dev/archery/archery/crossbow/cli.py", line 131, in submit
    target = Target.from_repo(arrow, remote=arrow_remote, branch=arrow_branch,
  File "/home/raulcd/code/arrow/dev/archery/archery/crossbow/core.py", line 837, in from_repo
    version = get_version(repo.path)
  File "/home/raulcd/code/arrow/dev/archery/archery/crossbow/core.py", line 754, in get_version
    version = parse_git_version(root, **kwargs)
TypeError: parse() missing 1 required positional argument: 'config'
```
This was in the virtualenv I use for `pyarrow` where we require `setuptools-scm==8.1.0`. I've changed to a different virtualenv that uses `setuptools-scm==7.1.0` and worked successfully.

We should be able to use the same version of `setuptools-scm` for `archery` and `pyarrow`

### Component(s)

Archery, Developer Tools

**Comment by llama90** [comment]
take

**Comment by kou** [comment]
Issue resolved by pull request 43156
https://github.com/apache/arrow/pull/43156
