### ISSUE TITLE
[Release] Occasional "Digest::Base cannot be directly inherited in Ruby" in post-03-binary.sh

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow#43152]
### Describe the bug, including details regarding any error messages, version, and platform.

```
Uploading: almalinux -   0.0% [0/1] 00:00:00 00:00:00  0/s#<Thread:0x0000ffffa188bf48 /host/binary-task.rb:43 run> terminated with exception (report_on_exception is true):
/usr/lib/ruby/3.1.0/digest.rb:49:in `new': Digest::Base cannot be directly inherited in Ruby (RuntimeError)
	from /usr/lib/ruby/3.1.0/digest.rb:49:in `file'
	from /host/binary-task.rb:397:in `block in upload'
	from /host/binary-task.rb:529:in `with_retry'
	from /host/binary-task.rb:396:in `upload'
	from /host/binary-task.rb:716:in `block (3 levels) in upload'
	from /host/binary-task.rb:587:in `pull'
	from /host/binary-task.rb:715:in `block (2 levels) in upload'
	from /host/binary-task.rb:47:in `block (3 levels) in initialize'
	from /host/binary-task.rb:44:in `loop'
	from /host/binary-task.rb:44:in `block (2 levels) in initialize'
```

I believe as per issues like https://github.com/aerospike/aerospike-client-ruby/issues/45 that we should be using `Digest(:SHA256)` and not `Digest::SHA256`

### Component(s)

Release

**Comment by kou** [comment]
Issue resolved by pull request 43154
https://github.com/apache/arrow/pull/43154

**Comment by lidavidm** [comment]
Thanks @kou!
