### ISSUE TITLE
[Go] parquet/pqarrow: panic: unaligned 64-bit atomic operation

### ISSUE THREAD

**Issue by powersj** [apache/arrow#43186]
### Describe the bug, including details regarding any error messages, version, and platform.

On a 32-bit test, when calling a write buffered with the pqarrow's FileWriter I see a panic due to unaligned operation. I believe this is due to the various `atomic.AddInt64` calls, in this case specifically [this one](https://github.com/apache/arrow/blob/5c64f74cf2840b37893d8158475676c290fa6615/go/parquet/pqarrow/path_builder.go#L509), but this appears to be used by both `pathBuilder` and `multipathLevelBuilder`.

From the Go docs on this function:

> AddInt64 atomically adds delta to *addr and returns the new value. Consider using the more ergonomic and less error-prone [Int64.Add](https://pkg.go.dev/sync/atomic#Int64.Add) instead (particularly if you target 32-bit platforms; see the bugs section).

From the bugs section:

> On ARM, 386, and 32-bit MIPS, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically via the primitive atomic functions (types [Int64](https://pkg.go.dev/sync/atomic#Int64) and [Uint64](https://pkg.go.dev/sync/atomic#Uint64) are automatically aligned). The first word in an allocated struct, array, or slice; in a global variable; or in a local variable (because the subject of all atomic operations will escape to the heap) can be relied upon to be 64-bit aligned.

## Steps to reproduce

You can reproduce this by using `GOARCH=386`:

```sh
git clone git@github.com:powersj/telegraf -b feat/parquet-serializer
cd telegraf
GOARCH=386 go test -v ./plugins/outputs/parquet/...
```

## Trace

```s
=== FAIL: plugins/outputs/parquet TestCases (0.00s)
panic: unaligned 64-bit atomic operation [recovered]
        panic: unaligned 64-bit atomic operation

goroutine 7 [running]:
testing.tRunner.func1.2({0x902af40, 0x93eb378})
        /usr/local/go/src/testing/testing.go:1631 +0x2a3
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1634 +0x434
panic({0x902af40, 0x93eb378})
        /usr/local/go/src/runtime/panic.go:770 +0x103
runtime/internal/atomic.panicUnaligned()
        /usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Xadd64(0xb43e9ac, 0xffffffffffffffff)
        /usr/local/go/src/runtime/internal/atomic/atomic_386.s:125 +0x11
github.com/apache/arrow/go/v16/parquet/pqarrow.(*multipathLevelBuilder).Release(0xb43e960)
        /go/pkg/mod/github.com/apache/arrow/go/v16@v16.1.0/parquet/pqarrow/path_builder.go:509 +0x3a
github.com/apache/arrow/go/v16/parquet/pqarrow.(*arrowColumnWriter).Write(0xb275c40, {0x93f7990, 0xb3c0d38})
        /go/pkg/mod/github.com/apache/arrow/go/v16@v16.1.0/parquet/pqarrow/encode_arrow.go:198 +0x1b9
github.com/apache/arrow/go/v16/parquet/pqarrow.(*FileWriter).WriteColumnChunked(0xb3e3200, 0xb3b4f30, 0x0, 0x1)
        /go/pkg/mod/github.com/apache/arrow/go/v16@v16.1.0/parquet/pqarrow/file_writer.go:330 +0xf7
github.com/apache/arrow/go/v16/parquet/pqarrow.(*FileWriter).WriteColumnData(0xb3e3200, {0x9401564, 0xb3b49f0})
        /go/pkg/mod/github.com/apache/arrow/go/v16@v16.1.0/parquet/pqarrow/file_writer.go:339 +0x109
github.com/apache/arrow/go/v16/parquet/pqarrow.(*FileWriter).WriteBuffered(0xb3e3200, {0x9400770, 0xb3c7de0})
        /go/pkg/mod/github.com/apache/arrow/go/v16@v16.1.0/parquet/pqarrow/file_writer.go:203 +0x413
github.com/influxdata/telegraf/plugins/outputs/parquet.(*Parquet).Write(0xb275f70, {0xb442520, 0x1, 0x1})
        /go/src/github.com/influxdata/telegraf/plugins/outputs/parquet/parquet.go:119 +0x5d9
github.com/influxdata/telegraf/plugins/outputs/parquet.TestCases.func1(0xb362508)
        /go/src/github.com/influxdata/telegraf/plugins/outputs/parquet/parquet_test.go:132 +0x118
testing.tRunner(0xb362508, 0xb3c7b00)
        /usr/local/go/src/testing/testing.go:1689 +0x125
created by testing.(*T).Run in goroutine 6
        /usr/local/go/src/testing/testing.go:1742 +0x3b9

DONE 7368 tests, 277 skipped, 2 failures in 133.817s
```

### Component(s)

Go

**Comment by joellubi** [comment]
Thanks for raising this issue and sharing your findings  @powersj. I'll try to reproduce the issue using the test in the PR you linked and will share any updates here.

**Comment by powersj** [comment]
@joellubi,

Here is a test case you can use outside of my branch :)

```go
package main

import (
	"os"
	"time"

	"github.com/apache/arrow/go/v16/arrow"
	"github.com/apache/arrow/go/v16/arrow/array"
	"github.com/apache/arrow/go/v16/arrow/memory"
	"github.com/apache/arrow/go/v16/parquet"
	"github.com/apache/arrow/go/v16/parquet/pqarrow"
)

type Metric struct {
	Time     time.Time
	CPUUsage float64
	Memory   float64
}

func main() {
	file, err := os.OpenFile("metrics.parquet", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0640)
	if err != nil {
		panic(err)
	}
	defer file.Close()

	pool := memory.NewCheckedAllocator(memory.NewGoAllocator())

	fields := []arrow.Field{
		{Name: "time", Type: arrow.FixedWidthTypes.Timestamp_ms},
		{Name: "cpu_usage", Type: arrow.PrimitiveTypes.Float64},
		{Name: "memory", Type: arrow.PrimitiveTypes.Float64},
	}
	schema := arrow.NewSchema(fields, nil)

	builder := array.NewRecordBuilder(pool, schema)
	defer builder.Release()

	metrics := []Metric{
		{Time: time.Now(), CPUUsage: 5.5, Memory: 1024.0},
	}

	for _, metric := range metrics {
		builder.Field(0).(*array.TimestampBuilder).Append(arrow.Timestamp(metric.Time.UnixNano() / int64(time.Millisecond)))
		builder.Field(1).(*array.Float64Builder).Append(metric.CPUUsage)
		builder.Field(2).(*array.Float64Builder).Append(metric.Memory)
	}

	record := builder.NewRecord()
	defer record.Release()

	parquetWriteProps := parquet.NewWriterProperties()
	arrowWriteProps := pqarrow.NewArrowWriterProperties()
	parquetFileWriter, err := pqarrow.NewFileWriter(record.Schema(), file, parquetWriteProps, arrowWriteProps)
	if err != nil {
		panic(err)
	}
	defer parquetFileWriter.Close()

	err = parquetFileWriter.Write(record)
	if err != nil {
		panic(err)
	}
}
```

```shell
❯ GOARCH=386 go run .
panic: unaligned 64-bit atomic operation

goroutine 1 [running]:
runtime/internal/atomic.panicUnaligned()
	/usr/lib/go/src/runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Xadd64(0x9eb246c, 0xffffffffffffffff)
	/usr/lib/go/src/runtime/internal/atomic/atomic_386.s:125 +0x11
github.com/apache/arrow/go/v16/parquet/pqarrow.(*multipathLevelBuilder).Release(0x9eb2420)
	/home/powersj/go/pkg/mod/github.com/apache/arrow/go/v16@v16.0.0-20240412130436-48a9639bb0ba/parquet/pqarrow/path_builder.go:509 +0x3a
github.com/apache/arrow/go/v16/parquet/pqarrow.(*arrowColumnWriter).Write(0x9e4dd10, {0x8f70188, 0x9e7b260})
	/home/powersj/go/pkg/mod/github.com/apache/arrow/go/v16@v16.0.0-20240412130436-48a9639bb0ba/parquet/pqarrow/encode_arrow.go:198 +0x1b9
github.com/apache/arrow/go/v16/parquet/pqarrow.(*FileWriter).WriteColumnChunked(0x9e9a640, 0x9e89710, 0x0, 0x1)
	/home/powersj/go/pkg/mod/github.com/apache/arrow/go/v16@v16.0.0-20240412130436-48a9639bb0ba/parquet/pqarrow/file_writer.go:330 +0xf7
github.com/apache/arrow/go/v16/parquet/pqarrow.(*FileWriter).WriteColumnData(0x9e9a640, {0x8f78eb0, 0x9e89590})
	/home/powersj/go/pkg/mod/github.com/apache/arrow/go/v16@v16.0.0-20240412130436-48a9639bb0ba/parquet/pqarrow/file_writer.go:339 +0x109
github.com/apache/arrow/go/v16/parquet/pqarrow.(*FileWriter).Write(0x9e9a640, {0x8f78218, 0x9ea81c0})
	/home/powersj/go/pkg/mod/github.com/apache/arrow/go/v16@v16.0.0-20240412130436-48a9639bb0ba/parquet/pqarrow/file_writer.go:242 +0x280
main.main()
	/home/powersj/test/main.go:60 +0x5c5
exit status 2
```

**Comment by joellubi** [comment]
@powersj If you have a chance, could you try running your tests with the changes in #43206 to confirm they resolve the specific issue? If so, the plan is to merge that PR and then prioritize some work for broader support for the architecture.

**Comment by powersj** [comment]
Looks good, thank you for the quick turn around!

```go
replace github.com/apache/arrow/go/v17 => github.com/joellubi/arrow/go/v17 v17.0.0-20240710192017-658fbb0785ed
```

```shell
❯ go mod tidy
go: downloading github.com/joellubi/arrow/go/v17 v17.0.0-20240710192017-658fbb0785ed
❯ GOARCH=386 go test -v ./plugins/outputs/parquet/...
=== RUN   TestCases
=== RUN   TestCases/basic_single_metric
=== RUN   TestCases/mix_of_tags_and_fields
=== RUN   TestCases/null_values
=== RUN   TestCases/data_types
--- PASS: TestCases (0.00s)
    --- PASS: TestCases/basic_single_metric (0.00s)
    --- PASS: TestCases/mix_of_tags_and_fields (0.00s)
    --- PASS: TestCases/null_values (0.00s)
    --- PASS: TestCases/data_types (0.00s)
=== RUN   TestRotation
--- PASS: TestRotation (2.00s)
=== RUN   TestOmitTimestamp
--- PASS: TestOmitTimestamp (0.00s)
PASS
ok  	github.com/influxdata/telegraf/plugins/outputs/parquet	2.053s
```
