### ISSUE TITLE
[pyarrow] support for casting from python's ctypes (or directly from byte objects)

### ISSUE THREAD

**Issue by ReubenM** [apache/arrow#43240]
### Describe the enhancement requested

I'm working with large byte objects from stdin and would like an efficient (without intermediate copying) way to cast to pyarrow objects from sub-chunks of the byte objects. I can't seem to cast pyarrow directly from ranges within a bytes object or from ctype pointers to the byte range. But I'm not very familiar with pyarrow, so perhaps there is a way I've missed in documentation or just don't have a good understanding of the API yet.

For example:
```
>>> import pyarrow as pa

>>> from ctypes import *

>>> pa.scalar( cast( b'\xaa\xbb\xcc\xdd', POINTER( c_uint32 )).contents, type = pa.uint32() )
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    pa.scalar( cast( b'\xaa\xbb\xcc\xdd', POINTER( c_uint32 )).contents, type = pa.uint32() )
  File "pyarrow/scalar.pxi", line 1212, in pyarrow.lib.scalar
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not convert c_uint(3721182122) with type c_uint: tried to convert to uint32
```

### Component(s)

Python

**Comment by thisisnic** [comment]
This issue has been closed because there has been no activity for the 14 days since the stale warning. Feel free to reopen if this has been closed in error.
