### ISSUE TITLE
[CI][Dev][Release] CI jobs for Source Release and Merge Script are failing after bumping versions

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#43284]
### Describe the bug, including details regarding any error messages, version, and platform.

After executing the bump-versions script after the release, which generates the following two commits:
https://github.com/apache/arrow/commit/55ce352be026c77dd6fd993c735fa58c3b8f4a12
https://github.com/apache/arrow/commit/18319d30e558af72f72ea58c7d7996e781777643

The Source Release and Merge Script CI jobs are failing with:
```
PostBumpVersionsTest: 
  test_deb_package_names[bump_type: nil]:		E
===============================================================================
Error: test_deb_package_names[bump_type: nil](PostBumpVersionsTest):
  CommandRunnable::Error: Failed to run: dev/release/post-12-bump-versions.sh 18.0.0 19.0.0
  stdout:
   Updating .deb package names for 19.0.0
  /private/var/folders/xz/lz5thm6s3vb1vdkk77vmkgbr0000gn/T/d20240716-2671-jtxceq/arrow/dev/tasks/linux-packages/apache-arrow /private/var/folders/xz/lz5thm6s3vb1vdkk77vmkgbr0000gn/T/d20240716-2671-jtxceq/arrow
  
  stderr:
   fatal: bad source, source=dev/tasks/linux-packages/apache-arrow/debian*/lib*1800.install, destination=dev/tasks/linux-packages/apache-arrow/debian*/lib*1900.install
/Users/runner/work/arrow/arrow/dev/release/test-helper.rb:47:in `sh'
/Users/runner/work/arrow/arrow/dev/release/post-12-bump-versions-test.rb:70:in `bump_versions'
/Users/runner/work/arrow/arrow/dev/release/post-12-bump-versions-test.rb:361:in `test_deb_package_names'
     358:   def test_deb_package_names
     359:     omit_on_release_branch unless bump_type.nil?
     360:     current_commit = git_current_commit
  => 361:     stdout = bump_versions("DEB_PACKAGE_NAMES")
     362:     changes = parse_patch(git("log", "-p", "#{current_commit}.."))
     363:     sampled_changes = changes.collect do |change|
     364:       first_hunk = change[:hunks][0]
/Users/runner/work/arrow/arrow/dev/release/post-12-bump-versions-test.rb:35:in `block (2 levels) in setup'
/Users/runner/work/arrow/arrow/dev/release/post-12-bump-versions-test.rb:31:in `chdir'
/Users/runner/work/arrow/arrow/dev/release/post-12-bump-versions-test.rb:31:in `block in setup'
/Users/runner/hostedtoolcache/Ruby/3.3.4/arm64/lib/ruby/3.3.0/tmpdir.rb:99:in `mktmpdir'
/Users/runner/work/arrow/arrow/dev/release/post-12-bump-versions-test.rb:28:in `setup'
===============================================================================
: (1.953008)
  test_deb_package_names[bump_type: :minor]:		.: (1.839936)
  test_deb_package_names[bump_type: :patch]:		.: (1.782844)
  test_linux_packages:					.: (2.743860)
  test_version_post_tag[next_release_type: :major]:	.: (23.563749)
  test_version_post_tag[next_release_type: :minor]:	.: (17.358402)
  test_version_post_tag[next_release_type: :patch]:	.: (17.056213)
PrepareTest: 
  test_deb_package_names[release_type: nil]:		.: (2.173847)
  test_deb_package_names[release_type: :major]:		E
===============================================================================
Error: test_deb_package_names[release_type: :major](PrepareTest):
  CommandRunnable::Error: Failed to run: dev/release/01-prepare.sh 19.0.0 20.0.0 0
  stdout:
   Updating .deb package names for 19.0.0
  /private/var/folders/xz/lz5thm6s3vb1vdkk77vmkgbr0000gn/T/d20240716-2671-bnthe2/arrow/dev/tasks/linux-packages/apache-arrow /private/var/folders/xz/lz5thm6s3vb1vdkk77vmkgbr0000gn/T/d20240716-2671-bnthe2/arrow
  
  stderr:
   fatal: bad source, source=dev/tasks/linux-packages/apache-arrow/debian*/lib*1800.install, destination=dev/tasks/linux-packages/apache-arrow/debian*/lib*1900.install
/Users/runner/work/arrow/arrow/dev/release/test-helper.rb:47:in `sh'
/Users/runner/work/arrow/arrow/dev/release/01-prepare-test.rb:51:in `prepare'
/Users/runner/work/arrow/arrow/dev/release/01-prepare-test.rb:58:in `test_deb_package_names'
     55:   def test_deb_package_names
     56:     omit_on_release_branch
     57:     current_commit = git_current_commit
  => 58:     stdout = prepare("DEB_PACKAGE_NAMES")
     59:     changes = parse_patch(git("log", "-p", "#{current_commit}.."))
     60:     sampled_changes = changes.collect do |change|
     61:       first_hunk = change[:hunks][0]
/Users/runner/work/arrow/arrow/dev/release/01-prepare-test.rb:34:in `block (2 levels) in setup'
/Users/runner/work/arrow/arrow/dev/release/01-prepare-test.rb:31:in `chdir'
/Users/runner/work/arrow/arrow/dev/release/01-prepare-test.rb:31:in `block in setup'
/Users/runner/hostedtoolcache/Ruby/3.3.4/arm64/lib/ruby/3.3.0/tmpdir.rb:99:in `mktmpdir'
/Users/runner/work/arrow/arrow/dev/release/01-prepare-test.rb:28:in `setup'
===============================================================================
: (2.088267)
  test_deb_package_names[release_type: :minor]:		E
===============================================================================
Error: test_deb_package_names[release_type: :minor](PrepareTest):
  CommandRunnable::Error: Failed to run: dev/release/01-prepare.sh 18.1.0 19.0.0 0
  stdout:
   Updating .deb package names for 18.1.0
  /private/var/folders/xz/lz5thm6s3vb1vdkk77vmkgbr0000gn/T/d20240716-2671-us0rjr/arrow/dev/tasks/linux-packages/apache-arrow /private/var/folders/xz/lz5thm6s3vb1vdkk77vmkgbr0000gn/T/d20240716-2671-us0rjr/arrow
  
  stderr:
   fatal: bad source, source=dev/tasks/linux-packages/apache-arrow/debian*/lib*1800.install, destination=dev/tasks/linux-packages/apache-arrow/debian*/lib*1801.install
/Users/runner/work/arrow/arrow/dev/release/test-helper.rb:47:in `sh'
/Users/runner/work/arrow/arrow/dev/release/01-prepare-test.rb:51:in `prepare'
/Users/runner/work/arrow/arrow/dev/release/01-prepare-test.rb:58:in `test_deb_package_names'
     55:   def test_deb_package_names
     56:     omit_on_release_branch
     57:     current_commit = git_current_commit
  => 58:     stdout = prepare("DEB_PACKAGE_NAMES")
     59:     changes = parse_patch(git("log", "-p", "#{current_commit}.."))
     60:     sampled_changes = changes.collect do |change|
     61:       first_hunk = change[:hunks][0]
/Users/runner/work/arrow/arrow/dev/release/01-prepare-test.rb:34:in `block (2 levels) in setup'
/Users/runner/work/arrow/arrow/dev/release/01-prepare-test.rb:31:in `chdir'
/Users/runner/work/arrow/arrow/dev/release/01-prepare-test.rb:31:in `block in setup'
/Users/runner/hostedtoolcache/Ruby/3.3.4/arm64/lib/ruby/3.3.0/tmpdir.rb:99:in `mktmpdir'
/Users/runner/work/arrow/arrow/dev/release/01-prepare-test.rb:28:in `setup'
```

### Component(s)

Continuous Integration, Developer Tools, Release

**Comment by kou** [comment]
Hmm. Do you have the "MINOR: [Release] Update .deb package names for 18.0.0" commit like https://github.com/apache/arrow/commit/e37b2ac9f8f5e813b9dac22a8072028c62c8e53a on local? If you have it, could you push it to the main branch?

**Comment by raulcd** [comment]
It seems this:  https://github.com/apache/arrow/pull/41859 introduced an issue on the `post-12-bump-versions.sh` script. I've created a PR and have used the change to push https://github.com/apache/arrow/commit/c66b3f149f92e1fae0b33cc63c6093db2deedd29

**Comment by kou** [comment]
Issue resolved by pull request 43294
https://github.com/apache/arrow/pull/43294
