### ISSUE TITLE
Missing alias type when calling pyarrow.type_for_alias() for fixed_size_binary[]

### ISSUE THREAD

**Issue by davlee1972** [apache/arrow#43312]
### Describe the enhancement requested

I'm trying to define a schema in a yaml config file using pyarrow aliases, but in one use case I have a binary column for the schema.

I tried using "fixed_size_binary[8]" for an alias and it is missing..

Here's a working example for date32..

```
>>> b = pa.date32()
>>> str(b)
'date32[day]'
>>> pa.type_for_alias("date32[day]")
DataType(date32[day])

```

Here's the non-working example for fixed size binary.
```
>>> a = pa.binary(8)
>>> str(a)
'fixed_size_binary[8]'
>>> pa.type_for_alias("fixed_size_binary[8]")
Traceback (most recent call last):
  File "pyarrow\\types.pxi", line 5266, in pyarrow.lib.type_for_alias
KeyError: 'fixed_size_binary[8]'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow\\types.pxi", line 5268, in pyarrow.lib.type_for_alias
ValueError: No type alias for fixed_size_binary[8]
```

Variable sized binary does work..
```
>>> c = pa.binary()
>>> str(c)
'binary'
>>> pa.type_for_alias("binary")
DataType(binary)
```

### Component(s)

Python

**Comment by davlee1972** [comment]
If possible could we support two aliases for this?

fixed_sized_binary[8]
and
binary[8]

For float we have two aliases:
float
and
float32

**Comment by davlee1972** [comment]
Opened a replacement issue https://github.com/apache/arrow/issues/43858 to support other types including binary.
