### ISSUE TITLE
[Java] `new RootAllocator()` occasionally  report error `java.lang.NoSuchFieldError: chunkSize`

### ISSUE THREAD

**Issue by xinyiZzz** [apache/arrow#43491]
### Describe the bug, including details regarding any error messages, version, and platform.

Hi,

`new RootAllocator()` occasionally reports an error, I looked through other issues and guess that the versions of `Netty` and `Arrow` are incompatible, could this be the reason for the error?

Arrow version: 15.0.2
Netty version: 4.1.104.Final

I am trying to upgrade Arrow 17.0.0 to see if it can solve the problem.

Thanks.

```
java.lang.NoSuchFieldError: chunkSize
        at io.netty.buffer.PooledByteBufAllocatorL$InnerAllocator.<init>(PooledByteBufAllocatorL.java:153) ~[lakesoul-io-java-2.6.1-shaded.jar:4.1.104.Final]
        at io.netty.buffer.PooledByteBufAllocatorL.<init>(PooledByteBufAllocatorL.java:49) ~[lakesoul-io-java-2.6.1-shaded.jar:4.1.104.Final]
        at org.apache.arrow.memory.NettyAllocationManager.<clinit>(NettyAllocationManager.java:51) ~[arrow-memory-netty-15.0.2.jar:15.0.2]
        at org.apache.arrow.memory.DefaultAllocationManagerFactory.<clinit>(DefaultAllocationManagerFactory.java:26) ~[arrow-memory-netty-15.0.2.jar:15.0.2]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at org.apache.arrow.memory.DefaultAllocationManagerOption.getFactory(DefaultAllocationManagerOption.java:108) ~[arrow-memory-core-15.0.2.jar:15.0.2]
        at org.apache.arrow.memory.DefaultAllocationManagerOption.getDefaultAllocationManagerFactory(DefaultAllocationManagerOption.java:98) ~[arrow-memory-core-15.0.2.jar:15.0.2]
        at org.apache.arrow.memory.BaseAllocator$Config.getAllocationManagerFactory(BaseAllocator.java:773) ~[arrow-memory-core-15.0.2.jar:15.0.2]
        at org.apache.arrow.memory.ImmutableConfig.access$801(ImmutableConfig.java:24) ~[arrow-memory-core-15.0.2.jar:15.0.2]
        at org.apache.arrow.memory.ImmutableConfig$InitShim.getAllocationManagerFactory(ImmutableConfig.java:83) ~[arrow-memory-core-15.0.2.jar:15.0.2]
        at org.apache.arrow.memory.ImmutableConfig.<init>(ImmutableConfig.java:47) ~[arrow-memory-core-15.0.2.jar:15.0.2]
        at org.apache.arrow.memory.ImmutableConfig.<init>(ImmutableConfig.java:24) ~[arrow-memory-core-15.0.2.jar:15.0.2]
        at org.apache.arrow.memory.ImmutableConfig$Builder.build(ImmutableConfig.java:485) ~[arrow-memory-core-15.0.2.jar:15.0.2]
        at org.apache.arrow.memory.BaseAllocator.<clinit>(BaseAllocator.java:62) ~[arrow-memory-core-15.0.2.jar:15.0.2]
        at org.apache.doris.service.arrowflight.DorisFlightSqlService.<init>(DorisFlightSqlService.java:47) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.QeService.start(QeService.java:68) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.DorisFE.start(DorisFE.java:213) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.DorisFE.main(DorisFE.java:95) ~[doris-fe.jar:1.2-SNAPSHOT]
```

### Component(s)

Java

**Comment by vibhatha** [comment]
Apache Arrow Java library uses a Netty and the version can be found in the pom. If this is used with a thirdparty project which already uses a particular Netty version, then maybe such issues could occur. But it should be possible to try something like `exclusion` when managing dependencies.

**Comment by xinyiZzz** [comment]
> Apache Arrow Java library uses Netty and the version can be found in the pom. If this is used with a thirdparty project which already uses a particular Netty version, then maybe such issues could occur. But it should be possible to try something like `exclusion` when managing dependencies.
Thanks for your reply,

Netty version in Arrow 15.0.2 pom is 4.1.104.Final, which is the same as the Netty version in my project, so the above error is confusing.
```
<dep.netty-bom.version>4.1.104.Final</dep.netty-bom.version>
```

**Comment by vibhatha** [comment]
Could you please check the dependency tree and see if there is a different version being overriding these from another dependency?

**Comment by xinyiZzz** [comment]
> Could you please check the dependency tree and see if there is a different version being overriding these from another dependency?

You are right, there is another dependency that includes `io.netty.buffer` which overrides the correct `netty.buffer`.

Thanks, helped me learn a lot.

**Comment by vibhatha** [comment]
@xinyiZzz glad you could resolve the issue.
