### ISSUE TITLE
[Integration][Archery] Can't disable Java

### ISSUE THREAD

**Issue by kou** [apache/arrow#44300]
### Describe the bug, including details regarding any error messages, version, and platform.

We have an option to disable Java integration test: `--with-java=0`

If we use it, the following error is occurred:

```console
$ archery docker run -e ARROW_INTEGRATION_JAVA=OFF conda-integration
...
Traceback (most recent call last):
  File "/opt/conda/envs/arrow/bin/archery", line 33, in <module>
    sys.exit(load_entry_point('archery', 'console_scripts', 'archery')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/arrow/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/arrow/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/arrow/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/arrow/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/arrow/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/arrow/dev/archery/archery/cli.py", line 833, in integration
    from .integration.runner import write_js_test_json, run_all_tests
  File "/arrow/dev/archery/archery/integration/runner.py", line 37, in <module>
    from .tester_java import JavaTester
  File "/arrow/dev/archery/archery/integration/tester_java.py", line 54, in <module>
    _arrow_version = load_version_from_pom()
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/arrow/dev/archery/archery/integration/tester_java.py", line 37, in load_version_from_pom
    tree = ET.parse(os.path.join(ARROW_BUILD_ROOT, 'java', 'pom.xml'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/arrow/lib/python3.11/xml/etree/ElementTree.py", line 1219, in parse
    tree.parse(source, parser)
  File "/opt/conda/envs/arrow/lib/python3.11/xml/etree/ElementTree.py", line 570, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/build/java/pom.xml'
```

### Component(s)

Archery, Integration

**Comment by raulcd** [comment]
Issue resolved by pull request 44301
https://github.com/apache/arrow/pull/44301
