### ISSUE TITLE
[Python] RecordBatch.from_struct_array produces invalid batch for some sliced arrays

### ISSUE THREAD

**Issue by wlhjason** [apache/arrow#44318]
### Describe the bug, including details regarding any error messages, version, and platform.

`RecordBatch.from_struct_array` can produce an invalid `RecordBatch` if the input `StructArray` has been sliced.

Examples (tested with pyarrow 17.0.0):
```python
import pyarrow as pa

batch = pa.record_batch({"num": [0, 1, 2, 3]})
sa = batch.to_struct_array()

assert pa.RecordBatch.from_struct_array(sa) == batch  # passes
assert pa.RecordBatch.from_struct_array(sa[1:]) == batch[1:]  # passes
assert pa.RecordBatch.from_struct_array(sa[1:3]) == batch[1:3]  # passes

assert pa.RecordBatch.from_struct_array(sa[:3]) == batch[:3]  # fails
assert pa.RecordBatch.from_struct_array(sa[0:3]) == batch[0:3]  # fails
```

In the failing examples, the created RecordBatch actually fails validation:

```
>>> sliced_batch = pa.RecordBatch.from_struct_array(sa[:3])
>>> sliced_batch
pyarrow.RecordBatch
num: int64
----
num: [0,1,2,3]
>>> sliced_batch.validate()
Traceback (most recent call last):
  ...
  File "pyarrow/table.pxi", line 2535, in pyarrow.lib.RecordBatch.validate
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Number of rows in column 0 did not match batch: 4 vs 3
```

### Component(s)

Python

**Comment by wlhjason** [comment]
In the C++ implementation of `RecordBatch.from_struct_array`, there is some logic to handle sliced arrays, but this doesn't get triggered if the slice offset is 0: https://github.com/apache/arrow/blob/e62fbaafd129931b1c217fcaa1b4c254087ab289/cpp/src/arrow/record_batch.cc#L247

**Comment by wlhjason** [comment]
take

**Comment by pitrou** [comment]
Issue resolved by pull request 47843
https://github.com/apache/arrow/pull/47843
