### ISSUE TITLE
[Java] Exceptions when building MapVector with map values

### ISSUE THREAD

**Issue by 0xderek** [apache/arrow#44353]
### Describe the usage question you have. Please include as many useful details as  possible.

I'm trying to build a MapVector with map as its value, for example Map<Int, Map<Int, Int>>, but the code throws exception when writing data into the inner map.

```java
    @Test
    void testMapOfMap() {
        MapVector vector = new MapVector("map", allocator,
                FieldType.nullable(new ArrowType.Map(false)), null);
        MapWriter writer = vector.getWriter();

        writer.startMap();
        writer.startEntry();

        writer.key().integer().writeInt(1);

        MapWriter innerMapWriter = writer.value().map();
        innerMapWriter.startMap();                         // <- throws at this line
        innerMapWriter.startEntry();
        innerMapWriter.key().integer().writeInt(1);
        innerMapWriter.value().integer().writeInt(2);
        innerMapWriter.endEntry();
        innerMapWriter.endMap();

        writer.endEntry();
        writer.endMap();

        vector.setValueCount(1);
        log.info(vector.toString());
    }
```
Exceptions
```text
java.lang.NullPointerException
	at org.apache.arrow.util.Preconditions.checkNotNull(Preconditions.java:724)
	at org.apache.arrow.vector.types.pojo.FieldType.<init>(FieldType.java:70)
	at org.apache.arrow.vector.types.pojo.FieldType.nullable(FieldType.java:39)
	at org.apache.arrow.vector.complex.UnionVector.addOrGet(UnionVector.java:225)
	at org.apache.arrow.vector.complex.UnionVector.getMap(UnionVector.java:1127)
	at org.apache.arrow.vector.complex.UnionVector.getMap(UnionVector.java:1121)
	at org.apache.arrow.vector.complex.impl.UnionWriter.getMapWriter(UnionWriter.java:191)
	at org.apache.arrow.vector.complex.impl.UnionWriter.getWriter(UnionWriter.java:214)
	at org.apache.arrow.vector.complex.impl.PromotableWriter.getWriter(PromotableWriter.java:321)
	at org.apache.arrow.vector.complex.impl.AbstractPromotableFieldWriter.getWriter(AbstractPromotableFieldWriter.java:80)
	at org.apache.arrow.vector.complex.impl.AbstractPromotableFieldWriter.startMap(AbstractPromotableFieldWriter.java:114)
	at org.apache.arrow.vector.complex.impl.PromotableWriter.startMap(PromotableWriter.java:53)
	at com.example.UtilsTest.testMapOfMap(UtilsTest.java:154)
...
```

Does Arrow support this? Or am I using this wrong?

BTW I'm using JDK 8 and Arrow 17.0.0.

Thanks

### Component(s)

Java

**Comment by 0xderek** [comment]
Some updates:

The demo code works after changing `.map()` calls to `.map(boolean keySorted)`. 

It turns out `UnionMapWriter` doesn't override `map()` and falls back to implementation in `UnionListWriter`. I think this is a bug.

**Comment by lidavidm** [comment]
Issue resolved by pull request 44390
https://github.com/apache/arrow/pull/44390
