### ISSUE TITLE
Loading local huggingface datasets in R package?

### ISSUE THREAD

**Issue by fkgruber** [apache/arrow#44408]
### Describe the usage question you have. Please include as many useful details as  possible.

If I have a dataset stored on a local folder that I downloaded with python hugging face's datasets module how I can I load in in the R arrow package?
This is the content of the directory:

> dataset_info.json        
> state.json               
> data-00000-of-00001.arrow
> 

I tried every function I could think without success

`ds=open_dataset("mydata")`

> Error in `open_dataset()`:
> ! Invalid: Error creating dataset. Could not read schema from './Documents/general/mydata/data-00000-of-00001.arrow'. Is this a 'parquet' file?: Could not open Parquet input source './Documents/general/mydata/data-00000-of-00001.arrow': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.
> ℹ Did you mean to specify a 'format' other than the default (parquet)?
> Run `rlang::last_trace()` to see where the error occurred.
> 

`ds=open_dataset("mydata",format="arrow")`

> Error in `open_dataset()`:
> ! Invalid: Error creating dataset. Could not read schema from './Documents/general/mydata/data-00000-of-00001.arrow'. Is this a 'ipc' file?: Could not open IPC input source './Documents/general/mydata/data-00000-of-00001.arrow': Not an Arrow file
> Run `rlang::last_trace()` to see where the error occurred.

`ds=open_dataset("mydata",format="ipc")`

> Error in `open_dataset()`:
> ! Invalid: Error creating dataset. Could not read schema from './Documents/general/mydata/data-00000-of-00001.arrow'. Is this a 'ipc' file?: Could not open IPC input source './Documents/general/mydata/data-00000-of-00001.arrow': Not an Arrow file
> Run `rlang::last_trace()` to see where the error occurred.

`ds=open_dataset("mydata",format="feather")`

> Error in `open_dataset()`:
> ! Invalid: Error creating dataset. Could not read schema from './Documents/general/mydata/data-00000-of-00001.arrow'. Is this a 'ipc' file?: Could not open IPC input source './Documents/general/mydata/data-00000-of-00001.arrow': Not an Arrow file
> Run `rlang::last_trace()` to see where the error occurred.

`ds=open_dataset("mydata",format="json")`

> Error in `open_dataset()`:
> ! Invalid: Error creating dataset. Could not read schema from './Documents/general/mydata/data-00000-of-00001.arrow'. Is this a 'json' file?: Could not open JSON input source './Documents/general/mydata/data-00000-of-00001.arrow': Invalid: JSON parse error: Invalid value. in row 0
> Run `rlang::last_trace()` to see where the error occurred.
> 

### Component(s)

R

**Comment by assignUser** [comment]
🤗 datasets are saved in the arrow IPC file format not parquet. https://arrow.apache.org/docs/r/reference/read_feather.html should work!

**Comment by assignUser** [comment]
Oh a sanity check on the python side might be good. Try to load it there to make sure it wasn't corrupted during the download or something.

**Comment by fkgruber** [comment]
I got:
`read_feather("./mydata/data-00000-of-00001.arrow")`

> Error: Invalid: Not a Feather V1 or Arrow IPC file
> > 

In python:
`>>> dataset.load_from_disk("mydata")`

> Dataset({
>     features: ['id', 'title', 'context', 'question', 'answers'],
>     num_rows: 87599
> })

>>>

**Comment by assignUser** [comment]
I meant using pyarrow to load the files generated by dataset, I tried that and it fails with the same error as in R with both pyarrow 15 and 17:
```
pyarrow.feather.read_feather("~/.cache/huggingface/datasets/squad/plain_text/0.0.0/7b6d24c440a36b6815f21b70d25016731768db1f/squad-train.arrow")
Traceback (most recent call last):
...
  File "pyarrow/_feather.pyx", line 79, in pyarrow._feather.FeatherReader.__cinit__
  File "pyarrow/error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Not a Feather V1 or Arrow IPC file
```
After perusing the dataset source it turns out that they are using the ipc stream format https://github.com/huggingface/datasets/pull/1933

So you can use `arrow::read_ipc_stream("path/to/file.arrow")` to open it in R.

**Comment by fkgruber** [comment]
Thanks that works. is there any way to use open_dataset with ipc_stream so we can read all files and create a dataset object?

**Comment by assignUser** [comment]
I don't think so as the stream format is just made for a different purpose (hf must have had their reasons to pick it).

Cc @amoeba

**Comment by fkgruber** [comment]
Yes, this is the standard way to save a dataset to disk
https://huggingface.co/docs/datasets/v1.5.0/processing.html#saving-a-processed-dataset-on-disk-and-reload-it

It would be great if we could load this in a dataset object in R.
