### ISSUE TITLE
[Release][Packaging] Wheel content script does not work with local wheel verification

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#44459]
### Describe the bug, including details regarding any error messages, version, and platform.

We added content verification for wheels for this release:
- https://github.com/apache/arrow/issues/43299

This works for individual wheel verification bus it currently failing when verifying all the wheels for the release.

The error:
```
+ python /tmp/arrow-18.0.0.UeQlC/apache-arrow-18.0.0/ci/scripts/python_wheel_validate_contents.py --path /tmp/arrow-18.0.0.UeQlC/apache-arrow-18.0.0/python/repaired_wheels
Traceback (most recent call last):
  File "/tmp/arrow-18.0.0.UeQlC/apache-arrow-18.0.0/ci/scripts/python_wheel_validate_contents.py", line 48, in <module>
    main()
  File "/tmp/arrow-18.0.0.UeQlC/apache-arrow-18.0.0/ci/scripts/python_wheel_validate_contents.py", line 44, in main
    validate_wheel(args.path)
  File "/tmp/arrow-18.0.0.UeQlC/apache-arrow-18.0.0/ci/scripts/python_wheel_validate_contents.py", line 28, in validate_wheel
    assert len(wheels) == 1, error_msg
           ^^^^^^^^^^^^^^^^
AssertionError: 0 wheels found but only 1 expected ([])
Failed to verify release candidate. See /tmp/arrow-18.0.0.UeQlC for details.
Error: `docker compose --file=/home/runner/work/crossbow/crossbow/arrow/docker-compose.yml run --rm -e VERIFY_VERSION=18.0.0 -e VERIFY_RC=0 -e TEST_DEFAULT=0 -e TEST_WHEELS=1 almalinux-verify-rc` exited with a non-zero exit code 1, see the process log above.

The docker-compose command was invoked with the following parameters:
```

### Component(s)

Packaging, Release

**Comment by raulcd** [comment]
We could try to validate the binary wheels modifying the folder to check the downloaded folder but we would have to also modify the script because we download all the wheels at once:
```
+ python /tmp/arrow-18.0.0.pfUwd/apache-arrow-18.0.0/ci/scripts/python_wheel_validate_contents.py --path /tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0
Traceback (most recent call last):
  File "/tmp/arrow-18.0.0.pfUwd/apache-arrow-18.0.0/ci/scripts/python_wheel_validate_contents.py", line 48, in <module>
    main()
  File "/tmp/arrow-18.0.0.pfUwd/apache-arrow-18.0.0/ci/scripts/python_wheel_validate_contents.py", line 44, in main
    validate_wheel(args.path)
  File "/tmp/arrow-18.0.0.pfUwd/apache-arrow-18.0.0/ci/scripts/python_wheel_validate_contents.py", line 28, in validate_wheel
    assert len(wheels) == 1, error_msg
           ^^^^^^^^^^^^^^^^
AssertionError: 24 wheels found but only 1 expected ([PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp313-cp313t-manylinux_2_17_x86_64.manylinux2014_x86_64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp313-cp313-manylinux_2_28_aarch64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp312-cp312-manylinux_2_28_x86_64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp313-cp313t-manylinux_2_17_aarch64.manylinux2014_aarch64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp39-cp39-manylinux_2_28_x86_64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp311-cp311-manylinux_2_28_x86_64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp313-cp313t-manylinux_2_28_aarch64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp313-cp313-manylinux_2_17_aarch64.manylinux2014_aarch64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp311-cp311-manylinux_2_28_aarch64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp312-cp312-manylinux_2_28_aarch64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp310-cp310-manylinux_2_28_aarch64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp313-cp313-manylinux_2_28_x86_64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp39-cp39-manylinux_2_28_aarch64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp313-cp313t-manylinux_2_28_x86_64.whl'), PosixPath('/tmp/arrow-18.0.0.pfUwd/binaries/python-rc/18.0.0-rc0/pyarrow-18.0.0-cp310-cp310-manylinux_2_28_x86_64.whl')])
Failed to verify release candidate. See /tmp/arrow-18.0.0.pfUwd for details.
Error: `docker compose --file=/home/raulcd/code/arrow/docker-compose.yml run --rm -e VERIFY_VERSION=18.0.0 -e VERIFY_RC=0 -e TEST_DEFAULT=0 -e TEST_WHEELS=1 almalinux-verify-rc` exited with a non-zero exit code 1, see the process log above.
```

**Comment by kou** [comment]
Issue resolved by pull request 44460
https://github.com/apache/arrow/pull/44460
