### ISSUE TITLE
[GLib] Unit test failed if -DARROW_EXTRA_ERROR_CONTEXT=ON in the C++ build

### ISSUE THREAD

**Issue by hiroyuki-sato** [apache/arrow#44483]
### Describe the bug, including details regarding any error messages, version, and platform.

Unit test failed if -DARROW_EXTRA_ERROR_CONTEXT=ON 

<img width="1012" alt="screenshot 2024-10-21 16 05 59" src="https://github.com/user-attachments/assets/adce7208-566b-43e8-a50f-e7c31ffb3473">

## Environment

* Ruby 3.3.4
* Apache Arrow/red-arrow: 18.0.0-SNAPSHOT (54697eaefeb151ad195f3a5812aafa48ba77c45e)
* OS: macOS 14.7

## Reproduce steps

```
cd cpp/
mkdir build
cmake .. --preset ninja-debug-maximal \
  -DCMAKE_INSTALL_PREFIX=/tmp/local \
  -DARROW_CUDA=OFF \
  -DARROW_SKYHOOK=OFF \
  -DARROW_EXTRA_ERROR_CONTEXT=ON
cmake --build .
cmake --install .
```

```
meson setup \
      --backend=ninja \
      --prefix=/tmp/local \
      --libdir=lib \
      --pkg-config-path=/tmp/local/lib/pkgconfig \
      -Ddoc=false \
      -Dvapi=false \
      -Dwerror=false \
      c_glib.build \
      c_glib
ninja -C c_glib.build all
```

```
cd c_glib.build
../c_glib/test/run-test.sh
```

## Error

```
=================================================================================================================================================================================================
F
=================================================================================================================================================================================================
Failure: test_invalid_precision(TestDecimal128DataType)
/Users/user/OpenProjects/arrow/arrow/c_glib/test/test-decimal128-data-type.rb:52:in `test_invalid_precision'
     49:   def test_invalid_precision
     50:     message =
     51:       "[decimal128-data-type][new]: Invalid: Decimal precision out of range [1, 38]: 39"
  => 52:     assert_raise(Arrow::Error::Invalid.new(message)) do
     53:       Arrow::Decimal128DataType.new(39, 1)
     54:     end
     55:   end

<Arrow::Error::Invalid(<[decimal128-data-type][new]: Invalid: Decimal precision out of range [1, 38]: 39>)> expected but was
<Arrow::Error::Invalid(<[decimal128-data-type][new]: Invalid: Decimal precision out of range [1, 38]: 39
/Users/user/OpenProjects/arrow/arrow/cpp/src/arrow/type.cc:1525  ValidateDecimalPrecision<Decimal128Type>(precision)>)
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:715:in `invoke'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:715:in `invoke'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:366:in `block (2 levels) in initialize'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:365:in `catch'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:365:in `block in initialize'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:364:in `each'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:364:in `initialize'
/Users/user/OpenProjects/arrow/arrow/c_glib/test/test-decimal128-data-type.rb:53:in `new'
/Users/user/OpenProjects/arrow/arrow/c_glib/test/test-decimal128-data-type.rb:53:in `block in test_invalid_precision'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/assertions.rb:1961:in `block (2 levels) in _assert_raise'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/assertions.rb:55:in `block in assert_block'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/assertions.rb:1913:in `_wrap_assertion'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/assertions.rb:54:in `assert_block'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/assertions.rb:1959:in `block in _assert_raise'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/assertions.rb:1918:in `_wrap_assertion'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/assertions.rb:1945:in `_assert_raise'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/assertions.rb:287:in `assert_raise'
/Users/user/OpenProjects/arrow/arrow/c_glib/test/test-decimal128-data-type.rb:52:in `test_invalid_precision'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/testcase.rb:871:in `run_test'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/testcase.rb:566:in `block (2 levels) in run'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/fixture.rb:276:in `block in create_fixtures_runner'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/fixture.rb:276:in `block in create_fixtures_runner'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/fixture.rb:257:in `run_fixture'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/fixture.rb:292:in `run_setup'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/testcase.rb:564:in `block in run'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/testcase.rb:563:in `catch'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/testcase.rb:563:in `run'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/testsuite.rb:124:in `run_test'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/testsuite.rb:53:in `run'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/testsuite.rb:124:in `run_test'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/testsuite.rb:53:in `run'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/ui/testrunnermediator.rb:67:in `run_suite'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/ui/testrunnermediator.rb:45:in `block (2 levels) in run'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/ui/testrunnermediator.rb:102:in `with_listener'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/ui/testrunnermediator.rb:41:in `block in run'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/ui/testrunnermediator.rb:39:in `catch'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/ui/testrunnermediator.rb:39:in `run'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/ui/testrunner.rb:40:in `start_mediator'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/ui/testrunner.rb:25:in `start'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/autorunner.rb:458:in `block in run'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/autorunner.rb:514:in `change_work_directory'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/autorunner.rb:457:in `run'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/autorunner.rb:66:in `run'
/Users/user/OpenProjects/arrow/arrow/c_glib/test/run-test.rb:112:in `<main>'
>
=================================================================================================================================================================================================
F
=================================================================================================================================================================================================
Failure: test_invalid_precision(TestDecimal256DataType)
/Users/user/OpenProjects/arrow/arrow/c_glib/test/test-decimal256-data-type.rb:52:in `test_invalid_precision'
     49:   def test_invalid_precision
     50:     message =
     51:       "[decimal256-data-type][new]: Invalid: Decimal precision out of range [1, 76]: 77"
  => 52:     assert_raise(Arrow::Error::Invalid.new(message)) do
     53:       Arrow::Decimal256DataType.new(77, 1)
     54:     end
     55:   end

<Arrow::Error::Invalid(<[decimal256-data-type][new]: Invalid: Decimal precision out of range [1, 76]: 77>)> expected but was
<Arrow::Error::Invalid(<[decimal256-data-type][new]: Invalid: Decimal precision out of range [1, 76]: 77
/Users/user/OpenProjects/arrow/arrow/cpp/src/arrow/type.cc:1538  ValidateDecimalPrecision<Decimal256Type>(precision)>)
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:715:in `invoke'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:715:in `invoke'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:366:in `block (2 levels) in initialize'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:365:in `catch'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:365:in `block in initialize'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:364:in `each'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/gobject-introspection-4.2.4/lib/gobject-introspection/loader.rb:364:in `initialize'
/Users/user/OpenProjects/arrow/arrow/c_glib/test/test-decimal256-data-type.rb:53:in `new'
/Users/user/OpenProjects/arrow/arrow/c_glib/test/test-decimal256-data-type.rb:53:in `block in test_invalid_precision'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/assertions.rb:1961:in `block (2 levels) in _assert_raise'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/assertions.rb:55:in `block in assert_block'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/assertions.rb:1913:in `_wrap_assertion'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/assertions.rb:54:in `assert_block'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/assertions.rb:1959:in `block in _assert_raise'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/assertions.rb:1918:in `_wrap_assertion'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/assertions.rb:1945:in `_assert_raise'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/assertions.rb:287:in `assert_raise'
/Users/user/OpenProjects/arrow/arrow/c_glib/test/test-decimal256-data-type.rb:52:in `test_invalid_precision'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/testcase.rb:871:in `run_test'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/testcase.rb:566:in `block (2 levels) in run'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/fixture.rb:276:in `block in create_fixtures_runner'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/fixture.rb:276:in `block in create_fixtures_runner'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/fixture.rb:257:in `run_fixture'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/fixture.rb:292:in `run_setup'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/testcase.rb:564:in `block in run'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/testcase.rb:563:in `catch'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/testcase.rb:563:in `run'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/testsuite.rb:124:in `run_test'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/testsuite.rb:53:in `run'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/testsuite.rb:124:in `run_test'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/testsuite.rb:53:in `run'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/ui/testrunnermediator.rb:67:in `run_suite'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/ui/testrunnermediator.rb:45:in `block (2 levels) in run'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/ui/testrunnermediator.rb:102:in `with_listener'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/ui/testrunnermediator.rb:41:in `block in run'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/ui/testrunnermediator.rb:39:in `catch'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/ui/testrunnermediator.rb:39:in `run'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/ui/testrunner.rb:40:in `start_mediator'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/ui/testrunner.rb:25:in `start'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/autorunner.rb:458:in `block in run'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/autorunner.rb:514:in `change_work_directory'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/autorunner.rb:457:in `run'
/Users/user/.rbenv.m1/versions/3.3.4/lib/ruby/gems/3.3.0/gems/test-unit-3.6.1/lib/test/unit/autorunner.rb:66:in `run'
/Users/user/OpenProjects/arrow/arrow/c_glib/test/run-test.rb:112:in `<main>'
>
=================================================================================================================================================================================================
```

### Component(s)

GLib

**Comment by kou** [comment]
Issue resolved by pull request 44484
https://github.com/apache/arrow/pull/44484
