### ISSUE TITLE
Error using extension types in struct in PyArrow

### ISSUE THREAD

**Issue by stemillington-flock** [apache/arrow#44853]
### Describe the bug, including details regarding any error messages, version, and platform.

The following code runs without problem
```
from pyarrow import schema, struct, field
from pyarrow import uuid

schema([
        field("col", uuid())
]).empty_table()
```

However when i try to move the uuid column into a struct as below
```
schema([
    field("parent", struct([
        field("col", uuid())
    ]))
]).empty_table()
```

I get the error
```
ArrowNotImplementedError                  Traceback (most recent call last)
Cell In[77], [line 5](vscode-notebook-cell:?execution_count=77&line=5)
      [1](vscode-notebook-cell:?execution_count=77&line=1) schema([
      [2](vscode-notebook-cell:?execution_count=77&line=2)     field("parent", struct([
      [3](vscode-notebook-cell:?execution_count=77&line=3)         field("col", uuid())
      [4](vscode-notebook-cell:?execution_count=77&line=4)     ]))
----> [5](vscode-notebook-cell:?execution_count=77&line=5) ]).empty_table()

File ~/Code/map-matching/.venv/lib/python3.12/site-packages/pyarrow/types.pxi:2988, in pyarrow.lib.Schema.empty_table()

File ~/Code/map-matching/.venv/lib/python3.12/site-packages/pyarrow/array.pxi:4791, in pyarrow.lib._empty_array()

File ~/Code/map-matching/.venv/lib/python3.12/site-packages/pyarrow/array.pxi:370, in pyarrow.lib.array()

File ~/Code/map-matching/.venv/lib/python3.12/site-packages/pyarrow/array.pxi:42, in pyarrow.lib._sequence_to_array()

File ~/Code/map-matching/.venv/lib/python3.12/site-packages/pyarrow/error.pxi:155, in pyarrow.lib.pyarrow_internal_check_status()

File ~/Code/map-matching/.venv/lib/python3.12/site-packages/pyarrow/error.pxi:92, in pyarrow.lib.check_status()

ArrowNotImplementedError: extension
```

This appears to happen when any extension type is moved into a struct. Using pyarrow 18.0.0 on a mac book pro M2.

### Component(s)

Python

**Comment by raulcd** [comment]
Example with a fixed shape tensor on a struct:
```python
>>> schema([field("parent", struct([field("col", pa.fixed_shape_tensor(pa.int32(), (1,2)))]))]).empty_table()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/types.pxi", line 3041, in pyarrow.lib.Schema.empty_table
    arrays = [_empty_array(field.type) for field in self]
  File "pyarrow/array.pxi", line 4823, in pyarrow.lib._empty_array
    arr = array([], type=type)
  File "pyarrow/array.pxi", line 370, in pyarrow.lib.array
    result = _sequence_to_array(obj, mask, size, type, pool, c_from_pandas)
  File "pyarrow/array.pxi", line 42, in pyarrow.lib._sequence_to_array
    chunked = GetResultValue(
  File "pyarrow/error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
    return check_status(status)
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
    raise convert_status(status)
pyarrow.lib.ArrowNotImplementedError: extension
```

**Comment by sibbiii** [comment]
Did somebody find a solution or a workaround here to create empty tables with nested extension types?

**Comment by pkrack** [comment]
@sibbiii You can use the `Table.from_arrays` constructor with an empty array.
Example using the struct type above:

```
import pyarrow as pa
schema = pa.schema([pa.field("parent", pa.struct([pa.field("col", pa.uuid())]))])
empty_table = pa.Table.from_arrays([pa.array([])], schema=schema)
```

**Comment by sibbiii** [comment]
that indeed works, thanks!

**Comment by AlenkaF** [comment]
I think this could be closed as a duplicate of: https://github.com/apache/arrow/issues/34985 and we can track the work there.
I am also planning to create an umbrella issue that will help move the support for extension types in PyArrow forward and can be used to track the overall progress.
