### ISSUE TITLE
[CI][C++] test-build-cpp-fuzz nightly failures

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#45059]
### Describe the bug, including details regarding any error messages, version, and platform.

The nightly build `test-build-cpp-fuzz` has started failing recently:
https://github.com/ursacomputing/crossbow/actions/runs/12383983437/job/34567737029

```
  Downloading PyYAML-6.0.tar.gz (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 17.9 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-06mbo987/overlay/local/lib/python3.12/dist-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-06mbo987/overlay/local/lib/python3.12/dist-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-06mbo987/overlay/local/lib/python3.12/dist-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "/tmp/pip-build-env-06mbo987/overlay/local/lib/python3.12/dist-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-06mbo987/overlay/local/lib/python3.12/dist-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-06mbo987/overlay/local/lib/python3.12/dist-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-06mbo987/overlay/local/lib/python3.12/dist-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-06mbo987/overlay/local/lib/python3.12/dist-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-06mbo987/overlay/local/lib/python3.12/dist-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-06mbo987/overlay/local/lib/python3.12/dist-packages/setuptools/command/egg_info.py", line 313, in run
          self.find_sources()
        File "/tmp/pip-build-env-06mbo987/overlay/local/lib/python3.12/dist-packages/setuptools/command/egg_info.py", line 321, in find_sources
          mm.run()
        File "/tmp/pip-build-env-06mbo987/overlay/local/lib/python3.12/dist-packages/setuptools/command/egg_info.py", line 544, in run
          self.add_defaults()
        File "/tmp/pip-build-env-06mbo987/overlay/local/lib/python3.12/dist-packages/setuptools/command/egg_info.py", line 582, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-06mbo987/overlay/local/lib/python3.12/dist-packages/setuptools/command/sdist.py", line 109, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-06mbo987/overlay/local/lib/python3.12/dist-packages/setuptools/_distutils/command/sdist.py", line 238, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-06mbo987/overlay/local/lib/python3.12/dist-packages/setuptools/_distutils/command/sdist.py", line 323, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 204, in get_source_files
        File "/tmp/pip-build-env-06mbo987/overlay/local/lib/python3.12/dist-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

### Component(s)

C++, Continuous Integration

**Comment by pitrou** [comment]
Issue resolved by pull request 45060
https://github.com/apache/arrow/pull/45060
