### ISSUE TITLE
Ruby CompressionType.values undefined

### ISSUE THREAD

**Issue by Makapoxa** [apache/arrow#4506]
When i'm trying to include red-arrow version 0.12.x to my project i get 
```
undefined local variable or method `values' for Arrow::CompressionType:Class (NameError)
```

output from cloning this repo and running `rake test` in ruby/red-arrow dir
```
$ rake test
cd -
/usr/local/bin/ruby test/run-test.rb
Traceback (most recent call last):
	16: from test/run-test.rb:33:in `<main>'
	15: from test/run-test.rb:33:in `require_relative'
	14: from /tmp/arrow/ruby/red-arrow/test/helper.rb:18:in `<top (required)>'
	13: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	12: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /tmp/arrow/ruby/red-arrow/lib/arrow.rb:24:in `<top (required)>'
	10: from /tmp/arrow/ruby/red-arrow/lib/arrow.rb:28:in `<module:Arrow>'
	 9: from /tmp/arrow/ruby/red-arrow/lib/arrow/loader.rb:24:in `load'
	 8: from /bundle/gems/gobject-introspection-3.3.6/lib/gobject-introspection/loader.rb:25:in `load'
	 7: from /bundle/gems/gobject-introspection-3.3.6/lib/gobject-introspection/loader.rb:45:in `load'
	 6: from /tmp/arrow/ruby/red-arrow/lib/arrow/loader.rb:30:in `post_load'
	 5: from /tmp/arrow/ruby/red-arrow/lib/arrow/loader.rb:38:in `require_libraries'
	 4: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /tmp/arrow/ruby/red-arrow/lib/arrow/compression-type.rb:18:in `<top (required)>'
	 1: from /tmp/arrow/ruby/red-arrow/lib/arrow/compression-type.rb:19:in `<module:Arrow>'
/tmp/arrow/ruby/red-arrow/lib/arrow/compression-type.rb:21:in `<class:CompressionType>': undefined local variable or method `values' for Arrow::CompressionType:Class (NameError)
rake aborted!
```

**Comment by shiro615** [comment]
What version of Arrow GLib is installed?
Red Arrow uses Arrow GLib. `Arrow::CompressionType.values` was added in 0.12.0. You may need to upgrade Arrow GLib.

**Comment by Makapoxa** [comment]
yeah sorry, found out the same that you just said
