### ISSUE TITLE
[Ruby] `Arrow::Column#size` doesn't work for `Arrow::RecordBatch`

### ISSUE THREAD

**Issue by kou** [apache/arrow#45119]
### Describe the bug, including details regarding any error messages, version, and platform.

```ruby
require "arrow"
Arrow::RecordBatch.new({"a" => [1, 2, 3]}).columns[0].size
```

```text
/tmp/local/lib/ruby/gems/3.4.0+1/gems/red-arrow-19.0.0.SNAPSHOT/lib/arrow/column.rb:62:in 'Arrow::Column#n_rows': undefined method 'n_rows' for an instance of Arrow::UInt8Array (NoMethodError)

      @data.n_rows
           ^^^^^^^
	from /tmp/a.rb:2:in '<main>'
```

### Component(s)

Ruby

**Comment by kou** [comment]
Issue resolved by pull request 45133
https://github.com/apache/arrow/pull/45133
