### ISSUE TITLE
Access Azure Data Lake Gen2 via PyArrow

### ISSUE THREAD

**Issue by ikravche** [apache/arrow#4888]
Hello,
I am trying to connect to my Data Lake **Gen2** Storage from Azure hosted virtual machine via hdfs.connect method, and instantly getting timeout; I was trying to use different driver "**libhdfs3**", and nothing really changed. Shared Key to access storage account is written in /opt/hadoop-3.2.0/etc/hadoop/**core-site.xml** and when I was using commands "hdfs dfs -get" the key was successfully read by the program and getting the file was not a problem at all, but at this point I am not sure If pyarrow is reading the key from configuration file as well as I am not sure if pyarrow supports connection do ADLS Gen2. Can somebody clarify those details please? Sitting third day on it and cannot understand is it my mistake or there is no such an option. 
Environment variables are set according to hadoop and pyarrow instructions, libraries "libhdfs" and "libhdfs3" are located in /opt/hadoop-3.2.0/lib/native . 

I am running following script :

`resp=$(python3 -c 'import pyarrow as pa; fs = pa.hdfs.connect(host="centerofexcellence.dfs.core.windows.net/analysis",  port=8020,  driver="libhdfs3")`

Sample output
```
2019-07-16 10:15:53.773990, p57668, th139653677737792, ERROR Failed to setup RPC connection to "centerofexcellence.dfs.core.windows.net:8020" caused by:
TcpSocket.cpp: 283: HdfsTimeoutException: Connect to "centerofexcellence.dfs.core.windows.net:8020" timeout
	@	Unknown
	@	Unknown
	@	Unknown
	@	Unknown
	@	Unknown
	@	Unknown
	@	Unknown
	@	Unknown
	@	Unknown
	@	Unknown
	@	Unknown
	@	Unknown
	@	arrow::io::HadoopFileSystem::Connect(arrow::io::HdfsConnectionConfig const*, std::shared_ptr<arrow::io::HadoopFileSystem>*)
	@	__pyx_pw_7pyarrow_3lib_16HadoopFileSystem_3_connect(_object*, _object*, _object*)
	@	builtin_sorted.cold.2325
	@	PyCell_New
	@	_PyFunction_FastCallDict
	@	PyArg_UnpackTuple
	@	PyByteArray_Resize
	@	enum_new.cold.2332
	@	os_mknod
	@	warnings_warn_explicit
	@	unicode_isalpha
	@	builtin_any
	@	lru_cache_new.cold.2327
	@	_PyObject_GC_Resize
	@	PyWeakref_NewRef
	@	assemble
	@	PyArg_UnpackTuple
	@	tupleitem
	@	PyWeakref_NewRef
	@	assemble
	@	PyLong_FromLong
	@	long_add
	@	symtable_visit_expr
	@	Unknown
	@	symtable_visit_slice
	@	_PyEval_EvalFrameDefault
	@	split.cold.1613
	@	Unknown
	@	fileio_new

2019-07-16 10:15:53.774092, p57668, th139653677737792, INFO Retrying connect to server: "centerofexcellence.dfs.core.windows.net:8020". Already tried 2 time(s)
2019-07-16 10:18:04.846982, p57668, th139653677737792, ERROR Failed to setup RPC connection to "centerofexcellence.dfs.core.windows.net:8020" caused by:
TcpSocket.cpp: 283: HdfsTimeoutException: Connect to "centerofexcellence.dfs.core.windows.net:8020" timeout
```

With different driver:
script - 

`resp=$(python3 -c 'import pyarrow as pa; fs = pa.hdfs.connect(host="analysis@centerofexcellence.dfs.core.windows.net/",  port=8020); fs.ls("/first")')
`

out:
```
2019-07-16 10:52:10,885 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2019-07-16 10:52:31,586 INFO ipc.Client: Retrying connect to server: centerofexcellence.dfs.core.windows.net/20.38.108.226:8020. Already tried 0 time(s); maxRetries=45
2019-07-16 10:52:51,607 INFO ipc.Client: Retrying connect to server: centerofexcellence.dfs.core.windows.net/20.38.108.226:8020. Already tried 1 time(s); maxRetries=45
```

**Comment by wesm** [comment]
We'll have to discuss in a more appropriate place. Maybe user@arrow.apache.org?

**Comment by ikravche** [comment]
Generally I was trying to connect in wrong way, and this one is proper:
`fs = pa.hdfs.connect(host="abfss://analysis@centerofexcellence.dfs.core.windows.net/")`
In my case after such a command next what I saw was an error NullPointerException, and it was about SSL:
```
    at org.wildfly.openssl.CipherSuiteConverter.toJava(CipherSuiteConverter.java:284)
    at org.wildfly.openssl.OpenSSLEngine.toJavaCipherSuite(OpenSSLEngine.java:1021)
    at org.wildfly.openssl.OpenSSlSession.initCipherSuite(OpenSSlSession.java:305)
    at org.wildfly.openssl.OpenSSlSession.initialised(OpenSSlSession.java:296)
```
and the solution was next:
find folder, where hadoop is installed, then go to directory 
`share/hadoop/tools/lib` and locate jar called `wildfly-openssl-1.0.4.Final.jar`
My version of hadoop is 3.2.0 and I have no idea why do they use 1.0.4 version,
next my step was to download wildfly-openssl-1.0.7.Final.jar
`replace` old jar by new one, and `rename` 1.0.7 to 1.0.4, if You will not rename it probably You will get ClassNotFoundException as I did, unfortunately still I didn't find a place where is it binded, but with all the above it works. Hope this will help somebody.

**Comment by sureshsargar** [comment]
@ikravche  this helps for me.
