### ISSUE TITLE
pyarrow wheel does not install or build on Python 3.8.2 on Windows 10 on Intel platform.  

### ISSUE THREAD

**Issue by richdevboston** [apache/arrow#6902]
pyarrow wheel does not build on Python 3.8.2 on Windows 10 on Intel platform.  

I am trying to install Apache Superset on Windows 10 in Python pip environment using virtualenv.  

Errors shown below....

I am ready to give up on Apache and Superset totally.  Too many problems with too many moving parts.  Apache seems to only work for Unix hackers.   Will try downgrading to Python 3.7 on Windows 10 to see if pyarrow works in that runtime environment.  

```
# pip install pyarrow
Collecting pyarrow
  Downloading pyarrow-0.16.0.tar.gz (5.7 MB)
     |████████████████████████████████| 5.7 MB 6.8 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting numpy>=1.14
  Using cached numpy-1.18.2-cp38-cp38-win32.whl (10.8 MB)
Collecting six>=1.0.0
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Building wheels for collected packages: pyarrow
  Building wheel for pyarrow (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\superset2020\devzone\scripts\python.exe' 'c:\superset2020\devzone\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\richadmin\AppData\Local\Temp\tmpdz5a3cyx'
       cwd: C:\Users\richadmin\AppData\Local\Temp\pip-install-ozpru4s0\pyarrow
  Complete output (474 lines):
  running bdist_wheel

.....

cut  many lines....
....
  running build_ext
  creating C:\Users\richadmin\AppData\Local\Temp\pip-install-ozpru4s0\pyarrow\build\temp.win32-3.8
  Traceback (most recent call last):
    File "c:\superset2020\devzone\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 257, in <module>
      main()
    File "c:\superset2020\devzone\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\superset2020\devzone\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 181, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\richadmin\AppData\Local\Temp\pip-build-env-pkpyvksi\overlay\Lib\site-packages\setuptools\build_meta.py", line 212, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "C:\Users\richadmin\AppData\Local\Temp\pip-build-env-pkpyvksi\overlay\Lib\site-packages\setuptools\build_meta.py", line 198, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\richadmin\AppData\Local\Temp\pip-build-env-pkpyvksi\overlay\Lib\site-packages\setuptools\build_meta.py", line 249, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\richadmin\AppData\Local\Temp\pip-build-env-pkpyvksi\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 574, in <module>
      setup(
    File "C:\Users\richadmin\AppData\Local\Temp\pip-build-env-pkpyvksi\overlay\Lib\site-packages\setuptools\__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "C:\ProgramData\Python3.8\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\ProgramData\Python3.8\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\ProgramData\Python3.8\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\richadmin\AppData\Local\Temp\pip-build-env-pkpyvksi\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "C:\ProgramData\Python3.8\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\ProgramData\Python3.8\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\ProgramData\Python3.8\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\ProgramData\Python3.8\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\ProgramData\Python3.8\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 94, in run
      self._run_cmake()
    File "setup.py", line 268, in _run_cmake
      raise RuntimeError('Not supported on 32-bit Windows')
  RuntimeError: Not supported on 32-bit Windows
  ----------------------------------------
  ERROR: Failed building wheel for pyarrow
Failed to build pyarrow
ERROR: Could not build wheels for pyarrow which use PEP 517 and cannot be installed directly
```

**Comment by xhochy** [comment]
Either your Windows or your Python installation is 32bit but Arrow doesn't support 32bit platforms. Check that both Windows and Python are a 64bit installation to install `pyarrow`. Then you should also be able to obtain wheels instead of sdists and no compilaton should happen.

**Comment by wesm** [comment]
> I am ready to give up on Apache and Superset totally. Too many problems with too many moving parts. Apache seems to only work for Unix hackers. 

Keep in mind that these kinds of comments aren't very helpful. We know what it's like to be frustrated but trust that these communities are working hard in good faith to produce software that works, and we at least in Apache Arrow have spent a lot of time and energy (mostly on a volunteer basis, I will add) supporting Windows already.

**Comment by richdevboston** [comment]
Hi Wes,

I personally appreciate all the great work that you have done and do with
Pandas.  It is a truly amazing and powerful package that has advanced
society greatly.  I train people how to use pandas, and use it myself
routinely.

I appreciate all the effort that volunteers put into the open source
products and process.  It takes many high-level engineers and programmers
to accomplish so much. Your efforts advance society and business
immeasurably.  I think that sponsored efforts like Apache Arrow and
Superset are great.

I wish more effort would be put into the Windows platform versions of the
Apache open source products, directly by Microsoft since Microsoft supplies
this most widely used OS platform for consumers and business analytics.  I
know there are many more mobile than desktop devices, but I don't count
cell phones and tablets in the analytics game because they are not (yet?)
primary or distributed high-performance computing endpoints.

I just spent the better part of 2 weeks working to get Superset to work
natively on Windows 10, so the community has a version that "just works"
with a clean installation without futzing around or frustrating dead ends.
I know there are Superset Docker container versions available, but most of
them have problems on Windows because Docker on Windows is immature and
comes with its own frustrating version and incompatibility issues.  My goal
for a Windows-native version is to stop burdening Windows users with the
additional complexity (and knowledge requirements) of Docker.  My message
post was a sign of my frustration with Superset and Docker Windows
incompatibility.

I apologize for expressing my frustration publicly, and I will refrain from
such comments in the future.

Thank you.

Best Regards,

Rich Lysakowski, Ph.D.
Data Scientist and Analytics Engineer,

**Comment by danield137** [comment]
Just to understand the status, what can be done for 32bit python on 64bit windows?

**Comment by wesm** [comment]
Locked the issue. Please follow up on JIRA or the mailing list
